### ISSUE TITLE
Review all uses of unbounded numbers

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1432]
We use `Natural`/`Integer` in various places in the spec, most likely for consistency with the formal spec. But this is a little annoying for implementation, where we'd like to make assumptions about the maximum size. Consider whether we can replace these with bounded types.

**Comment by lehins** [comment]
All protocol parameters have been switched to bounded types.
To my knowledge there are no unbounded types anymore that can be provided by the user, with a natural exception of Plutus' `Data` and `TxAuxData`'s `Metadata`.
