### ISSUE TITLE
Monotonically increasing Byron block header check

### ISSUE THREAD

**Issue by johnalotoski** [IntersectMBO/cardano-ledger#1499]
The byron protocol as implemented by cardano-sl enforced block header protocol versioning to have the same or larger version than last adopted, as seen here for example:
```
[cardano-sl.node:Warning:ThreadId 333] [2020-05-27 22:01:12.85 UTC] Failed to verify blocks: wrong protocol version has been seen in header: 0.2.0 (current adopted is 1.0.0), this version is smaller than last adopted or is not confirmed
```
The byron protocol as implemented by cardano-node does not enforce this header validation or warn on it when the block version decreases from the block version last adopted, such as in the example that generated the error above on legacy cardano-sl; in this case, no error was observed with cardano-node v.1.12.0 on nodes forging such blocks.

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future
