### ISSUE TITLE
Performance micro-benchmarks for Shelley validation

### ISSUE THREAD

**Issue by dcoutts** [IntersectMBO/cardano-ledger#1504]
We need to verify that we do not have STS rules that accidentally have the wrong asymptotic complexity. We can do this by writing `criterion` micro-benchmarks where we use large ledger states, and check that tx validation times are broadly as expected and in line with the equivalent times in Byron.

For example, at the time of writing, in the UTxO rule, we check that the transaction inputs are valid in a way that is O(n) in the size of the UTxO, when in fact we could do it O(m*log(n/m + 1))  (m being size of txins, n size of utxo).

So a first task would be to set up a criterion test that demonstrates this. We could then use the same setup to look for similar problems.

@JaredCorduan says:
> We could probably start with our valid trace generation for the LEDGER rule. The `forAllLedgerTrace` function generates a trace for the ledger rule, where signals are transactions and the state has things like the UTxOs. I think maybe we could adjust the constants in `geConstants` to make a large genesis state. The property can be trivial (always true).  To see `forAllLedgerTrace` in action, you can look at all the tests in the same file that `forAllLedgerTrace` is defined in.

**Comment by kevinhammond** [comment]
For avoidance of doubt, this is internal and needs detailed design/implementation work, rather than being something to pass on to the benchmarking team.
