### ISSUE TITLE
Use fixed precision in implementation of `UnitInterval`

### ISSUE THREAD

**Issue by Jimbo4350** [IntersectMBO/cardano-ledger#1508]
We should be using fixed precision in the implementation of `UnitInterval` because it is part of the on-chain representation. We can do this via using `approxRational` (with `fpEpislon`) in its smart constructors, or by changing the representation to use fixed precision. 

`fpEpsilon` = 1e-17

**Comment by dcoutts** [comment]
And in particular we need to check that the CBOR representation is of bounded size, so have to be careful with the use of `Integer`. If 64bit sizes are ok for the `Rational` representation then we can use that in the CBOR instance.
