### ISSUE TITLE
DoS Issue with Update Proposals in Byron

### ISSUE THREAD

**Issue by troedfach** [IntersectMBO/cardano-ledger#1514]
Protocol version update proposals can either increase the protocol major version or protocol minor version, and are free to choose an Alt version (to differentiate proposals increasing the same version). The [Alt](https://github.com/input-output-hk/cardano-ledger-specs/blob/8f10a78cc87adcb8bff346858b5a9f4c5b84e80e/byron/ledger/impl/src/Cardano/Chain/Update/ProtocolVersion.hs#L26) version is a Word8.

This could lead to a DoS issue where, if an attacker can submit 256 update proposals (one per each Alt version) increasing the protocol minor version by 1 and 256 update proposals increasing the protocol major version by 1, this would block any other update proposals from being registered for the lifetime of those proposals. Afterwards, the attacker could submit new proposals to continue blocking.

In order to carry this out the attacker would need a genesis key (or be delegated to by a genesis key), and be able to submit 512 update proposals one after another, without leaving any slots open for a legitimate proposal.

We tested this on an internal testnet and it appears to be viable, if the attacker has a genesis key.

**Comment by troedfach** [comment]
This was previously raised in https://github.com/input-output-hk/cardano-ledger/issues/764 - refiling as the repositories have merged.

**Comment by JaredCorduan** [comment]
no more Byron blocks will ever be made, we can safely ignore this now. Development of Byron code has been frozen and only potential security fixes will be applied in the future
