### ISSUE TITLE
shelley-spec-ledger: MonadFail issue in 8.8.x and beyond (fix suggestion)

### ISSUE THREAD

**Issue by Heinrich-CH** [IntersectMBO/cardano-ledger#1515]
Hello,

When trying to build the code on ghc 8.8.3 and 8.10.1, I get the following error:

```
Configuring shelley-spec-ledger-0.1.0.0...
Preprocessing library for shelley-spec-ledger-0.1.0.0..
Building library for shelley-spec-ledger-0.1.0.0..
[ 5 of 50] Compiling Shelley.Spec.Ledger.BaseTypes ( src/Shelley/Spec/Ledger/BaseTypes.hs, dist/build/Shelley/Spec/Ledger/BaseTypes.dyn_o )

src/Shelley/Spec/Ledger/BaseTypes.hs:214:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
214 |   fail _ = SNothing
    |   ^^^^
==> ERROR: A failure occurred in build().
    Aborting...
```

I read the [MonadFail Proposal](https://wiki.haskell.org/MonadFail_Proposal), but not sure what's the best approach to address this. When I delete the offending line ` fail _ = SNothing`, `shelley-spec-ledger` builds successfully on 8.8.3.

**Comment by mrBliss** [comment]
Note that we only support GHC 8.6.5 at the moment.

**Comment by nc6** [comment]
Should be addressed now!
