### ISSUE TITLE
Validate `ShelleyGenesis`

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1516]
One of the pioneers saw an interesting issue in that they had a ShelleyGenesis whose security param was > half the epoch length. So they never hit the point in the epoch at which rewards were being created.

We should have some basic validation of the genesis to catch obvious nonsensical genesis values like this.

**Comment by mrBliss** [comment]
Another check that can be included: check that the chosen maximum KES evolutions is supported by the KES algorithm, i.e., `sgMaxKESEvolutions` <= `totalPeriodsKES (Proxy @(KES c))`.

**Comment by dcoutts** [comment]
And epoch length >= 10 * k / f.
