### ISSUE TITLE
Change epoch structure to 4-2-4

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1525]
Currently we have stabilityWindow and randomnessStabilisationWindow set to 3, giving us a 3-4-3 epoch structure. It was suggested by Peter Gazi that 4-2-4 would be a better parametrisation.

**Comment by JaredCorduan** [comment]
I am going to close this issue since it has grown stale and there is still no certainty on whether or now this will change (and we can always re-open if it ever becomes relevant again).
