### ISSUE TITLE
Move definition of ShelleyGenesis to ledger-specs

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-ledger#1530]
The `ShelleyGenesis` struct was originally defined in the `consensus` package but it makes more sense to define it in this one. We need:

* `ShelleyGenesis` moved here.
* Tests for `ShelleyGenesis` copied here from the `node` repository.
* A function `ShelleyGenesis c -> UTxO c` to generated the initial UTxO set from the genesis distribution specified in the Shelley genesis file.

These are all **must haves** for work further up the stack.

My understanding is that this is in progress. Raising as an issue here mainly for visibility.

**Comment by kderme** [comment]
The first 2 parts are merged and the third is here https://github.com/input-output-hk/cardano-ledger-specs/pull/1536
