### ISSUE TITLE
add txid and headerHash in cddl schema

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#1537]
When communicating using node-client mini protocols, it is useful to have txid and headerhash

If not, I would like to know how I can compute hash for txid and header, a spec details will be very helpful so I can write them in javascript

**Comment by ashisherc** [comment]
@JaredCorduan can you please help me with this one?

**Comment by JaredCorduan** [comment]
hello @ashisherc , the transaction ID (ie transaction body hash) is the BLAKE2b-256 hash of the [CBOR serialized transaction body](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl#L51). Similarly, the header hash (which is used in the block header to point to the previous block) is the BLAKE2b-256 hash of the [CBOR serialized block header body](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl#L28).

**Comment by ashisherc** [comment]
I tried to cbor encode the block header body and then apply the blake2b-257, but the hash I am receiving is not the same.

Is there anything extra in the header body before I should cbor encode it, while going through the ledger source code here, https://github.com/input-output-hk/cardano-ledger-specs/blob/f6867a170049e3dfcc65cf865a7775ea8aea6edd/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs#L242

I am not sure if there is anything extra I need to add to the ledger before serializing https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl#L28 with cbor

**Comment by ashisherc** [comment]
This is what I am encoding to cbor,

```
[0, 0, null, h'BB93EEDF4AE001993672B868D81F2BAE678A23CF786D61F33D64E8540A1CF8D2', h'0000DF457056FAC44FB16596532E02D700017EC4524A2C93450876920D2658E9', [44792797903275057896331118126287229661, h'00009E5F5301DAFE7C7AC76061AF04F10001AE56059F60A85AD68CD136A9510CBB71C818AFD81BD48132A2F15BAF8CFA0000B52E521AADF07D595168D5C4B96F'], [203513572971754583926679883562105556346, h'0000C17EFB992F8E9CA52B2E2DB42825000078CD951DE20EDE9088E2443A9C1618A0251070D0813FBD9632950888351E00005FA9002B208FB36067156B2A1899'], 3, h'1033376BE025CB705FD8DD02EDA11CC73975A062B5D14FFD74D6FF69E69A2FF7', h'AF29773AC5410157EAF51F11FECFF7C89FEB980CBA72517A08F3342314498FEE', 0, 0, h'F0529B4F86DF241E04AEBD0F68FD0B20B114D94F97A4A61CE2E3970382664FBEB345A0774CCE99F39D6940D7035615C616833FD5CB733918B6F3AC2C2D40FB0E', 0, 0]
```
the cbor is this,

```
8f0000f65820bb93eedf4ae001993672b868d81f2bae678a23cf786d61f33d64e8540a1cf8d258200000df457056fac44fb16596532e02d700017ec4524a2c93450876920d2658e982c25021b2c7719f2b093be9d3ae1a72ab12dd584000009e5f5301dafe7c7ac76061af04f10001ae56059f60a85ad68cd136a9510cbb71c818afd81bd48132a2f15baf8cfa0000b52e521aadf07d595168d5c4b96f82c250991b49d6635f40e6232f2cfe0405cd7a58400000c17efb992f8e9ca52b2e2db42825000078cd951de20ede9088e2443a9c1618a0251070d0813fbd9632950888351e00005fa9002b208fb36067156b2a18990358201033376be025cb705fd8dd02eda11cc73975a062b5d14ffd74d6ff69e69a2ff75820af29773ac5410157eaf51f11fecff7c89feb980cba72517a08f3342314498fee00005840f0529b4f86df241e04aebd0f68fd0b20b114d94f97a4a61ce2e3970382664fbeb345a0774cce99f39d6940d7035615c616833fd5cb733918b6f3ac2c2d40fb0e0000
```

**Comment by ashisherc** [comment]
One slight change, had to put the whole header for serialising,

https://github.com/input-output-hk/cardano-ledger-specs/blob/f6867a170049e3dfcc65cf865a7775ea8aea6edd/shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl#L23

This works. Thank you very much.

**Comment by ashisherc** [comment]
@JaredCorduan The cbor of blockheader from the cddl is producing the correct headerhash, but I am unable to produce the correct trx hash from cddl transaction hash.

I am encoding the exact same object you have linked above. Also tried encoding the transaction spec from the cddl spec file but no luck.

**Comment by ashisherc** [comment]
@JaredCorduan Here's more details on the trx id computation problem I am facing,

I went through FF testnet blocks manually looking for a valid set of UTXOs to implement this. I found block 415 and 432 has transactions that have a valid chain of UTXO. eg. block 432 uses a utxo generated in block 415. Thus I know what the trx id should be of the trx in block 415. below is the trx body cbor from the block 415 and 432 for your quick reference.

cbor of trx body from 415
```
a5008182582075c62cb4a2bbc63ccff6b518de7f18beef9eb1898829822f421bece94f44bb61000181825821605b9f3715742489a4c5a138e4a47984a41a6623aab620037ee67baed820521ba5c2472386f2162b9371021a0002df850319271004848200820058204a215bb53749de82d1b0366df901782328a4aef522d297fc27ccdbb65c96de698a035820f96172bc57f829a2e4b1ef8771ce846369370fd4aedb7850ca0480a85b598fbb5820bc35afa0e36aa11d16261912ee8e5cefe1ecd0a3a875f2681ba78617e245f2011b000000ae9f7bcc001a00989680d81e821b000ccccccccccccd1b00100000000000005821e04be527703e72f2f637486a83e33bd1c706c1de78b6b7a5401fb6c9bdd23b64088158204a215bb53749de82d1b0366df901782328a4aef522d297fc27ccdbb65c96de6980f68302820058204a215bb53749de82d1b0366df901782328a4aef522d297fc27ccdbb65c96de695820f96172bc57f829a2e4b1ef8771ce846369370fd4aedb7850ca0480a85b598fbb8200820058204be527703e72f2f637486a83e33bd1c706c1de78b6b7a5401fb6c9bdd23b6408
```

cbor of trx body from 432
```
a40081825820fb8ef4188f7d11dac347ad5b0e247f27c5fda44162997503bea56fffe5f9ace1000184825821605b9f3715742489a4c5a138e4a47984a41a6623aab620037ee67baed820521ba5c2472384379839bd54825841001afb8b875f50857359309cb4a78e852c83baed487ab237b540ed52b4d30c1641d74699fc1b7d0f2a1bf98716f637dbf36da6e250fb0d3e51c70f19cc7c0ea2351b000000e8d4a510008258410001aa73954a34dc3444f9fe4dae38b591d0df1a83292062ce8b6f70a7bc3eadbe663f2e8ff050e71a2190218c5699f3103a026564342f4e8e62fbc3efb23359eb1b000000e8d4a510008258410031a8cb662c7ae9121626281dc92b1473fa047351f3724681b9304c28c0a2f0554a215bb53749de82d1b0366df901782328a4aef522d297fc27ccdbb65c96de691b000000e8d4a51000021a0002a61d03192710
```

As per transactions above, the hash of cbor of trx body of block 415 should be the trx id used in the trx in block 432.

I hashed the cbor of trx body of block 415 the exact same mentioned above and I receive
```
b1d8366a57c2c976755930a9bca7faaa565b49e643b20292007430e3d6d0000b
```

This doesn't match the input trx id used in trx body from block 432.

I have been going through the source code at https://github.com/input-output-hk/cardano-ledger-specs/blob/cb9e3420cb48adb4306f976240edf464c684f22c/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/TxData.hs#L355

Not sure if I have to add anything extra to the cddl object before cbor encoding it. I also tried creating a cbor from the transaction spec as per https://github.com/input-output-hk/cardano-ledger-specs/blob/cb9e3420cb48adb4306f976240edf464c684f22c/shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl#L15

But that as well doesn't work.

**Comment by JaredCorduan** [comment]
I'm glad that the header hash is working for you now! I'll reopen the issue in case there is something going on with that transaction id.

**Comment by ashisherc** [comment]
closing this issue over an encoding issue in javascript. Thanks for your help @JaredCorduan

**Comment by JaredCorduan** [comment]
@ashisherc did you get the transaction ID to work?

**Comment by ashisherc** [comment]
Yes, it worked as you mentioned earlier, not able to make it work properly as some data type issue with js.
