### ISSUE TITLE
Allow specifying a coin value in `getNonMyopicMemberRewards`

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1542]
Rather than a stake cert, allow specifying a putative stake.

See conversation at https://input-output-rnd.slack.com/archives/CCZSDE005/p1591872486454400

**Comment by kevinhammond** [comment]
From Matthias:

Hey guys, this is now a rather big blocker for us.
Can we make sure that this get prioritized correctly please :pray:  ?

**Comment by nc6** [comment]
Gotcha
