### ISSUE TITLE
Please remove Byron Cardano.Chain.Slotting tree

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-ledger#1548]
My understandings is that this should have been replaced by the `Cardano.Slotting` modules in `cardano-base`. Having the old and the new is just confusing.

Probably good to deprecate them first, wait a month or so and them remove them.

:sob: `headerSlot` in `Cardano.Chain.Block.Header` returns `SlotNumber` :cry: 

To make matters still worse, `SlotNo` is re-exported from `ouroboros-network`.

**Comment by mrBliss** [comment]
> To make matters still worse, `SlotNo` is re-exported from `ouroboros-network`.

That's because `ouroboros-network` introduced `SlotNo`, but it was moved to `cardano-base`. We haven't gotten around to removing it from `ouroboros-network` yet because we had other things to do :slightly_smiling_face:

**Comment by nc6** [comment]
I don't think the byron code uses `Cardano.Slotting`, but I could be wrong. I'll check

**Comment by nc6** [comment]
Confirmed that we don't use the Cardano.Slotting types in Byron, and currently have no plan to switch this over.
