### ISSUE TITLE
pool keyhash is 28 bytes in the cardano-node 1.14.1, what could be the best way to keep track of these changes?

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#1588]
https://github.com/input-output-hk/cardano-ledger-specs/blob/c23baa30db5b26e27c1443494631e22f78e216b7/shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl#L225

**Comment by nc6** [comment]
Yes, good point, those are incorrect. I will fix today

**Comment by ashisherc** [comment]
One more item probably, **activeSlotsCoeff**

This one can be updated using update proposal but is not mentioned in the cddl spec, let me know if I am interpreting it wrong.

**Comment by JaredCorduan** [comment]
thank you @ashisherc for letting us know!

the `activeSlotsCoeff` is actually a global constant, and cannot be updated using the update proposals. In the formal spec, the globals are in figure 8 and the updateable parameters are in figure 7.
