### ISSUE TITLE
Typos/mistakes in Shelley Ledger Formal Specification, Chapter 12.9

### ISSUE THREAD

**Issue by jmhrpr** [IntersectMBO/cardano-ledger#1617]
In the [Shelley Ledger Formal Spec](https://hydra.iohk.io/build/3301467/download/1/ledger-spec.pdf), Page 76, 12.9 Operational Certificate Transition, the first bullet point describing the preconditions of the operational certificate state transition seems to be incorrect as it reads:

> The KES period start c_0 must be greater than or equal to the KES period of the slot of the block header body and less than MaxKESEvo-many KES periods after c_0

That is, `kesPeriod s <= c0 < c0 + MaxKESEvo`, but in Figure 67 which shows the transition rule it states `c0 <= kesPeriod s < c0 + MaxKESEvo`, which appears to be correct and matches the implementation in the executable spec. Also, the SL-D1 document that is referenced here has an outdated link.

In the third and fourth bullet points it seems that sigma and tau should be swapped, as in Figure 67 and the implementation in the executable spec sigma is used for the KES signature and tau for the cold key signature, the inverse of how they are defined in the formal spec.

Finally, it may be worth noting that in the list of the six predicate failures the name `KESPeriodWrong` is used for the case in which the original key hash counter mapping is larger than the period number in the certificate, but in the executable spec it is called `CounterTooSmall`.

**Comment by JaredCorduan** [comment]
thank you @jmhrpr!, I agree on all the points above.
