### ISSUE TITLE
[BUG] - delegators and owners/operators of a stake pool that does not honour pledge should not be receiving rewards

### ISSUE THREAD

**Issue by bergr01** [IntersectMBO/cardano-ledger#1627]
I'm running cardano-node version 1.14.2 at the moment on Shelley Testnet network.

A pool with over 8 trillion tADA in pledge is currently returning some non-zero reward amounts to its delegators. 
The relevant part of the spec was corrected recently, see https://github.com/input-output-hk/cardano-ledger-specs/pull/1611

Similarly, the non-myopic reward estimate for such a pool should also take this into consideration and probably yield 0.

**Comment by erikd** [comment]
See: https://github.com/input-output-hk/cardano-ledger-specs/pull/1611/commits/a441031923161517186dd0f8ee1239b4e3f3e0cb

>  pools where the owners do not meet the pledge in a given epoch will earn no rewards for that epoch. Note that this affects \emph{all} pool rewards, both for the operator and for pool members.

**Comment by JaredCorduan** [comment]
@bergr01 do you know how many epochs this pool had an 8 trillion ADA pledge and continued to receive rewards? there is a delay on pool re-registration certificates, and there is some timing involved in when snapshot are taken, when that snapshot is used for leader election, and when the rewards are handed out.

**Comment by JaredCorduan** [comment]
@bergr01 can you tell me what the key hash of the stake pool is, and what epoch you saw this? the logs from `cardano-cli shelley query ledger-state` would probably also be helpful.

**Comment by bergr01** [comment]
The pool had 8 trillion pledge for over a day now (4 epochs). After the pledge came into effect I created a couple of new wallets using cntools library and delegated them to it - here is what the reward balances are at the moment:

Adver2
Funds			37,765,543.088449 ADA
Rewards			23,312.940018 ADA
Delegated to Max2 (feea59bc6664572e631e9adfee77142cb51264156debf2e52970cc01)

AdverTest
Funds			10,111,220.751859 ADA
Rewards			5,876.716677 ADA
Delegated to Max2 (feea59bc6664572e631e9adfee77142cb51264156debf2e52970cc01)

The above values are derived using cardano-cli, e.g.

cardano-cli shelley query stake-address-info --testnet-magic 42 --address 581de0ed0d002c1057f05c3576dc000b712720a74aae1dd3c244d55916a18b
{
    "581de0ed0d002c1057f05c3576dc000b712720a74aae1dd3c244d55916a18b": {
        "delegation": "feea59bc6664572e631e9adfee77142cb51264156debf2e52970cc01",
        "rewardAccountBalance": 23312940018
    }
}

**Comment by bergr01** [comment]
After a bit more testing using 1.15.0 cardano-node version, it looks like pools are behaving correctly - perhaps I was just confused by just how long it took from the moment I made a pool certificate modification / pledge change to when rewards stopped being paid out (e.g. if i change pledge from 0 to 8 trillion, a second later delegate to that pool, i seem to get a couple of epochs of rewards). My earlier comment about the need for non-myopic reward estimation and either too high (some ridiculous number) or non-honored pledge scenarios still stand, however.

**Comment by JaredCorduan** [comment]
thanks again @bergr01 for running these tests! We are addressing the pledge issue in #1634
