### ISSUE TITLE
`MetaDatum` type in the ledger implementation matching the Plutus `Data` type

### ISSUE THREAD

**Issue by polinavino** [IntersectMBO/cardano-ledger#1628]
The Plutus interpreter expects several arguments of type `Data`. I believe we agreed that this type should be defined in the ledger code, and should be the same as the type of ledger metadata (`MetaDatum`). 

Right now, these two types have different constructors and different names (`Data` and `MetaDatum`). They should have the same name and same constructors.

```
data MetaDatum
  = Map [(MetaDatum, MetaDatum)]
  | List [MetaDatum]
  | I Integer
  | B B.ByteString
  | S T.Text
```

```
data Data =
      Constr Integer [Data]
    | Map [(Data, Data)]
    | List [Data]
    | I Integer
    | B BSL.ByteString
```

**Comment by michaelpj** [comment]
We definitely need `Constr`. I don't know why we didn't add that before. To do this really nicely we'd need the CBOR extension for alternatives which we proposed a while ago. I don't know what happened to that (@dcoutts was pushing it).

The `S` constructor is worrying. We can't necessarily support that in Plutus. We could add `Text` as a builtin type but I'm not sure we want to. So we'd have to hack around it. Apparently I reviewed the PR where this was introduced and didn't say anything, which is unfortunate.

**Comment by dcoutts** [comment]
We do not need the types to be the same provided we have a suitable conversion.

Fortunately the conversion from `MetaDatum` to `Data` is easy. We don't use the `Constr` in the targer type. The text is just converted to bytes in utf8. That's it.

**Comment by michaelpj** [comment]
I thought it was nice and parsimonious for them to be exactly the same...

**Comment by polinavino** [comment]
If they can be different, there is really no reason to even translate them?

**Comment by michaelpj** [comment]
Well, at least we probably want the metadata to go into the validation context so scripts can see it. I had hoped this would be beautifully simply since it would already be the same type, but we can translate it if we have to.

**Comment by polinavino** [comment]
Oh hm.. I didnt think MD would be passed. But it makes sense to pass it I guess?

**Comment by michaelpj** [comment]
I think we definitely want to pass it!

**Comment by polinavino** [comment]
Ok, we will translate the MetaDatum to Data

**Comment by polinavino** [comment]
Different types, passing MD to scripts is part of the larger question of translating Tx data into a Data type
