### ISSUE TITLE
`txSize` for Shelley transactions during Goguen

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/cardano-ledger#1632]
If we want to support Shelley transactions during Goguen without any software update for the wallets, we need to make sure that `txSizeG (toGoguenTx tx) = txSizeS tx` (or at least `<=`) for the Goguen and Shelley `txSize` functions, or we run into the issue of transactions being created that are rejected even though the wallet doesn't see any problems.

The `Value` type by itself has some overhead, so the most trivial implementation will certainly not satisfy this equation. We could try getting around this with some special casing, but I don't think we can get rid of all overhead.

**Comment by polinavino** [comment]
txSize for Shelley Txs is always the number of bytes of the original Tx, before toGoguen translation is applied
