### ISSUE TITLE
"We are elected as leader proportional to our stake" property test failure

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#1638]
The property test "We are elected as leader proportional to our stake" fails on

```
stack test shelley-spec-ledger --ta --scenario=Fast --ta  "--quickcheck-replay=857578"
```

```
        *** Failed! Falsifiable (after 97 tests and 15 shrinks):
        ASC (ActiveSlotCoeff {unActiveSlotVal = UnsafeUnitInterval (7797641395041937 % 144115188075855872), unActiveSlotLog = -556258308534652196332665362628480})
        StakeProportion (5282813 % 46661632)
        -4 /< 11 /< 11 (p=6.277908974846036e-3)
        Use --quickcheck-replay=857578 to reproduce.
```

The test is a statistical test that is supposed to have a low chance of failing. We could have just gotten unlucky, but it is probably worth investigating.

**Comment by JaredCorduan** [comment]
Another PR was recently hit with this:  `--quickcheck-replay=729593`.

**Comment by nc6** [comment]
So the probability of failing (in this case) is about 0.0004. We run this test 100 times each time. So we expect to see it once every 25 PRs or so...

**Comment by JaredCorduan** [comment]
this has not failed in a long time!
