### ISSUE TITLE
What witness is required for pool registration certificates?

### ISSUE THREAD

**Issue by SebastienGllmt** [IntersectMBO/cardano-ledger#1641]
Pool registration certificates contain the following information

```rust
struct PoolParams {
    operator: PoolKeyHash,
    vrf_keyhash: VRFKeyHash,
    pledge: Coin,
    cost: Coin,
    margin: UnitInterval,
    reward_account: RewardAddress,
    pool_owners: AddrKeyHashes,
    relays: Relays,
    pool_metadata: Option<PoolMetadata>,
}
```

I want to know which witnesses are required for a transaction that contains a pool registration certificate. However, the spec has two contradictory statements on this:

1) The `witsVKeyNeeded` says that we need the VKey of the `pool_owners` keys

![image](https://user-images.githubusercontent.com/2608559/87096265-689c5d80-c27d-11ea-9341-9a9850832b39.png)

2) `cwitness` says the transaction contains only the witness of the `operator` (same thing is mentioned for pool retirement)

![image](https://user-images.githubusercontent.com/2608559/87096333-89fd4980-c27d-11ea-9c4f-f9d07712ce84.png)

I assume (1) is correct and (2) is wrong?

**Comment by dcoutts** [comment]
It's perhaps a little confusing but it is not contradictory.

Note that `witsVKeyNeeded` takes both:
1. the `certWitsNeeded` which for pool registrations is the pool operator; and
2. the union of the key hashes from all the `poolOwners` in all the pool registration certs

So it's handled in two parts, the `cwitness` returns the "primary" witness keyhash, and then for the special case of pool registrations we also take all the pool owners (and for update proposals there's another special rule using `propWits`).

So the overall answer both from the design spec, and here from the formal spec is that you need witnesses from the pool operator and all the pool owners.
