### ISSUE TITLE
Shelley Ledger Spec - Pool Reap Transition Incompleteness and Typo

### ISSUE THREAD

**Issue by xenocidewiki** [IntersectMBO/cardano-ledger#1654]
The issue is on Page 51 of the Shelley Ledger Spec, in Fig. 41.

On page 50, it says that for the pool reap transition "Each retiring pool is removed from all four maps in the pool state."
This is indeed the case in the relevant code, however it is incompletely reflected by the spec.
In Fig. 41 only 3 of the 4 maps  (stpools, poolParams, and retiring) are specified to have the retiring pool removed. The spec is missing the rule for the retiring pool being removed from the **future pool params** in the pool state.

A second issue is what I believe to be a typo.

Again in Fig. 41 the _pr_ variable is specified as a set which involves _kh_. I think this is referring to the key hash, in which case it should be _hk_ as defined on page 5 of the spec, and seen throughout. This problem is also reflected in the code here: https://github.com/input-output-hk/cardano-ledger-specs/blob/011c223b0dbf45f5053fc810cf2b7f0da6f2490c/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs#L73 where _kh_ is used instead of _hk_.

**Comment by JaredCorduan** [comment]
yes indeed, thank you @xenocidewiki !
