### ISSUE TITLE
Shelley Ledger Spec - Pool Registration Inconsistency in Formal Spec

### ISSUE THREAD

**Issue by nankeen** [IntersectMBO/cardano-ledger#1656]
Regarding Equation 12 & 13 on Figure 25 page 38 of the formal specification, there is a precondition specifying a requirement for the pool cost to be lesser than or equal to the minimum pool cost.

![image](https://user-images.githubusercontent.com/6895854/87357037-1dbf6600-c55b-11ea-927d-9183c5985b2e.png)

However the executable spec implements a different assertion.

https://github.com/input-output-hk/cardano-ledger-specs/blob/45b76296976046de09a686d3987ca55368f792b2/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Pool.hs#L152

The *POOL* rules also contradicts this.

> In the case of a pool registration or re-registration certificate, if specified pool cost parameter is smaller than the value of the protocol parameter _minPoolCost_, there is a _StakePoolCostTooLow_ failure.

I think the implementation in the executable spec is correct, and this is just a typo in the formal specification.

**Comment by dcoutts** [comment]
I agree. The impl is correct and the spec should be adjusted.
