### ISSUE TITLE
Test re-organisation

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1673]
# Test re-org

- Make it obvious how to contribute additional testing
- What should we do with the ConcreteCryptoTypes module? It's not parametrised everywhere anyway! Let's just drop it entirely.
- Benchmarks should be pulled out of the tests directory entirely, and placed inside `bench`.
- We want to be able to produce much longer traces
- Improve the transaction/block generators

Shelley/Spec/Ledger/Test

- Serialization
    - Generators
    These generators only generate type-correct data for use in the round-tripping tests / CDDL tests.
    - Golden
        - Binary
        Should have a means to "overwrite" the test output with a given flag.
        - Encoding (e.g. golden tests at the encoding level?)
        Should we get rid of these entirely?
    - Tripping
    - CDDL
    - Q: Do we want to split this by type?
- Property
    - Unit
        - Sometimes these need their own generators. They should be test specific and not exported.
    - Trace
        - Incorporate anything from the 'NonTrace' tests so that the 'NonTrace' tests can die
- Examples
Split the examples up into self-contained modules, each of which should have a coherent description of what they're testing.

    We could consider using literate haskell here.

    - Ex1
    - Ex2
    - Ex3
    - Framework
    We should build something to allow us to write the examples in a more compact, explicit way - e.g. remove most of the manual threading of state.

**Comment by JaredCorduan** [comment]
We should review this ticket and see how much of it is still relevant.

**Comment by JaredCorduan** [comment]
The details in this issues are out of date, but we definitely still need to re-organized our tests.

**Comment by JaredCorduan** [comment]
closing in favor of  #2743
