### ISSUE TITLE
Remove use of `cardano-prelude`

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1676]
Depends on https://github.com/input-output-hk/cardano-prelude/issues/115

**Comment by JaredCorduan** [comment]
waiting on https://github.com/input-output-hk/cardano-base/pull/278 before we can finish it up.

**Comment by locallycompact** [comment]
Is there a WIP branch for this?

**Comment by teodanciu** [comment]
There was an outdated one, which I just refreshed and opened a draft PR for it: https://github.com/input-output-hk/cardano-ledger/pull/2887

**Comment by JaredCorduan** [comment]
:tada: :wave: :tada:
