### ISSUE TITLE
Re-enable mac tests

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#1704]
Our OSX tests were timing out, so we disabled them temporarily. https://github.com/input-output-hk/cardano-ledger-specs/pull/1703/commits/b9b2e5cd8a4e1e800ad4e5471fb06533260d0cee

We need to re-enable them!

**Comment by lehins** [comment]
MacOS tests have been working on hydra for a long time. 
Closing
