### ISSUE TITLE
Incorrect forward reference regarding enterprise addresses

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/cardano-ledger#1716]
https://github.com/input-output-hk/cardano-ledger-specs/blob/be224350a89d24adecdd7d1ff9a94807e2222c64/shelley/chain-and-ledger/formal-spec/address.tex#L34-L36

I didn't find a discussion of either of those in `sec:delegation-shelley` in the PDF.

- I anticipate that referring to 3.2.2 On Enterprise Addresses of SL-D1 would work for motivating the stakelessness of enterprise addresses.
- I haven't seen any discussion of the indicated circumvention mechanism. (For context, that's actually what I was interested in for possible use in the ThreadNet tests.)

**Comment by JaredCorduan** [comment]
> I anticipate that referring to 3.2.2 On Enterprise Addresses of SL-D1 would work for motivating the stakelessness of enterprise addresses.

Yes, that is the correct reference.

> I haven't seen any discussion of the indicated circumvention mechanism.

There isn't one, I think this sentence must be trying to communicate that no one can force anyone to use enterprise addresses. we should just remove it.

thanks!
