### ISSUE TITLE
Decouple HASH and ADDRHASH in test generators

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1721]
This is proving problematic for consensus, which re-uses these downstream for testing the hard fork.

**Comment by edsko** [comment]
In particular, _Byron_ uses different length hashes for these two.

**Comment by nc6** [comment]
Thomas Winant  5:26 PM
I think I found the problem: https://github.com/input-output-hk/cardano-ledger-specs/blob/c0bb1ae640093d612de69fe916f9ddac9fd8cfdd/shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/ConcreteCryptoTypes.hs#L49-L50
shelley/chain-and-ledger/executable-spec/test/Test/Shelley/Spec/Ledger/ConcreteCryptoTypes.hs:49-50
  type HASH (ConcreteCrypto h) = h
  type ADDRHASH (ConcreteCrypto h) = h
<https://github.com/input-output-hk/cardano-ledger-specs|input-output-hk/cardano-ledger-specs>input-output-hk/cardano-ledger-specs | Added by GitHub





5:26
We use the same hash algorithm for HASH and ADDRHASH, i.e. Blake2b_256
5:26
But Byron address hashes are Blake2b_224
