### ISSUE TITLE
MIR and NEWEPOCH Specification Discrepancies

### ISSUE THREAD

**Issue by xenocidewiki** [IntersectMBO/cardano-ledger#1728]
A few issues I found when reviewing the MIR and NEWEPOCH rules:

- MIR:
    - There is a small typo on page 68 in section 12.3 (2nd paragraph) of the formal spec, where "mappiing" has one "i" too many.
    - Variable names in Fig. 56 on page 69 (the ones mentioned first refer to the formal spec):
        - Instead of updateR and updateT the code uses irwdR and irwdT
        - Instead of totR and totT the code uses totFromReserves and totFromTreasury
        - Instead of ds the code uses dState
        - Instead of acnt' etc. the code uses acnt
            - I don't think this should be a major problem as such but if we want to be pedantic about this then matching the spec and using ' would probably be desirable.
    - In Fig. 55 on page 68 we have a mirUpdates helper function, this function does not exist in the code, the functionality it performs is there but it is not done through the helper function.

- NEWEPOCH:
    - On page 69 below the figure you refer to overlaySchedule being described in 3.9.2 of SL-D1. No such section exists in that specification. I believe this might instead be referring to 3.8.2 in SL-D1.
    - In Fig. 58 on page 72 "poolPrms" is used instead of "poolParams", seems like a small typo.
    - There is a calculatePoolDistr helper function in the code that is being used, however this helper function is not anywhere in the formal specification. It performs the functionality required to get pd'.

**Comment by jmhrpr** [comment]
In MIR there is another typo just after the `mappiing` typo: `accouts` instead of `accounts`.

**Comment by JaredCorduan** [comment]
regarding `acnt'` in the spec vs the code: it's not that the code uses `acnt`, but rather that it uses the record update syntax with `acnt`, ie it is being inlined in the code. My preference is to just inline this in the spec as well, to make sure that `acnt'` is never used in `MIR-Skip`. and for this reason, I'm going to go with the more cryptic name `totR` over `totFromReserves` just so my latex tables don't explode.
