### ISSUE TITLE
Block Validation Performance

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#1750]
Initial bench-marking has shown that shelley block validation could be as much as 150 times slower that byron block validation.  We need to investigate where the slowdown is coming from and propose solutions.

**Comment by nc6** [comment]
Closing this issue for now; we have made many improvements to validation performance:
https://github.com/input-output-hk/cardano-ledger-specs/pull/1790
https://github.com/input-output-hk/cardano-ledger-specs/pull/1789
https://github.com/input-output-hk/cardano-ledger-specs/pull/1786
https://github.com/input-output-hk/cardano-ledger-specs/pull/1785

We may make future improvements, but if so we will open another ticket.
