### ISSUE TITLE
Misc typos in the Shelley formal specification

### ISSUE THREAD

**Issue by Vtec234** [IntersectMBO/cardano-ledger#1751]
- In Fig. 10, the codomain of `ProposedPPUpdates` should probably be `PParamsUpdate` as `PPUpdate` is never defined.
- In Fig. 21, the type `PoolMD` is defined both as an abstract and a derived type.
- In Fig. 23, the name `futureOtherVrfKeyHashe` is a typo. Moreover the set comprehensions for `futureOtherColdKeyHashes` and `futureOtherVrfKeyHashes` should probably bind the key as `(_, g)` rather than `(g, _)` since the domain of `FutGenesisDelegation` is `(Slot x KeyHash_G)`.

**Comment by csoroz** [comment]
Fig. 21, `PoolParams` and `PoolMetaData` in code:

https://github.com/input-output-hk/cardano-ledger-specs/blob/59098c0038b30cac7f5c3c4443e6c3db98717b1c/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/TxData.hs#L320-L330

https://github.com/input-output-hk/cardano-ledger-specs/blob/59098c0038b30cac7f5c3c4443e6c3db98717b1c/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/TxData.hs#L202-L205

**Comment by csoroz** [comment]
Fig. 10, in the code `ProposedPPUpdates` has `PParamsUpdate` as codomain, as the OP says:

https://github.com/input-output-hk/cardano-ledger-specs/blob/59098c0038b30cac7f5c3c4443e6c3db98717b1c/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/PParams.hs#L438-L439

**Comment by csoroz** [comment]
Fig. 23, the corresponding code:

https://github.com/input-output-hk/cardano-ledger-specs/blob/59098c0038b30cac7f5c3c4443e6c3db98717b1c/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs#L249-L263
