### ISSUE TITLE
RUPD and TICK Specification Discrepancies

### ISSUE THREAD

**Issue by xenocidewiki** [IntersectMBO/cardano-ledger#1753]
This concerns the Reward Update and Chain Tick Transition rules.

Page 75 Formal Spec:
- In the formal spec the createRUpd function takes 3 parameters, while in the code there are 4 parameters. The first parameter should be the epoch. Relevant code is here: https://github.com/input-output-hk/cardano-ledger-specs/blob/25f504bd95104607be722979eb911f8330d1a921/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Rupd.hs#L75
    - This is also reflected anywhere else createRUpd is mentioned such as on page 63 of the formal spec.

Page 76 Formal Spec:
- I believe the "s" in Fig. 65 should be called "slot" to be consistent, this is what is is called in the code. 
- The ru' and es' variables in the code should be ru'' and es'' to be matching the formal specification in Fig. 65. Relevant code: https://github.com/input-output-hk/cardano-ledger-specs/blob/25f504bd95104607be722979eb911f8330d1a921/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Tick.hs#L113-L115

**Comment by JaredCorduan** [comment]
I think that the right thing to do here is to make both the code and the spec pass `slotsPerEpoch` to `createRUpd`. The complication comes from the fact that `slotsPerEpoch` is a constant in shelley, but the hard fork combinator can change it, so `createRUpd` was using the epoch number to get `slotsPerEpoch`.
