### ISSUE TITLE
OCERT and OVERLAY discrepancies

### ISSUE THREAD

**Issue by xenocidewiki** [IntersectMBO/cardano-ledger#1776]
OCERT:

- vkey should be vk_cold as in the formal specification: https://github.com/input-output-hk/cardano-ledger-specs/blob/46a623afdb69741590ca5e809ab3fc41554939e1/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Ocert.hs#L83

- The formal spec names certain functions "bslot", "bvcold", "bocert", etc. whilst in the code they are bheaderSlotNo, bheaderVK, bheaderOcert -> maybe it is a good idea to change one or the other in order to keep it consistent throughout.

OVERLAY:
- On page 80 in the formal spec, it is stated that there are nine predicate failures, while in reality there are ten. OcertFailure seems to not be documented in the formal spec, but exists in the code: https://github.com/input-output-hk/cardano-ledger-specs/blob/46a623afdb69741590ca5e809ab3fc41554939e1/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs#L137

- ~~Perhaps renaming eta0 to n0 would be better, as the formal spec uses n0. This is seen throughout Overlay.hs in multiple locations and different helper functions. I.e. in the formal spec praosVrfChecks uses n0 as a parameter, not eta0.~~ "eta" is used as the formal spec uses the greek letter eta, in which case this difference makes sense.

- Same question with bheaderSlotNo, bheaderVrfVk etc. functions. The formal spec seems to have shortened names (bslot etc.), perhaps to keep this consistent one or the other should be changed.

**Comment by xenocidewiki** [comment]
I finished reviewing OVERLAY and found a couple more issues @JaredCorduan, it concerns mainly page 79 of the formal spec which are the vrf helper functions used by overlay:

- **vrfChecks**
    - seedEta -> it's seedN in the formal spec: https://github.com/input-output-hk/cardano-ledger-specs/blob/d46160eb1f5b1d9fee46ee1a1efdb04dd11a67e4/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs#L48
    - slot -> is ss in the formal spec: https://github.com/input-output-hk/cardano-ledger-specs/blob/d46160eb1f5b1d9fee46ee1a1efdb04dd11a67e4/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs#L166
        - Same as above, mkSeed does not seem to be mentioned as a helper function anywhere
    - vrfK is vrfVK in the formal spec: https://github.com/input-output-hk/cardano-ledger-specs/blob/d46160eb1f5b1d9fee46ee1a1efdb04dd11a67e4/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs#L179

- **praosVrfChecks**
    - This might be me being pedantic, but in the formal spec praosVrfChecks has its third parameter defined as [0,1], however in the executable spec this is ActiveSlotCoeff which is defined to be (0,1] -> I do not think this is a large issue, just a small inconsistency.
    - Again we have vrfK being used, perhaps change either the code or the formal spec to fit, just like with **vrfChecks** above. 
    - vrfHK should maybe be hk_vrf like in the formal spec: https://github.com/input-output-hk/cardano-ledger-specs/blob/d46160eb1f5b1d9fee46ee1a1efdb04dd11a67e4/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs#L222
    - PoolIdFromBHBody gets the vk_cold hash from bhb, but the helper function is not documented anywhere, perhaps remove it or add it to the spec? https://github.com/input-output-hk/cardano-ledger-specs/blob/d46160eb1f5b1d9fee46ee1a1efdb04dd11a67e4/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs#L207
    
- **pbftVrfChecks**
    -  In the formal spec this has some weird indentation so that it's indented further than the other functions, might want to fix that.
    - Same issue with vrfK and vrfHK as above, perhaps keep both consistent with the rest, i.e. make vrfHK -> hk_vrf instead. The formal spec uses vrfh instead for some reason, so that should probably be changed as well. https://github.com/input-output-hk/cardano-ledger-specs/blob/d46160eb1f5b1d9fee46ee1a1efdb04dd11a67e4/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Overlay.hs#L222

**Comment by JaredCorduan** [comment]
> On page 80 in the formal spec, it is stated that there are nine predicate failures, while in reality there are ten. OcertFailure seems to not be documented in the formal spec, but exists in the code:

I think we have been consistent so far with never counting the "sub-transition predicate failures" in these lists in the spec.

**Comment by JaredCorduan** [comment]
> The formal spec names certain functions "bslot", "bvcold", "bocert", etc. whilst in the code they are bheaderSlotNo, bheaderVK, bheaderOcert -> maybe it is a good idea to change one or the other in order to keep it consistent throughout.

That's a good point, thank you. I've split that out into a separate issue (#1860) since I would like to keep the code changes in this PR minimal right now.

**Comment by JaredCorduan** [comment]
> seedEta -> it's seedN in the formal spec

it's actually a greek eta in the spec (and spelled out "eta" in the impl.), but it sure does look a lot like an n!

why was epsilon afraid of zeta? because zeta "ate a" theta!

**Comment by JaredCorduan** [comment]
> This might be me being pedantic, but in the formal spec praosVrfChecks has its third parameter defined as [0,1], however in the executable spec this is ActiveSlotCoeff which is defined to be (0,1] -> I do not think this is a large issue, just a small inconsistency.

sometimes this is exactly the kind of innocuous-looking thing that bites you hard. I appreciate you mentioning things like this!

**Comment by JaredCorduan** [comment]
> In the formal spec this has some weird indentation so that it's indented further than the other functions, might want to fix that.

yea, this is a problem in a lot of spots. the align environment is being centered inside the figure. played around with it just, couldn't figure out something nice right away... I'm going to skip for now...
