### ISSUE TITLE
Staking credential registered in rewards map

### ISSUE THREAD

**Issue by Willburn** [IntersectMBO/cardano-ledger#1787]
I have several errors of "Staking credential registered in rewards map" if I check my logs. It seems to be a MempoolRejectedTx. I was wondering what this errors means?

Link to pastebin of logs:
https://gist.github.com/Willburn/3d78d19b47110c51dff0aa921c39b692

**Comment by JaredCorduan** [comment]
This error is saying that a registration certificate was issued for a stake credential which is already registered.

**Comment by erikd** [comment]
@JaredCorduan This was reported by an SPO (and other SPOs have seen similar logs messages). In all cases, it was not the SPO submitting this to their own node. Normally I would expect anyone generating the above transaction would submit it to their own node where it would be rejected. Does this mean that someone is generating this transactions, but then submitting it to other nodes?

**Comment by Willburn** [comment]
Yes I was not doing any new registration of certificates with transactions and as can be seen on the gist this was several such transactions during a small time period.

**Comment by JaredCorduan** [comment]
> @JaredCorduan This was reported by an SPO (and other SPOs have seen similar logs messages). In all cases, it was not the SPO submitting this to their own node. Normally I would expect anyone generating the above transaction would submit it to their own node where it would be rejected. Does this mean that someone is generating this transactions, but then submitting it to other nodes?

I see, thank you for the context! That could well be what is going on. I am not sure where the best home for this issue is, perhaps ouroboros-network or cardano-node.

**Comment by JaredCorduan** [comment]
https://github.com/input-output-hk/ouroboros-network/issues/1743 is the underlying issue
