### ISSUE TITLE
PRTCL Discrepancies

### ISSUE THREAD

**Issue by xenocidewiki** [IntersectMBO/cardano-ledger#1800]
I found a few issues when reviewing Prtcl:

- PrtclEnv has 4 members, _osched, pd, dms, and nonce_, this is seen in the code but missing in the formal spec, P. 83, Fig 70. Section 12.12 mentions this but it is just not reflected in Fig. 70. https://github.com/input-output-hk/cardano-ledger-specs/blob/985da4511eec48553ee6a3210768e4b912338e4a/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs#L102-L108

- PrtclState is missing the "last applied block information" field. It is mentioned in section 12.12 but is NOT reflected by Fig. 70 AND the code.

- The formal spec says that Prtcl has no predicate failures, but there are in fact two as of now: OverlayFailure and UpdnFailure. https://github.com/input-output-hk/cardano-ledger-specs/blob/985da4511eec48553ee6a3210768e4b912338e4a/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs#L134-L137

- In Fig. 71 we have PrtclEnv and OverlayEnv being used. The former has the order: osched pd dms n0, whereas the latter has the order: osched n0 pd dms. Just a suggestion, but perhaps it would be good to switch one of them about to keep the same order of parameters to keep it consistent?

- Naming issues
    - ~~etaV, etaC etc. pop up again. It seems that this is consistent throughout multiple files? I went back to check UPDN and that seems to use eta_v and eta. However the formal spec naturally uses n instead of eta for everything. Is it a good idea to change one or the other to better reflect this? Nothing major though as this is just naming related.~~ "eta" seems to be used because the formal spec uses the greek letter eta, in which case this is not really a problem
    
    - In Fig. 71 the nonce is specified to be _n := bnonce (bhbody bhb)_ and the code equivalent is here: https://github.com/input-output-hk/cardano-ledger-specs/blob/985da4511eec48553ee6a3210768e4b912338e4a/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Prtcl.hs#L162-L164 -> Perhaps it is better to make a bnonce helper function?

**Comment by JaredCorduan** [comment]
> The formal spec says that Prtcl has no predicate failures, but there are in fact two as of now: OverlayFailure and UpdnFailure.

That's true, I guess it should say something more like "has no predicate failures besides those of its sub-transitions". I think we have been consistent in the spec in not counting children errors as parent errors.
