### ISSUE TITLE
Unfair Pool ranking

### ISSUE THREAD

**Issue by Proxiweb** [IntersectMBO/cardano-ledger#1823]
Actually IOG1, saturated, with 7% fee is ranked No 1 for a whole epoch. Something is wrong, obviously.

**Comment by nc6** [comment]
Are you seeing this using the non-myopic utility calculations? Need more detail on what exactly is being seen.

**Comment by Proxiweb** [comment]
It's the ranking in Daedalus.

**Comment by nc6** [comment]
Linking to the other issue raised on this - the ranking is operating as it's designed, and changes to that ranking should probably be raised through the CIP process:

https://github.com/input-output-hk/cardano-ledger-specs/issues/1828

https://github.com/cardano-foundation/CIPs/blob/master/CIP1/CIP1.md
