### ISSUE TITLE
Extend desirability function to consider oversaturated pools

### ISSUE THREAD

**Issue by ilap** [IntersectMBO/cardano-ledger#1828]
Desirability function is based on the assumption of the Nash equilibrium, and therefore does not consider the possibility of the over-saturation of the pools. 
As a consequence, an over-saturated pool will have the same desirability, and therefore ranking, than any `non-` or `fully saturated` pool.

Though, I understand the logic of the decision, but I think the desirability and therefore the ranking should consider the over-saturated pools to indirectly incentivase the users to delegate to the `non-saturated` pools.

This new addition could be considered as some `max threshold` i.e. max 100% of the desirability, which depends only on the level of the oversaturation of the relevant pool.

![Monetary epansion](https://microsoft.codecogs.com/png.latex?\dpi{100}%7Bz_0%20%5Cover%20max%28%5Csigma%2C%20z_0%29%7D%20%5Ctilde%20f%28s%2C%20%5Coverline%20p%29)

This can be very easily implemented in the haskell code by slightly modifying these three function belows:
- https://github.com/input-output-hk/cardano-ledger-specs/blob/9dd938b2fa66c0712293aa7f273ca9450bdd05a6/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Rewards.hs#L251
- https://github.com/input-output-hk/cardano-ledger-specs/blob/9dd938b2fa66c0712293aa7f273ca9450bdd05a6/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Rewards.hs#L277
- https://github.com/input-output-hk/cardano-ledger-specs/blob/9dd938b2fa66c0712293aa7f273ca9450bdd05a6/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Wallet.hs#L60

**Comment by ilap** [comment]
I think it's not necessary, as the ranking is not based mainly on the ranking and desirability mechanism, but the expected non-myopic rewards inherited from them.

**Comment by ilap** [comment]
I do not think it is necessary as the non-myopic reward would consider the oversaturated stake later anyway.
But, it would be a nice to have feature for checking the oversaturation at the ranking/desirability part too and not just in the non-myopic reward, to allow some others to be fit in the `k` number of pools instead of an over-saturated one.

**Comment by nc6** [comment]
I think the sensible thing here is to follow the CIP: https://github.com/cardano-foundation/CIPs/blob/master/CIP1/CIP1.md

The current ranking scheme is operating as designed; a change to the design needs to be proposed and considered more widely. Issues here are more for things we know we want to change!
