### ISSUE TITLE
Translate some properties as STS Assertions

### ISSUE THREAD

**Issue by uroboros** [IntersectMBO/cardano-ledger#1842]
Given that we now have Assertions on STS level, we can port some of our properties (specified on STS Trace level) to Assertions.
A prelim list of candidates are:

TestChain: 

*  `checkPreservation`
* `checkWithdrawlBound`
* `potsSumIncreaseWdrlsPerTx` (this is a Tx level version of `potsSumIncreaseWdrlsPerBlock`)

**Comment by JaredCorduan** [comment]
The assertions have actually been less helpful that we would have guessed. The "deposit pot must be non-negative" assertion is almost always masking another problem due to an invalid transaction.
