### ISSUE TITLE
`nonMyopicStake` implementation not adding member stake for non-top k pools

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#1898]
Section 5.6.4 of the delegation design document mentions that "we will have to replace σ_nm by s + t in Equation (3)" for pools not in the top k desirability ranking. This is also missing from the pool ranking document. See https://github.com/input-output-hk/cardano-ledger-specs/issues/1892#issuecomment-703571701

**Comment by PhilippeLeLong** [comment]
As I commented in the other issue, I think there might be a problem how the intended member stake is implemented. But it seems that this is not addressed in the design specification. In order to rank the pools based on the intended member stake t, t needs to be added to the live stake sigma, otherwise the member rewards calculation will be wrong if sigma + t > z0.
When you adress your question to Lars Brunjes you might want to clarify this as well, if you agree on my point.

**Comment by JaredCorduan** [comment]
> As I commented in the other issue, I think there might be a problem how the intended member stake is implemented. But it seems that this is not addressed in the design specification. In order to rank the pools based on the intended member stake t, t needs to be added to the live stake sigma, otherwise the member rewards calculation will be wrong if sigma + t > z0.
> When you adress your question to Lars Brunjes you might want to clarify this as well, if you agree on my point.

indeed, there are a few subtitles that need to be clarified. the API function that the ledger exposes actually accepts [either a stake credential or a lovelace value](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/API/Wallet.hs#L110). for the the stake credentials, we look up the lovelace value in the live/active stake mapping, so we don't need to adjust anything. But for the option of just providing a lovelace value it is less clear (at least to me!) what the assumption being made is.

**Comment by JaredCorduan** [comment]
@Klobbinger I have confirmed with the researchers that the assumption is that `t` is active stake, and hence no need to adjust the denominator.

**Comment by PhilippeLeLong** [comment]
@JaredCorduan Not sure I understand what you mean by
> the assumption is that t is active stake, and hence no need to adjust the denominator.

But I looked at the changes in #1916 and can see that you correctly added `t` to the non myopic stake function:

```
nonMyopicStake pp (StakeShare s) (StakeShare sigma) (StakeShare t) kh topPools =
  let z0 = 1 % max 1 (fromIntegral (_nOpt pp))
   in if kh `Set.member` topPools
        then StakeShare (max sigma z0)
        else StakeShare s

        then StakeShare (max (sigma + t) z0)
        else StakeShare $ s + t
```
Now, if the slider in the wallet's delegation center uses the wallet API correctly, the ranking should be correct in case a delegator plans on delegating an amount that would oversaturate the top k pools. 

Thanks for fixing this, looking forward to the production update.

**Comment by JaredCorduan** [comment]
> Not sure I understand what you mean by

I think I just misread your original comment. :) Now I see that we are in agreement. hooray for the clarity of math :)
