### ISSUE TITLE
Chain transition consistency

### ISSUE THREAD

**Issue by nankeen** [IntersectMBO/cardano-ledger#1907]
`chainChecks` is a 2 argument helper in Figure 75, there's an additional `maxpv` here.

https://github.com/input-output-hk/cardano-ledger-specs/blob/d8a6e0d5c73299ca42998a34be2fb01e4c95b56e/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs#L243

`EpochState` has 6 fields here. Figure 76 describes only 4 fields, non-myopic data is missing (related to #1319) along with an additional field to the left.

https://github.com/input-output-hk/cardano-ledger-specs/blob/d8a6e0d5c73299ca42998a34be2fb01e4c95b56e/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Chain.hs#L282

The additional _'_ on the subscript _cur'_ in Figure 76 could be a typo.
![](https://user-images.githubusercontent.com/6895854/95747665-b6679e00-0c90-11eb-940c-c5dc9ea0a97f.png)

**Comment by jmhrpr** [comment]
If the incorrect number of fields used for EpochState is a mistake, it may be worth noting that this mistake also occurs in figure 75 within the definitions for the `getGKeys` and `updateNES` chain transition helper functions.
