### ISSUE TITLE
Problem with FromCBOR [a] Shelley vs Byron

### ISSUE THREAD

**Issue by TimSheard** [IntersectMBO/cardano-ledger#1909]
The (instance ToCBOR a => ToCBOR [a]). This uses the Begin .. End encoding,
While encodeList uses the list-length encoding.
--     toCBOR [5::Int,2]     --> [TkListBegin,TkInt 5,TkInt 2,TkBreak].
--     encodeList [5::Int,2] --> [TkListLen 2,TkInt 5,TkInt 2]

The (instance FromCBOR a => FromCBOR [a]) will ONLY RECOGNIZE THE BEGIN END ENCODING.
But the decoder (decodeList fromCBOR) will recognize both styles of encoding. So in a decoder for a FromCBOR instance it is always preferable to use (decodeList fromCBOR) over (fromCBOR)
For example we could write either of these 2 lines
--       2 -> do { l <- decodeList fromCBOR; pure(2,C l) }
--       2 -> do { l <- fromCBOR; pure(2,C l) }
Because THE FIRST IS MORE GENERAL. 

This distinction flows from the Byron need to be cannonical
If this was not the case we could just fix the following instance:

-- instance FromCBOR a => FromCBOR [a]  
-- Defined in ‘cardano-binary-1.5.0:Cardano.Binary.FromCBOR’

How do we fix this without messing up Byron?

**Comment by JaredCorduan** [comment]
I think the only thing we can really do is switch to using `encodeList` and `decodeList` from Shelley onward. We have a similar issue with maps.
