### ISSUE TITLE
Incorrect RandomnessStabilisationWindow used for nonce calculation 

### ISSUE THREAD

**Issue by AndrewWestberg** [IntersectMBO/cardano-ledger#1914]
In the LedgerSpec document p. 74, figure 61 under Update Nonce Transition, it states that the RandomnessStabilisationWindow should be used.

The RandomnessStabilisationWindow is defined as `4k/f`
https://github.com/input-output-hk/cardano-ledger-specs/blob/93d0e53516d09eb43d1822eed1a0244fd90ba9cb/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/StabilityWindow.hs#L36

However, in the actual calculations, the node is using the stabilityWindow which is defined as `3k/f`
https://github.com/input-output-hk/cardano-ledger-specs/blob/93d0e53516d09eb43d1822eed1a0244fd90ba9cb/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Updn.hs#L63

Given that correcting the code would likely require a hard fork, we should consider updating the formal spec document to use stabilityWindow instead of randomnessStabilisationWindow.

I'm working on calculating epochNonce values in JorManager and have dumped values for nc and nh from the node which confirms that nc is coming from a block stabilityWindow distance from the epoch and not randomnessStabilisationWindow distance from the epoch.

**Comment by JaredCorduan** [comment]
thank you @AndrewWestberg ! there is a single use of the `randomnessStabilisationWindow` in both the spec and the implementation, and indeed they do not agree. The spec uses it in the `UPDN` transition, the implementation uses it in `RUPD`.

https://github.com/input-output-hk/cardano-ledger-specs/blob/93d0e53516d09eb43d1822eed1a0244fd90ba9cb/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Rupd.hs#L68

I'm pretty confident that the spec is correct (unfortunately). I agree that we should change the spec to what was implemented, and then make a new appendix section for the mistake so that we can correct it at the next hard fork.

**Comment by AndrewWestberg** [comment]
@JaredCorduan Was this corrected at the Allegra hardfork?  @dcoutts mentioned on the SPO call that it was corrected, but I'd like confirmation from you.

**Comment by AndrewWestberg** [comment]
Unless I'm looking in the wrong place, the executable specs on master do not appear to be changed so I'm thinking @dcoutts 's statement in the SPO call was not correct.

**Comment by JaredCorduan** [comment]
No, we did not change anything with respect to the stability windows at the hard fork. I did talk with the authors of the Praos paper, and indeed there is no harm in the 3k/f stability window for freezing the nonce (in Praos). We may change it for Genesis, though, but there is no rush.

I will be putting up an errata soon to the shelley ledger spec. I was going to say something like:
```
The constant $RandomnessStabilisationWindow$ was intended to be used only    
for freezing the candidate nonce in the $\mathsf{UPDN}$ rule    
from Figure~\ref{fig:rules:update-nonce}.    
This was chosen as a good value for both Ouroboros Praos and Ouroboros Genesis.    
The implementation mistakenly used the constant in the $\mathsf{RUPD}$ rule    
from Figure~\ref{fig:rules:reward-update}, and used $\StabilityWindow$    
in for the $\mathsf{UPDN}$ transition.    
                        
The constant $\StabilityWindow$ is a good choice for the $\mathsf{UPDN}$    
transition while we remain using Ouroboros Praos, but it will be changed before    
adopting Ouroboros Genesis in the consensus layer.    
                        
There is no problem with using $RandomnessStabilisationWindow$ for the    
$\mathsf{RUPD}$ transition, since anything after $\StabilityWindow$ would work,    
but there is no reason to do so. 
```
