### ISSUE TITLE
[QUESTION] V. Butterin attack vector on Praos

### ISSUE THREAD

**Issue by mark-stopka** [IntersectMBO/cardano-ledger#2011]
When researching [Wikipedia article on Ouroboros](https://en.wikipedia.org/wiki/Ouroboros_(protocol)) I came accross this [link to Reddit](https://www.reddit.com/r/cardano/comments/92r3si/vitalik_allegations_against_ouroboros/e38j0ig/), yet it seems unanswered if:

> I can think of two strategies for beating this attack. First, you can try to dynamically adjust the slot length and the consensus weight of slots (or alternatively, start assigning multiple sequential slots to the same node) if the protocol detects that too many blocks are being created off the main chain, so that eventually network latency drops to below the new de-facto average block time. Given that the reduction on page 15 of the paper depends on Δ-1 consecutive ⊥ slots, I'm guessing Praos is doing something like this; can someone confirm? Alternatively, you can use GHOST.

> However, even in this case, you're getting semi-synchronous chain growth, not semi-synchronous safety, as if there is a situation where a node accepts a block as finalized, and then network latency suddenly increases sharply (eg. it keeps rising exponentially), then an attacker chain could outgrow it. So it's not quite the same thing that you can get with traditional BFT-inspired algorithms, though I grant that it's a nice property to have (though I would be interested in a comparison between what you're doing and just using GHOST).

> Hi Vitalik,
> I'm one of Aggelos' students, and took a closer look at this today. Tl;dr, you're correct, this is a valid attack, Praos assumes a specific relation between adversarial stake and synchronuity, which your situation violates.
> Let's consider this under Theorem 5 of Ouroboros Praos. In this setting we have Δ = 10, and α = 5/6. We note that chain growth only holds if α(1-f)^Δ ≥ (1+ε)/2, for some f, ε between 0 and 1. In particular, in this case, this means f neads to be at most approximately 0.04, which translates to only one in 20 slots being "active" (in which case, it is trivial to see that on average parties will see the preceding block, even with a 10 slot delay). We note that this equation encodes a type of honest majority assumption, and dynamically defines how much stake needs to be honest to achieve security in some Δ-semisynchronous setting.

> It also seems to be that if Δ >= 1/f * ln(2), then you can get no security guarantee at all, at least using your existing proofs. Is that correct?

Is this a valid vector of attack or has it been mitigated later on?

**Comment by JaredCorduan** [comment]
I asked the authors of the Praos paper, and was told that there is no issue here and no attack. ouroboros for a given parameterization is secure for a range of Δ values departing from honest majority more and more the higher Δ is. this is explained in the paper.

**Comment by mark-stopka** [comment]
@JaredCorduan thanks.
