### ISSUE TITLE
Errata in reward calculation (formal spec)

### ISSUE THREAD

**Issue by csoroz** [IntersectMBO/cardano-ledger#2040]
If I understand correctly, the formal ledger-spec (Fig. 47) is using `tot` = _active stake_ for the reward calculation (whereas design and exec spec are using _total stake_)
<img width="852" alt="Screenshot 2020-12-06 at 00 18 20" src="https://user-images.githubusercontent.com/3624828/101297528-af40b480-3829-11eb-95a1-52782a1a1b3a.png">

**Comment by JaredCorduan** [comment]
yes indeed, thank you @csoroz ! In fact, `rewardOnePool` is going to need the pool's stake relative to both, since for rewards it is relative to the total supply and for the apparent performance it is relative to the active stake.

**Comment by JaredCorduan** [comment]
closed by #2332
