### ISSUE TITLE
Node eligibility calculation inconsistency

### ISSUE THREAD

**Issue by nankeen** [IntersectMBO/cardano-ledger#2043]
![Screenshot 2020-12-07 at 16 23 57](https://user-images.githubusercontent.com/6895854/101376535-9d522680-38a8-11eb-836b-6524b5d9f194.png)

I suspect _greater than_ in the bottom definition might be a typo, the executable spec returns true when q is _less than_ the exp(-sigma * c).

https://github.com/input-output-hk/cardano-ledger-specs/blob/581767d1329f3f702e332af08355e81a0f85333e/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs#L718

It is also contradicting the first formula.

**Comment by JaredCorduan** [comment]
yes, you are correct, thank you @nankeen !

It seems that the names have become confusing. what is named `q` in the spec is called `recip_q` in the implementation. I'll fill in some details here for history's sake.

The VRF doesn't actually give us `\ell`, but rather that `certNat`, and we let `\ell =certNat / 2^512`. Note that in the comments in the code, `\ell` is named `p`:

https://github.com/input-output-hk/cardano-ledger-specs/blob/581767d1329f3f702e332af08355e81a0f85333e/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BlockChain.hs#L694

So indeed we want `1 / (1 - \ell) < exp(-σ * c)`

**Comment by JaredCorduan** [comment]
It seems that `p` and `q_recip` came from the non-integral spec:

![pq](https://user-images.githubusercontent.com/943479/101387529-8e5d7b00-388c-11eb-8ab0-0e9533947241.png)

**Comment by csoroz** [comment]
There is a typo in the 2nd paragraph:
<img width="241" alt="Screenshot 2020-12-09 at 16 09 20" src="https://user-images.githubusercontent.com/3624828/101647395-f6e95b00-3a38-11eb-96fc-eac1ae43bbf1.png">

**Comment by JaredCorduan** [comment]
closed by #2332
