### ISSUE TITLE
`computeStabilityWindow` uses `Double` and so "rounds" counter-intuitively

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/cardano-ledger#2073]
I was surprised by this behavior in `computeStabilityWindow`. I looked for a preexisting Issue, but I didn't find it. Perhaps this Issue will just be archived as a public explanation/warning of intended behavior.

https://github.com/input-output-hk/cardano-ledger-specs/blob/823d06c4287f6ae51d0b17fe8e3b3697e1226e24/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/StabilityWindow.hs#L21-L24

An example -- note that `60 /= 61`:

```
Prelude GHC.Real Data.Word> :set -XTypeApplications
Prelude GHC.Real Data.Word> let k = 7 :: Word64
Prelude GHC.Real Data.Word> let f = 7 / 20 :: Ratio Word64   -- this is ultimately the ActiveSlotCoeff type
Prelude GHC.Real Data.Word> ceiling $ fromIntegral @_ @Double (3 * k) / fromRational (toRational f)
61
Prelude GHC.Real Data.Word> ceiling $ fromIntegral @_ @Rational (3 * k) / fromRational (toRational f)
60
Prelude GHC.Real Data.Word> ceiling $ fromIntegral (3 * k) / toRational f
60
```

* Is this kind of "surprise" harmless as long as we're consistent?

* Even so, is it too confusing? I understand that `Double` will be a tighter bound on the computational cost, but are we computing the stability window often enough for that to matter?

* Perhaps the "Non-integer calculations specification" (which I haven't read carefully) forbids the use of `Rational`. I suppose it might be awkward/tedious to compute with as-needed precision in lower-level languages.

* I wonder if there's a clever manual fusion that is most efficient/bounded and exact.

My personal takeaway, regardless of how this issue is resolved: just import `computeStabilityWindow` in downstream libraries!

**Comment by JaredCorduan** [comment]
thank you for pointing this out @nfrisby , I was unaware of this function.

the stability window is only ever computed once (per chain) and is stored as a [global constant](https://github.com/input-output-hk/cardano-ledger-specs/blob/497f4aedd33cdea199157200814561db37e4753d/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/BaseTypes.hs#L400). it looks like the function `computeStabilityWindow` is only used in the function `mkShelleyGlobals`.

On mainnet `k=2160` and `f=1/20`, and with these values both `@Double` and `@Rational` agree, so I think that we can still change `computeStabilityWindow` to use `@Rational` if folks agree that this is more clear (I prefer using rational).
