### ISSUE TITLE
MissingScriptWitnessesUTXOW can be unclear

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2085]
If a transaction contains more scripts than is needed, the ledger correctly rejects the transaction, but the error is unclear. The error displays only the difference between the needed scripts and the scripts it actually received. I think that the correct thing to do is to add a new error for the case of superfluous scripts.

https://github.com/input-output-hk/cardano-ledger-specs/blob/f84bae4334f5117667af598388352f75b3660175/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Utxow.hs#L326-L328

**Comment by catch-21** [comment]
Example of error currently seen when submitting transaction that was singed with superfluous script:
`Shelley command failed: transaction submit  Error: Error while submitting tx: ApplyTxError [LedgerFailure (UtxowFailure (MissingScriptWitnessesUTXOW (fromList [])))]`

**Comment by JaredCorduan** [comment]
fixed by #2527
