### ISSUE TITLE
Small-step-tests are failing

### ISSUE THREAD

**Issue by TimSheard** [IntersectMBO/cardano-ledger#2093]
The small steps tests are failing (even in master) 
To reproduce cd to the small steps test directory and run the tests.  Here is a transcript.

[nix-shell:~/four/cardano-ledger-specs]$ cd semantics/small-steps-test/

[nix-shell:~/four/cardano-ledger-specs/semantics/small-steps-test]$ cabal test --test-show-details=streaming
Warning: Requested index-state2020-11-15T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2020-11-14T23:50:07Z).
Resolving dependencies...
Build profile: -w ghc-8.10.2 -O1
In order, the following will be built (use -v for more details):
 - cardano-prelude-0.1.0.0 (lib) (configuration changed)
 - goblins-0.2.0.0 (lib) (configuration changed)
 - small-steps-test-0.1.0.0 (test:doctests) (configuration changed)
 - cardano-binary-1.5.0 (lib) (configuration changed)
 - cardano-crypto-class-2.0.0 (lib) (configuration changed)
 - small-steps-0.1.0.0 (lib) (configuration changed)
 - small-steps-test-0.1.0.0 (lib) (configuration changed)
 - small-steps-test-0.1.0.0 (test:examples) (configuration changed)
Configuring library for cardano-prelude-0.1.0.0..
Configuring library for goblins-0.2.0.0..
Configuring test suite 'doctests' for small-steps-test-0.1.0.0..
Preprocessing library for cardano-prelude-0.1.0.0..
Building library for cardano-prelude-0.1.0.0..
Preprocessing test suite 'doctests' for small-steps-test-0.1.0.0..
Building test suite 'doctests' for small-steps-test-0.1.0.0..
Preprocessing library for goblins-0.2.0.0..
Building library for goblins-0.2.0.0..
Running 1 test suites...
Test suite doctests: RUNNING...
doctests: <command line>: cannot satisfy -package-id prettyprinter-1.7.0-L9BUdCzYor7LBsek1iasxd
    (use -v for more information)
Test suite doctests: FAIL
Test suite logged to:
/home/sheard/four/cardano-ledger-specs/dist-newstyle/build/x86_64-linux/ghc-8.10.2/small-steps-test-0.1.0.0/t/doctests/test/small-steps-test-0.1.0.0-doctests.log
0 of 1 test suites (0 of 1 test cases) passed.
cabal: Tests failed for test:doctests from small-steps-test-0.1.0.0.

**Comment by JaredCorduan** [comment]
seems fixed by the above
