### ISSUE TITLE
Rename packages to be consistent and indicates the eras

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/cardano-ledger#2109]
@nc6 and I had a brief exchange on Slack where we agreed that it's probably worthwhile at this point to re-establish a naming convention for the packages in this repository. From the downstream Consensus side, my only request is that the names make the mapping between packages and eras (Byron, Shelley, Allegra, Mary, Alonzo, etc) as obvious as possible.

**Comment by JaredCorduan** [comment]
fixed by #2483
