### ISSUE TITLE
Mistake in formal spec definition of function createRUpd

### ISSUE THREAD

**Issue by jmhrpr** [IntersectMBO/cardano-ledger#2113]
In Figure 50 (Page 63) of the ledger formal spec, the definition of the `createRUpd` function, the denominator used in the calculation for eta (the ratio between the number of blocks that have been produced during the epoch and expected value of blocks that should have been produced under ideal conditions) has the decentralization parameter `d` as a factor but in the [executable spec this factor is `(1-d)`](https://github.com/input-output-hk/cardano-ledger-specs/blob/13bcb5931beb0d6ad8faa7bd2fbc5cfa1fed0ef0/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/LedgerState.hs#L1095).

Section 3.8 of the design spec states that the total number of blocks in the epoch is taken as the number of blocks produced in non-OBFT slots, and that `(d*n_s)` is the number of OBFT slots (thus `((1-d)*n_s)` is the number of non-OBFT slots) so, if I am not mistaken, it appears the formal spec is incorrect while the executable spec is correct.

**Comment by JaredCorduan** [comment]
closed by #2332
