### ISSUE TITLE
Inconsistency between Formal ledger spec and PoolReap.hs

### ISSUE THREAD

**Issue by social-anthrax** [IntersectMBO/cardano-ledger#2122]
### Formal Ledger spec:
Figure 40 in the formal ledger spec states that according to the pool reap inference rule `deposits` should be used to describe the following change:
![image](https://user-images.githubusercontent.com/40488664/106601176-43da4100-6553-11eb-9235-9d2fabca4d3e.png)
There is no mention of a function called `deposited` throughout the whole spec.

### Executable Ledger spec:
[Line 112 of PoolReap.hs](https://github.com/input-output-hk/cardano-ledger-specs/blob/8c8b11eee6709fc4086dd5e7d9d12a39e90d9db9/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/PoolReap.hs#L112) uses `_deposited`. I originally suspected that this was a simple change of spelling, however, there also exists another function called `deposits`, which seems to [originate from UtxO](https://github.com/input-output-hk/cardano-ledger-specs/blob/d1ecd9fed4771d880235063eb484e15e87733b62/shelley/chain-and-ledger/shelley-spec-ledger-test/src/Test/Shelley/Spec/Ledger/Generator/Utxo.hs)  but I have not been able to confirm its source.

### Issue
As both functions seem to be accessed elsewhere, this leads to confusion as to whether the Formal ledger spec references to the same function throughout or if there is a difference between `deposits` and `_deposited` and what the difference between them is.

**Comment by JaredCorduan** [comment]
good catch @social-anthrax , I agree that the inconsistency could lead to confusion. The `_deposited` function in the implementation is the record accessor function for `UTxOState` for the field called `deposits` in the formal spec.

It looks like there is also an inconsistency between `_ppups` in the implementation and `ups` in the spec.

**Comment by nc6** [comment]
Yep, this inconsistency comes up in the Alonzo spec as well.

**Comment by JaredCorduan** [comment]
closed by #2341
