### ISSUE TITLE
Minor operator inconsistency in Deleg-MIR between formal and executable spec

### ISSUE THREAD

**Issue by yellowtides** [IntersectMBO/cardano-ledger#2131]
<img width="794" alt="Screenshot 2021-02-09 at 13 54 49" src="https://user-images.githubusercontent.com/32711186/107373649-ab0d6d80-6ade-11eb-879d-4949da825f43.png">
In Figure 23 of the formal ledger specification, the combined reserves for the MIR are calculated as a union-override-right of the instantaneous rewards reserves and the moving rewards.

https://github.com/input-output-hk/cardano-ledger-specs/blob/9f9ba7da08edc142baee887f9f5c673dcec73d2b/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/Deleg.hs#L284

In the executable spec for DELEG however, these are calculated as a union-override-left (Map.union) with the arguments seemingly swapped. The functionality seems to thus be the exact same, but I think that this inversion coupled with the naming inconsistency might prove confusing.

**Comment by JaredCorduan** [comment]
That's a good point, this could lead to confusion. I think in the set algebra library we have a `⨃` that uses the same ordering as the spec. thank you @yellowtides !

**Comment by JaredCorduan** [comment]
closed by #2341
