### ISSUE TITLE
Alonzo Era for Consensus

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2137]
In order for the consensus team to start integrating the alanzo era:

https://github.com/input-output-hk/cardano-ledger-specs/blob/d794c7236201f51e4699195eea3d8a05b69a4dd9/alonzo/impl/src/Cardano/Ledger/Alonzo.hs#L23

we need at least a couple things still:

* `TranslateEra` instances, similar to the Mary ones https://github.com/input-output-hk/cardano-ledger-specs/blob/d794c7236201f51e4699195eea3d8a05b69a4dd9/shelley-ma/impl/src/Cardano/Ledger/Mary/Translation.hs#L60-L68
* Rule mappings, similar to the Mary ones https://github.com/input-output-hk/cardano-ledger-specs/blob/d794c7236201f51e4699195eea3d8a05b69a4dd9/shelley-ma/impl/src/Cardano/Ledger/ShelleyMA/Rules/EraMapping.hs#L24-L32

**Comment by JaredCorduan** [comment]
stubs are in place for the era mapping as of #2170

**Comment by nfrisby** [comment]
We're plugging this into our pre-integration branch now. I'll report back here. If the stubs suffice, we can close this 👍

**Comment by JaredCorduan** [comment]
@nfrisby do you think we can close this issue now?

**Comment by nfrisby** [comment]
Yes, thanks!
