### ISSUE TITLE
Implementation Effort and Timeline Estimation

### ISSUE THREAD

**Issue by goodengineer** [IntersectMBO/cardano-ledger#2143]
To: Engineering Coding Enthusiasts,

Greetings,

   
In DLT systems hashing(digesting, scatter-storage addressing encoding) is of a paramount utilization, and so improving just one algorithm and corresponding function will improve performance in many places in a ledger's software where it is permanently used.

Currently, used hashing from cryptonite sw, which contains ChaCha, Salsa, Keccak, BLAKE2(not to remove from it, as this hashing algorithms are good for interoperability for another IIoT applicable DLTs, while there are more hashing algorithms that can be pruned due to the upgrade) implementations, but no full BLAKE3(which is faster) and (BLAKE2s/BLAKE2d whether?)
What if to replace/add SHA1 and other "low-performant" criptonite hashing functions by next hashing: modified(cryptography empowered) XXH3 https://cyan4973.github.io/xxHash/ (to transcode to Haskell or to link without transcoding, how? and include in Cardano internals) and BLAKE3 as already cryptographically empowered, NIST competitions winner candidate, highly parallelization-able, with Tree inside, Rust and C implemented: https://github.com/BLAKE3-team/BLAKE3
(to transcode to Haskell and include in Cardano SW)?

  

In Stellar XLM crypto protocol, they started to work on this realization, which is smart and correct. Finally, we only just tend for practically beneficial on global scale for general humankind working upright, corruption disabling financial tool, more convenient and leading to significant improvements of global life comfort and so different ledgers as a requirements-rewards swaying machines can be combined having clear, benign goals.

My question is who can estimate w.h.p. and what is the estimated(precise work group structure(which will take and lead to final running realization), economical benefit of full running realization of the idea(how much we can earn  from realized running new hashing, I estimate it is substantially perceptible earning), number of days required till full running feature/novelty done, other related work metrics/decomposition details, required work existing code modifications and new code modules creation effort(implement in Haskell cryptographically empowered XXH3 and BLAKE3 and, "prune" cryptonite sw(remove old hashing), add new hashing(BLAKE3) in places of old hashing algorithms) and timeline to  replace/add the novel Hashing functionality with provable performance(in terms of time, space and attacks resistance). 

Sincere and Kind Regards,
Engineer: P.E. Mazniker.

**Comment by dcoutts** [comment]
Thanks for the suggestions.

Cardano uses Blake2b hashing, which has a good balance of good performance, and well-understood security.

We don't need to "prune" SHA1 etc because we do not use it at all. We only use Blake2b (except in one place in the Byron ledger where SHA3 256 is used).

We have no plans to switch to Blake3. The advice from our cryptographers is that this would be ill advised.

There are perhaps opportunities to improve performance with crypto primitives, but we think there is much more opportunity with the VRF and with the ordinary signature algorithm, rather than in changing hashing algorithm. It would be better to focus limited time there.
