### ISSUE TITLE
Inconsistency between Multi-asset formal specification and Utxo.hs from shelley-ma

### ISSUE THREAD

**Issue by social-anthrax** [IntersectMBO/cardano-ledger#2168]
## Executable ledger specification.
Within the [`utxoTransition` function on line 313](https://github.com/input-output-hk/cardano-ledger-specs/blob/f151e8252bb0478b1f9ca7705971591e22836e5a/shelley-ma/impl/src/Cardano/Ledger/ShelleyMA/Rules/Utxo.hs#L313) there exists a function `outputsTooBig`, which from my understanding exists so that the TX size wouldn't be used up.
![image](https://user-images.githubusercontent.com/40488664/109964814-10bbd680-7ce6-11eb-907d-4aa900384fd3.png)

## Formal Specification
The formal specification makes no mention of this function and does not mention a function with similar usage. The utxoTransition function is described in figure 5 as shown below.
![image](https://user-images.githubusercontent.com/40488664/109967236-149d2800-7ce9-11eb-8892-88ff7a1f85eb.png)

## Issue
The `outputsTooBig` function seems essential to prevent attacks that could use up the TX size but does not seem to be documented in the formal specifications.

**Comment by polinavino** [comment]
Done in https://github.com/input-output-hk/cardano-ledger-specs/pull/2383
