### ISSUE TITLE
Type mismatch present in the ShelleyMA/Shelley formal specs when calculating the stake relation in the Rewards and the Epoch Boundary

### ISSUE THREAD

**Issue by yellowtides** [IntersectMBO/cardano-ledger#2174]
<img width="876" alt="Screenshot 2021-03-08 at 15 06 52" src="https://user-images.githubusercontent.com/32711186/110339299-ec326800-801f-11eb-9896-e4862ef90397.png">

In figure 7 of the ShelleyMA formal spec, in the calculation of the stake relation, there seems to be a composition performed between `stakeCred_r^{-1}` and `rewards`.

<img width="813" alt="Screenshot 2021-03-08 at 15 10 34" src="https://user-images.githubusercontent.com/32711186/110339777-7084eb00-8020-11eb-999b-e08af49a8367.png">

In figure 5 of the Shelley formal spec, we see that `stakeCred_r` is a map from `Addr` to `Cred`. This would imply that `stakeCred_r^{-1}` is a map from `Cred` to `Addr`.

<img width="835" alt="Screenshot 2021-03-08 at 15 13 01" src="https://user-images.githubusercontent.com/32711186/110340093-c78ac000-8020-11eb-883f-89f5b6ae9381.png">

In figure 21 of the Shelley formal spec, we see that `rewards` is a map from `Cred` to `Coin`. 

Since this is the case (and that we define the composition of two maps, one of type A -> B, and the other B -> C as a resulting map of type A -> C), it would not make sense to compose `stakeCred_r^{-1}` (which is of type  `Cred -> Addr`) with `rewards` (which is of type `Cred -> Coin`). This composition (and mismatch) seems to also be present in the Shelley spec.

The executable spec seems to be implementing the stake relation calculation correctly, ignoring `stakeCred_r^{-1}` (and the composition) entirely, unionising the left side with just the `rewards`.

**Comment by JaredCorduan** [comment]
closed by #2341
