### ISSUE TITLE
Policy for regulating native asset transfers

### ISSUE THREAD

**Issue by Flavien** [IntersectMBO/cardano-ledger#2266]
I am not sure this has been discussed before, but please consider either adding a new transfer policy script or generalising the forging policy to allow regulating transfer of native assets as well.

There are many use cases where the issuer might want to restrict the transfer of an asset based on some specific conditions (e.g. you may only start transferring the asset from a certain epoch, the asset must be transferred in conjunction with another asset, the asset must be transferred in exchange for another asset, etc.).

**Comment by JaredCorduan** [comment]
Such restrictions will be possible when we introduce Plutus scripts at the next planned hard fork.

**Comment by Flavien** [comment]
Ok so the Plutus script will not just run for forging/burning transactions?

**Comment by JaredCorduan** [comment]
indeed, Plutus scripts will be usable in transaction outputs, delegation certificates, reward withdrawals, and minting policies. moreover, they have access to some of the context surrounding the transaction, and can use this to restrict how the token is used.
