### ISSUE TITLE
Multi-asset formal spec timelock issue

### ISSUE THREAD

**Issue by nankeen** [IntersectMBO/cardano-ledger#2307]
There are a few issues regarding timelock in figure 9.

###  Reuse of `i_s` and `i_f`

In the last case where `ValidityInterval` is specified for `evalTimelock`, the parameters use `i_s` and `i_f` twice which introduces ambiguity as later on `i_s'` and `i_f'` are used.

![image](https://user-images.githubusercontent.com/6895854/120207859-d39fab80-c224-11eb-9d42-9f814a2ee92e.png)

### `evalMultiSigScript` not defined

`evalTimelock` is said to call `evalMultiSigScript` which is not the case in the executable spec.

https://github.com/input-output-hk/cardano-ledger-specs/blob/a3ef848542961079b7cd53d599e5385198a3035c/shelley-ma/impl/src/Cardano/Ledger/ShelleyMA/Timelocks.hs#L260

Here `evalTimelock` calls itself recursively instead of `evalMultiSigScript`.

![image](https://user-images.githubusercontent.com/6895854/120207991-f336d400-c224-11eb-83ab-187187ee8721.png)

### Argument order mismatch

Formal spec defines `evalTimelock` to take the script as the first argument, however it is implemented to take a set of key hashes first.

https://github.com/input-output-hk/cardano-ledger-specs/blob/a3ef848542961079b7cd53d599e5385198a3035c/shelley-ma/impl/src/Cardano/Ledger/ShelleyMA/Timelocks.hs#L250

![image](https://user-images.githubusercontent.com/6895854/120208679-aa334f80-c225-11eb-8c5c-609fe5c840c7.png)

### `ValidityInterval` is not a `Timelock` pattern

Figure 9 describes the following, where a time constraint can be placed via the policy script.

![image](https://user-images.githubusercontent.com/6895854/120208916-f2eb0880-c225-11eb-9e1e-5a7b4d5eff78.png)

But this is implemented with two separate patterns - `RequireTimeExpire` and `RequireTimeStart`.

https://github.com/input-output-hk/cardano-ledger-specs/blob/a3ef848542961079b7cd53d599e5385198a3035c/shelley-ma/impl/src/Cardano/Ledger/ShelleyMA/Timelocks.hs#L219

https://github.com/input-output-hk/cardano-ledger-specs/blob/a3ef848542961079b7cd53d599e5385198a3035c/shelley-ma/impl/src/Cardano/Ledger/ShelleyMA/Timelocks.hs#L226

This diverges in the sense that the start and end slots are defined separately in practice, and so the `ValidityInterval` case for `evalTimelock` in the formal spec does not quite make sense.

**Comment by polinavino** [comment]
Done in https://github.com/input-output-hk/cardano-ledger-specs/pull/2383
