### ISSUE TITLE
Remove extra parameter on utxoEntrySize

### ISSUE THREAD

**Issue by SebastienGllmt** [IntersectMBO/cardano-ledger#2346]
This definition of TxOut is the following triple
![image](https://user-images.githubusercontent.com/2608559/122894072-db64f280-d381-11eb-8b4c-ec15ade1c3d0.png)

However, the utxoEntrySize function takes in a data as an input instead of getting the data from the TxOut type (the type definition of utxoEntrySize, but the definition takes an unnecessary parameter `d`)
![image](https://user-images.githubusercontent.com/2608559/122894002-c9834f80-d381-11eb-840d-c1d3234bef33.png)

**Comment by polinavino** [comment]
thanks!

**Comment by JaredCorduan** [comment]
I couldn't quickly figure out when this was fixed, but I do see that it is correct now:

https://github.com/input-output-hk/cardano-ledger/blob/b86d15987170326d7a74837cc3072c84f4a4b76b/eras/shelley-ma/formal-spec/value-size.tex#L121
