### ISSUE TITLE
Naming inconsistency for isNonNativeScriptAddress in Alonzo formal spec/ implementation 

### ISSUE THREAD

**Issue by social-anthrax** [IntersectMBO/cardano-ledger#2364]
# Naming inconsistency 

Currently Figure4 contains a function called `isNonNativeScriptAddress`. A function with this name does not exist in the implementation, however, the function [`isTwoPhaseScriptAddress `](https://github.com/input-output-hk/cardano-ledger-specs/blob/91a97d0177c7e60a6e3bcb3e680b15dad2f91d90/alonzo/impl/src/Cardano/Ledger/Alonzo/Tx.hs#L282) has a similar signature and performs the same actions.

![img](https://user-images.githubusercontent.com/40488664/124160928-b0bb1e00-da94-11eb-9247-34f042551248.png)

*Relevant section from Figure 4*

-----

![image-20210701174733381](https://user-images.githubusercontent.com/40488664/124160983-c29cc100-da94-11eb-960d-7fc048c2b943.png)

*isTwoPhaseScriptAddress* - Pattern match fits the formal specification of `isNonNativeScriptAddress`

The function within the implementation should be renamed or the formal specification should be updated to match.

**Comment by JaredCorduan** [comment]
We are trying to get rid of the name "NonNative", but we've yet to find a great alternative...

**Comment by dcoutts** [comment]
Suggest "simple script" or "simple language" vs "Plutus script" or "Plutus language". Or specifically referring to two-phase validation.

**Comment by JaredCorduan** [comment]
we changed this but forgot to close the issue.
