### ISSUE TITLE
Stale comment in Alonzo's Plutus txinfo prep

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/cardano-ledger#2365]
It's possible I'm misunderstanding, but this comment mentions UTxO and `PtrMap` but I don't see anything such thing in its signature.

https://github.com/input-output-hk/cardano-ledger-specs/blob/91a97d0177c7e60a6e3bcb3e680b15dad2f91d90/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L325-L333

**Comment by JaredCorduan** [comment]
The comment is wrong, this explanation applies more to `txinfo`:

https://github.com/input-output-hk/cardano-ledger-specs/blob/91a97d0177c7e60a6e3bcb3e680b15dad2f91d90/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L285
