### ISSUE TITLE
Inconsistencies between the Alonzo formal specification and haskell implementation

### ISSUE THREAD

**Issue by xenocidewiki** [IntersectMBO/cardano-ledger#2366]
I found a couple smaller inconsistencies that I'd like to report.

### **No empty check on Dats**
In figure two we have three conditions to satisfy in order to return nothing, that is a null check on dats, rdmrs, and langs, relevant figure is below:
![image](https://user-images.githubusercontent.com/9161925/124382099-ed219080-dcc5-11eb-8e30-11ef91b14f72.png)

In the implementation the check for dats doesn't exist:
https://github.com/input-output-hk/cardano-ledger-specs/blob/91a97d0177c7e60a6e3bcb3e680b15dad2f91d90/alonzo/impl/src/Cardano/Ledger/Alonzo/Tx.hs#L269

### **Undocumented field in the formal spec**
In the haskell implementation TxWitnessRaw has a field called txwitsBoot, referenced here: https://github.com/input-output-hk/cardano-ledger-specs/blob/91a97d0177c7e60a6e3bcb3e680b15dad2f91d90/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWitness.hs#L167

It does say that you make two physical modifications in the code, but why not include it in the spec as well? 
![image](https://user-images.githubusercontent.com/9161925/124382170-586b6280-dcc6-11eb-9557-dd871859a6f5.png)

### **Order of parameters for TxBodyRaw**
This is rather cosmetic but the haskell implementation and formal spec have a different ordering of parameters here:
https://github.com/input-output-hk/cardano-ledger-specs/blob/91a97d0177c7e60a6e3bcb3e680b15dad2f91d90/alonzo/impl/src/Cardano/Ledger/Alonzo/TxBody.hs#L198-L216

If we compare this to figure three this is inconsistent. Not an issue per se but might be beneficial to keep the order the same :)

### **Small typo referencing wrong figure**
https://github.com/input-output-hk/cardano-ledger-specs/blob/91a97d0177c7e60a6e3bcb3e680b15dad2f91d90/alonzo/impl/src/Cardano/Ledger/Alonzo/Tx.hs#L279

I believe this comment is a typo and refers to figure 4 instead of 5, not really a huge issue though..

**Comment by lehins** [comment]
> No empty check on Dats

This issue has been fixed a few days ago in #2359

**Comment by JaredCorduan** [comment]
`Undocumented field in the formal spec` - This actually goes all the way back to Shelley. The Byron keys and the Shelley keys are actually the same (ed25519), it's just that the Byron addresses mistakenly included some information regarding deterministic wallet constructions that forced us to separate the types.

I think we would prefer to make mention of this fact somewhere in the Shelley spec, but keep the abstractions in the spec free of this detail. :thinking: (We may, in fact, have enough in Appendix C of the Shelley spec).

**Comment by JaredCorduan** [comment]
I think we can safely close this issue once we fix the comment to [here](https://github.com/input-output-hk/cardano-ledger/blob/7fbccfb0562a522f2b3d858d6bcbe119df758e6f/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Tx.hs) to point to figure 4.
