### ISSUE TITLE
Type inconsistency for Prices

### ISSUE THREAD

**Issue by nankeen** [IntersectMBO/cardano-ledger#2367]
The formal spec states that `prMem` and `prSteps` are `Coin` types which are integers.

![image](https://user-images.githubusercontent.com/6895854/124491798-92626480-ddab-11eb-85db-433def077de4.png)

The executable spec implements them as rational numbers.

https://github.com/input-output-hk/cardano-ledger-specs/blob/f79800ccd5567fa3e12ae5e539ce6185384d0249/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs#L201

This also results in having to take the ceiling of calculations like the following which isn't mentioned in the formal spec.

https://github.com/input-output-hk/cardano-ledger-specs/blob/f79800ccd5567fa3e12ae5e539ce6185384d0249/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs#L212

**Comment by dcoutts** [comment]
Thanks. We are in the process of making the prices fractional (with 1e-9 precision). We will have to update the formal spec to bring the two in line with each other.

**Comment by JaredCorduan** [comment]
the spec now uses rationals, thanks!
