### ISSUE TITLE
FeesOK inconsistent with Formal Specification

### ISSUE THREAD

**Issue by social-anthrax** [IntersectMBO/cardano-ledger#2370]
# FeesOK inconsistent with Formal Specification

The `FeesOK` function has multiple inconsistencies with the formal specification.

## Return Type

https://github.com/input-output-hk/cardano-ledger-specs/blob/ec9c77edbf5700a4b2ece8f97a1e313df06abc97/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L255-L274

Return type is stated to be `Rule (AlonzoUTXO era) 'Transition ()` Functionally this means that it will return (), and raise an error (rather than return) if any of the required parts are False. This contradicts the formal spec in which it states it returns a Boolean.

As a follow up to the inconsistency, rather than returning a Boolean there are specific errors that are thrown depending on what predicate failed. 

https://github.com/input-output-hk/cardano-ledger-specs/blob/ec9c77edbf5700a4b2ece8f97a1e313df06abc97/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L255-L300

The formal specification states that the function should simply return false, rather than distinguish between the different errors.

## Issue in figure 4 with collateral tx

`collateral tx` does not have an otherwise, or, or and before it in figure 4, making it impossible to tell what it is doing to influence the return type. 

![image-20210707180419123](https://user-images.githubusercontent.com/40488664/124801928-523be700-df4f-11eb-9183-d3fa199e01fa.png)

The implementation takes it to be part of the condition if `txrdmrs tx =/ null`, as does the written explanation of the formal specification 

> (v) the set of collateral inputs is non-empty (pg14)

The brackets should be expanded to include the `collateral tx` inside the `txrdmrs tx =/ null` section.

As a small nitpick, the order of the predicates being checked also changes between the formal specification and the implementation, although this is just a stylistic issue.

**Comment by JaredCorduan** [comment]
It's my opinion that the difference between returning Bool and returning something with a more descriptive version of `False` is an acceptable deviation from the spec. We do this in other places as well.

Good catch on the rogue `collateral tx`!

I think it would be nice to have the order of the predicates being checked be the same in the spec and the implementation.

**Comment by JaredCorduan** [comment]
I'm going to close this issue since we are okay with the spec using Bool, but having more expressive return types for the implementation.
