### ISSUE TITLE
Fix Alonzo block serialization so that it roundtrips

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/cardano-ledger#2397]
All I have is a repro.

This QuickCheck property

```
propRoundTripBlock :: SL.Block (AlonzoEra StandardCrypto) -> Property
propRoundTripBlock blk =
      case CBOR.deserialiseFromBytes decoder bs of
        Right{} -> property True
        Left e@(CBOR.DeserialiseFailure _ _) ->
            counterexample (show e)
          $ label (show $ (isInfixOf "PlutusScript" (show blk), isInfixOf "TimelockScript" (show blk)))
          $ property True
  where
    bs = CBOR.toLazyByteString encoding

    encoding = toCBOR blk

    decoder = do
      _ <- fromCBOR @(Annotator (SL.Block (AlonzoEra StandardCrypto)))
      return ()

```

gives

```
    +++ OK, passed 1000 tests:
    91.4% (True,True)
     1.7% (False,True)
     0.2% (False,False)
```

Meaning that with or without scripts of either variety, ~95% of the Alonzo blocks failed to roundtrip through `toCBOR` and `fromCBOR`.

I wasn't able to find which part of the serialization is failing, but the error is consistently "expecting word".

-----

@KtorZ found this error, using these dependency versions:

```
~/ouroboros-network$ cat cabal.project | grep -A3 -e source-repository-package
-- in order to force usage of nix provided dependencies for `source-repository-package`s.
-- --------------------------- 8< --------------------------
-- Please do not put any `source-repository-package` clause above this line.

source-repository-package
  type: git
  location: https://github.com/input-output-hk/Win32-network
  tag: 5b3d08c454f425da5cf045fe7865950d7c806691
--
source-repository-package
  type: git
  location: https://github.com/input-output-hk/iohk-monitoring-framework
  tag: 808724ff8a19a33d0ed06f9ef59fbd900b08553c
--
source-repository-package
  type: git
  location: https://github.com/input-output-hk/cardano-prelude
  tag: fd773f7a58412131512b9f694ab95653ac430852
--
source-repository-package
  type: git
  location: https://github.com/input-output-hk/cardano-base
  tag: b6a215c42a28dc8b71b42946fe30256a333d34af
--
source-repository-package
  type: git
  location: https://github.com/input-output-hk/cardano-ledger-specs
  tag: ec9c77edbf5700a4b2ece8f97a1e313df06abc97
--
source-repository-package
  type: git
  location: https://github.com/input-output-hk/plutus
  tag: 523f349f3d68db07c98150734793ed7003d1f562
--
source-repository-package
  type: git
  location: https://github.com/Quid2/flat.git
  tag: 95e5d7488451e43062ca84d5376b3adcc465f1cd
--
source-repository-package
  type: git
  location: https://github.com/input-output-hk/goblins
  tag: cde90a2b27f79187ca8310b6549331e59595e7ba
--
source-repository-package
  type: git
  location: https://github.com/input-output-hk/cardano-crypto
  tag: ce8f1934e4b6252084710975bd9bbc0a4648ece4

~/ouroboros-network$ git lg -5
2c210d969 - (HEAD, origin/nfrisby/ktorz-codec-error-repro) Adjust dependencies to match those of cardano-node@1.28.0 (3 days ago) <KtorZ>
abcb87df2 - (nfrisby/ktorz-codec-error-repro) TEMP KtorZ codec error repro (3 days ago) <Nicolas Frisby>
e338f2cf8 - Merge #3243 (3 weeks ago) <iohk-bors[bot]>

```

**Comment by JaredCorduan** [comment]
I just ran `propRoundTripBlock` in `cardano-ledger-specs` on master, and I cannot trigger the bug with `Left (CBOR.DeserialiseFailure _ _) -> property False`. I think @KtorZ 's hunch that it has to do with using a different version of `cardano-prelude`, `cardano-base`, or `plutus` in the other downstream repositories is likely.

**Comment by KtorZ** [comment]
@JaredCorduan yes indeed, this has been confirmed. We've only been able to trigger with the dependency set currently used by cardano-node in 1.28.0

**Comment by nfrisby** [comment]
Jared and I chatted a bit. It looks like there's no error on `master` branch, etc. It's specific (at least) to those versions that Matthias identified via node 1.28.0 tag.

So this Issue might be trivial to Close. Something like "understand why some (which?) particular upstream version doesn't let Alonzo blocks roundtrip" but confirm that there's nothing for `cardano-ledger-specs` to do about it.

I'm also curious: How does/did an upstream version break a RTT roundtrip test? IE what upstream PR changed one half of a serializer but no the other? Or similar.
  
Probably beyond the scope of this Issue, but related: How to prevent different repos from getting confused by using different combinations of upstream dependencies? Matthias started a conversation on Slack about this.
  
> The gist is: some part of the Alonzo blocks serialization does not roundtrip in 1.28.0., which makes for instance node clients choke during the chain-sync protocol. While the issue in itself isn't much impacting at the moment (only affects the Alonzo testnet), what I'd like to discuss is more the process and how we got there.

**Comment by JaredCorduan** [comment]
I just ran `propRoundTripBlock` in `cardano-ledger-specs`, with master and setting:

* `cardano-base` to `b6a215c42a28dc8b71b42946fe30256a333d34af`
* `cardano-prelude` to `fd773f7a58412131512b9f694ab95653ac430852`

(the same as what @nfrisby used to get the failure)

I do not get any failures.

**Comment by JaredCorduan** [comment]
Mystery solved.  The problem arose from a version of Plutus that forbid negative constructors, and a version of this repo that generated negative constructors. See https://github.com/input-output-hk/plutus/pull/3309.

This test

https://github.com/input-output-hk/cardano-ledger-specs/blob/30eca73a2f5c13f1fbed9a98a59540ac3d0c8afe/alonzo/test/test/Test/Cardano/Ledger/Alonzo/Serialisation/Tripping.hs#L114

also observes the serialization failure when run with the same dependencies as @nfrisby lists above.
