### ISSUE TITLE
API to get Plutus Script from Transaction

### ISSUE THREAD

**Issue by ducphanduyagentp** [IntersectMBO/cardano-ledger#2401]
Hi there!
I am working on a way to fetch the on-chain code from cardano-node. While some information can be retrieved like the UTxO by address, the Plutus Script is not, at the moment.

Can anyone shed some light on this matter?
Thank you!

**Comment by kikai-duydn** [comment]
Based on what I know, Plutus Script isn't stored in the UTXO. Only the hash of the script is stored in the UTXO. To get the actual script, you must trace back to the transaction.

**Comment by JaredCorduan** [comment]
Hi @ducphanduyagentp , I am sorry that this issue somehow didn't get noticed and answered until now!

This is not the kind of information that the ledger would ever store. The hashes of Plutus scripts are stored in the ledger, but the scripts are only ever revealed when a user uses a redeemer, at which time it does not make sense for the ledger to store anything. You should, however, be able to use [db-sync](https://github.com/input-output-hk/cardano-db-sync/blob/master/doc/schema.md#script) to get scripts which have been revealed.

**Comment by ducphanduyagentp** [comment]
OK thanks man
