### ISSUE TITLE
Inconsistencies between Alonzo formal specification and PlutusScriptApi.hs file of implementation

### ISSUE THREAD

**Issue by jmhrpr** [IntersectMBO/cardano-ledger#2406]
There are a number of small mistakes and inconsistencies between the Alonzo formal specification and the [PlutusScriptApi.hs](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/alonzo/impl/src/Cardano/Ledger/Alonzo/PlutusScriptApi.hs) file (or relating to) in the implementation.

1. The ordering of arguments in the definitions for the `runPLCScript` function are inconsistent between the formal spec (figure 6) and the implementation ([TxInfo.hs](https://github.com/input-output-hk/cardano-ledger-specs/blob/38850aa9ac042b5456e3285e9d6933dd9b9fb25e/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L364)).
2. The `getData` function in the implementation is named `getDatum` in the formal spec.
3. In the implementation the `collectTwoPhaseScriptInputs` function takes `EpochInfo` and `SystemStart` arguments but this is not reflected in the formal specification.
4. In Figure 7 (Scripts and their arguments) of the formal spec `evalTimelock` is missing an argument `vhks` (first argument).
5. PlutusScriptApi.hs contains an outdated comment before the `checkScriptData` function which states "This is called checkRedeemers in the Specification", which is no longer the case as the formal spec also uses the name `checkScriptData`.
6. In Figure 11 (UTXOW helper functions) of the formal spec the definition for the `checkScriptData` function reads `checkScriptData tx (sp, h) = \forall s, (h \mapsto s)...` but it seems the `\forall s,` may be a typo? ![image](https://user-images.githubusercontent.com/25673452/127879045-52ee5fc5-40a7-498c-a58d-b9e9568f2866.png)
7. Also in the formal spec definition of `checkScriptData` it reads `txrdmrs tx sp` but I think this should be `indexedRdmrs tx sp` (which is what the implementation uses).

There's also a typo in chapter 4.2: "In no datum is found..." -> "If no datum is found...".

Please let me know if I misunderstood anything! Cheers.

**Comment by WhatisRT** [comment]
Thanks! We're currently in the process of doing an internal audit, and I think all of these points except for the typo in 4.2 are already fixed or on my TODO list. I'll post a link to the PR here once it's up!

**Comment by WhatisRT** [comment]
I forgot about this issue, but I just went over this list and while a few things have changed in the implementation I think everything in this issue has been resolved properly.
