### ISSUE TITLE
Inconsistencies between Alonzo formal specification and implementation of UTXOS/UTXO rules

### ISSUE THREAD

**Issue by jmhrpr** [IntersectMBO/cardano-ledger#2424]
There are a number of potential minor inconsistencies/mistakes related to the (Alonzo) [UTXOS.hs](https://github.com/input-output-hk/cardano-ledger-specs/blob/febc1c3008a42a632ff5630c7793f8e987ec7546/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxos.hs) and [UTXO.hs](https://github.com/input-output-hk/cardano-ledger-specs/blob/febc1c3008a42a632ff5630c7793f8e987ec7546/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs) files and the corresponding contents of the Alonzo [formal spec](https://hydra.iohk.io/build/7172824/download/1/alonzo-changes.pdf).

**UTXOS.hs**
1. Figure 9 ("State update rules") of the formal spec reads `depositChange := deposits pp poolParams (txcerts txb)) - refunded` but I think this should use the `totalDeposits` function defined in the Shelley ledger spec and which is used in the implementation; that is, it should read `totalDeposits pp poolParams...`.
2. (Figure 9) It might be worth mentioning that the formal spec now names the state's deposited field `deposits` whereas the implementation is consistent with the `deposited` naming that was also used in the Shelley era. Intentional change?
3. (Figure 9) In the PPUP transition the signal should read `txup txb` not `txup tx`. This minor issue, accessing fields which are contained in transaction body by using an accessor on the transaction itself, is prevalent throughout the specification. For example, `collateral tx` and `collateral txb` are both used in Figure 10.

**UTXO.hs**
1. Figure 17 ("Value Size") states the function type of `utxoEntrySize` to be `TxOut -> MemoryEstimate` whereas the implementation is `utxoEntrySize :: TxOut -> Integer`. The Alonzo spec doesn't define the `MemoryEstimate` type but the ShelleyMA spec defines it as a Natural.
2. In Figure 4 ("Functions related to fees and collateral") the check which ensures the collateral provided covers the collateral percentage of the txfee achieves this by dividing the `(txfee * collateralPercent)` product on the RHS of the inequality by 100 and taking the quotient, whereas the [implementation](https://github.com/input-output-hk/cardano-ledger-specs/blob/12a0ef69d64a55e737fbf4e846bd8ed9fb30a956/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L280) multiplies the LHS by 100 resulting in a slightly different (more precise?) check.
3. In Figure 10 ("UTxO inference rules") [a `\to` arrow is used](https://github.com/input-output-hk/cardano-ledger-specs/blob/febc1c3008a42a632ff5630c7793f8e987ec7546/alonzo/formal-spec/utxo.tex#L675) between `a \in Addr_{bootstrap} \to bootstrapAttrsSize a \leq 64` but this should maybe be a `~\Rightarrow~` (for "implies")?
4. Figure 10 checks that `txnetworkid txb == NetworkId` but the `txnetworkid` field of the transaction body is optional and the [implementation](https://github.com/input-output-hk/cardano-ledger-specs/blob/febc1c3008a42a632ff5630c7793f8e987ec7546/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L432) allows for `txnetworkid` to equal nothing. Maybe Figure 10 should say something along the lines of "If `txnetworkid txb` is not equal to nothing _then_ `txnetworkid txb` must equal `NetworkId`"?
5. The recently renamed (in the implementation) `wppHash` and `hashWitnessPPData` will need to also be renamed in the formal spec.

Let me know if I misunderstood anything, thanks!

**Comment by WhatisRT** [comment]
UTXOS:

1. Fixed in #2448
2. We inherited that naming from the shelley spec, and it's used consistently among the specs I think. @JaredCorduan ?
3. We'll soon switch to a different way of doing accessors in the formal specs, which will get rid of this issue entirely

UTXO:
1. We specifically wrote this with the intention for the code to use a newtype. Should we spin this off into a new issue for the code @JaredCorduan ?
The rest should be fixed in #2448

**Comment by jmhrpr** [comment]
UTXOS 2. Looks like `deposited` was used in the Shelley formal spec (Figure 16) but was then changed to `deposits` in the ShelleyMA (Figure 4) and Alonzo (Figure 9) formal specs. The implementation of both Shelley and Alonzo uses `deposited`, but the ShelleyMA implementation uses `deposits`. Rest LGTM

**Comment by polinavino** [comment]
Done in https://github.com/input-output-hk/cardano-ledger-specs/pull/2418
