### ISSUE TITLE
Babbage Formal Spec

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2479]
We need a Babbage formal spec, covering:

* Protocol
   * a single VRF check
   * removal of protocol params: d and extra entropy
   * no overlay schedule / OBFT
   
* Ledger
   *  collateral return output (including the total collateral field)
   * [reference inputs](https://github.com/cardano-foundation/CIPs/pull/159)
   * [Inline datums](https://github.com/cardano-foundation/CIPs/pull/160)
   * [reference scripts](https://github.com/cardano-foundation/CIPs/pull/161)
   * fix one or both reward calculation warts from the Shelley spec errata.

**Comment by WhatisRT** [comment]
Also 2-phase validation for... 1-phase scripts. That naming scheme aged well^^

**Comment by michaelpj** [comment]
- Compression
- Inline datums

**Comment by yihuang** [comment]
Will babel fee supported in this era? And the multi-tier gas price system described by recent blog post?

**Comment by WhatisRT** [comment]
The list at the top is the full list of what's planned. So probably not.

**Comment by mark-stopka** [comment]
> Will babel fee supported in this era? And the multi-tier gas price system described by recent blog post?

Babel fees are certainly something requiring much more community dialogue, don't you think? How would you value those native tokens relative to ADA for instance?

**Comment by yihuang** [comment]
> > Will babel fee supported in this era? And the multi-tier gas price system described by recent blog post?
> 
> Babel fees are certainly something requiring much more community dialogue, don't you think? How would you value those native tokens relative to ADA for instance?

The liquidity market is done off-chain, what's needed on-chain is to support the grouped transactions, several invalid transactions (might contain negative ada output) can be valid after grouped as a bundle. Like a cheap way to do an atomic swap.

**Comment by WhatisRT** [comment]
Yes, so while it's clear what kind of changes would enable Babel fees, actually implementing those would require quite big changes to the ledger (and maybe even other parts of the system).
