### ISSUE TITLE
section on TxInfo is empty

### ISSUE THREAD

**Issue by CodiePP** [IntersectMBO/cardano-ledger#2482]
https://github.com/input-output-hk/cardano-ledger-specs/blob/bc963e0aca99a592bd88244b951bfd1f0cc81fdf/alonzo/formal-spec/txinfo.tex#L4

I was trying to find out which information is passed to scripts and found this section to be empty. Maybe copy the data structure from the implementation here?

**Comment by JaredCorduan** [comment]
I agree, this is important information for the spec. In the meantime, you can look at the data structure here:

https://github.com/input-output-hk/cardano-ledger-specs/blob/bc963e0aca99a592bd88244b951bfd1f0cc81fdf/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L381-L392

**Comment by polinavino** [comment]
Done in https://github.com/input-output-hk/cardano-ledger-specs/pull/2494
