### ISSUE TITLE
OutputTooBigUTxO / MaxTxSizeUTxO Warning

### ISSUE THREAD

**Issue by nnamdert** [IntersectMBO/cardano-ledger#2502]
Create a user warning prior to OutputTooBigUTxO / MaxTxSizeUTxO when minting (long asset name may cause issue)? so the receiving wallet does not lock up if the size is more than 16kb (or increase the max size). 

Or when attempting to send have a warning script in Yoroi or Daedalus be called before attempting the invalid transaction letting the sender know what the problem is and a possible way to resolve it.

Similar to the "you can't mint ada" code

The warning is preferable so the issue does not occur in the first place?

**Comment by JaredCorduan** [comment]
Asset names are restricted to at most 32 bytes.

I don't understand how a receiving wallet could be effected by an invalid transaction, it would never receive anything.

**Comment by nnamdert** [comment]
https://forum.cardano.org/t/possible-attack-method-what-am-i-missing/75412

See the link above as this individual had a similar issue.
I think it is more about "after" receiving the problem asset the wallet can't send the native assets. In effect, it locks the wallet.

**Comment by nnamdert** [comment]
Also on Page 22 here
https://hydra.iohk.io/build/5949624/download/1/shelley-ma.pdf

**Comment by nnamdert** [comment]
Here is another example of an issue where tokens were minted but now cannot be sent/

https://forum.cardano.org/t/i-minted-some-tokens-but-cant-send-outputtoobigutxo-maxtxsizeutxo/75336

**Comment by JaredCorduan** [comment]
Thank you for the context @nnamdert , that helps a lot. This sounds like a problem with the wallet, not the ledger or the protocol. The `OutputTooBigUTxO` check was put in place to prevent the creation of an output that was nearly the size of the max transaction size. The wallet may be attempting to combine outputs that are near the limit.
