### ISSUE TITLE
byron-spec-ledger: "duplicate instance declaration" error for "Hashable (Set a)" with hashable-1.3.4.1

### ISSUE THREAD

**Issue by runeksvendsen** [IntersectMBO/cardano-ledger#2551]
https://github.com/input-output-hk/cardano-ledger/blob/62ee15ed1d710395a765ceafabe4a2583342dcd1/eras/byron/ledger/executable-spec/src/Byron/Spec/Ledger/Update.hs#L235-L237 defines an orphan `Hashable` instance. This instance was introduced in 1.3.4.1 of `hashable`, thus requiring that we put a constraint of `< 1.3.4.1` on the `hashable` package at https://github.com/input-output-hk/cardano-ledger/blob/62ee15ed1d710395a765ceafabe4a2583342dcd1/eras/byron/ledger/executable-spec/byron-spec-ledger.cabal#L55

**Comment by JaredCorduan** [comment]
fixed by #2570

https://github.com/input-output-hk/cardano-ledger/pull/2570/files#diff-606a4950aff787440d647129526afc5c4b4ab27652fef400b3526f8f9b6c01e6R236-R238
