### ISSUE TITLE
Improve unfriendly error messages

### ISSUE THREAD

**Issue by benapetr** [IntersectMBO/cardano-ledger#2562]
https://github.com/input-output-hk/cardano-ledger/blob/master/libs/cardano-protocol-tpraos/src/Cardano/Protocol/TPraos/BHeader.hs#L143

```
              size
              ( ( \case
                    -- we are mapping a 'Proxy', so nothing can
                    -- go wrong here
                    GenesisHash -> error "impossible happend"
                    BlockHash h -> h
                )
                  <$> proxy
              )
```

seriously "impossible happend"? That's the error message you want to give to user? Either this error is possible and there should be a proper message without typos and with explanation of what has actually happened and what should be done to fix it, or if this is really impossible to happen, then this error condition shouldn't even be the part of code. Terrible error messages make for extremely awful user / admin experience.

**Comment by JaredCorduan** [comment]
This error is impossible. Note that `fmap` for Proxy does not actually use the function `f: a -> b`, it just transforms the phantom type. The use of `error`, however, can be avoided, and I agree is better.
