### ISSUE TITLE
fail phase 1 validation on the presence of byron addresses

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2612]
Byron addresses are current ignored by Plutus, in the sense that they are not a part of the context passed to Plutus. We would prefer to have the transaction fail phase 1 validation in the event that a transaction contains both a plutus script and any byron addresses (both inputs and outputs).

**Comment by michaelpj** [comment]
I suggest that this also goes with a policy change for the `TxInfo` creation code: any time it sees something it can't deal with (i.e. the various cases that return `Nothing` currently), it should fail phase 1 validation instead of ignoring it.
