### ISSUE TITLE
important to define the key names for costModel

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#2634]
The cost model is used for computing script integrity hash, which is done by sorting the cost model values lexicographically by key names. The key names are unknown until we see find the key names as used by the cli when querying proto params. Since script integrity hash is also computed in other languages, it is required to define the key names in the CDDL spec.

https://github.com/input-output-hk/cardano-ledger/blob/01e362881823e30cf69907c65b038dc34f9bdd20/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L312

**Comment by ashisherc** [comment]
cc: @JaredCorduan

**Comment by JaredCorduan** [comment]
I agree, there should be a comment in the CDDL spec which provides this information.
