### ISSUE TITLE
How to interpret this figure in the ledger spec

### ISSUE THREAD

**Issue by locallycompact** [IntersectMBO/cardano-ledger#2641]
Hi, can someone explain how to interpret rule (3) in figure 6 here? The above specification indicates that the turnstile relation has four arguments, but this one only has two. How is this a valid relation?

![Screenshot_20220202-122002](https://user-images.githubusercontent.com/1267527/152152681-f52c07bb-bf61-45bb-80e6-3308cedee44d.jpg)

**Comment by JaredCorduan** [comment]
I see that is from the Byron ledger spec. Equation 3 looks like an initialization rule, not a transition rule. But I do not see any explanation for what an "initialization rule" is in either this spec of the [document](https://hydra.iohk.io/job/Cardano/cardano-ledger-specs/semanticsSpec/latest/download-by-type/doc-pdf/small-step-semantics) explaining how to read the specs. So I guess it an abuse of notation on `UTXO`, I can definitely see how this could be confusing. @dnadales or @nc6 could confirm.

**Comment by dnadales** [comment]
That rule explains how to obtain an initial state from the environment. In particular, it tells how the initial UTxO state is constructed. It's a pity this is not explained in the document that Jared mentioned though.

**Comment by JaredCorduan** [comment]
Development of Byron code has been frozen and only potential security fixes will be applied in the future. Note that only Byron ever used the initialization rules.
