### ISSUE TITLE
Question about `txInfoData`

### ISSUE THREAD

**Issue by L-as** [IntersectMBO/cardano-ledger#2649]
Are there any restrictions on what can be put in `txInfoData`? Can we put arbitrary extra data into it for use in scripts?

**Comment by JaredCorduan** [comment]
No, there is no way to put any extra/auxiliary data into the transaction context. Any data that you want to pass to a Plutus script should be passed via the redeemer.

**Comment by L-as** [comment]
Would you be open to removing this restriction?

**Comment by L-as** [comment]
This would be a possible alternative to adding something like `dataHash :: BuiltinData -> BuiltinByteString` to UPLC as a built-in.

**Comment by JaredCorduan** [comment]
@L-as in general, https://cardano.stackexchange.com is a better place to ask questions, the issues here are really for the ledger team to track work. And CIPs are the better place to propose new ideas: https://cips.cardano.org

I think it is more likely that we would add a builtin hash function for Plutus than that we would allow data in addition to the redeemer, just for the purposes of getting a hash. But this is just my first impression, take it with a grain of salt. :)

**Comment by L-as** [comment]
Thanks! Considering we seemingly already have the approval for adding `dataHash`, I'll just do that.

Wasn't sure where to post this initially, didn't know there was an active stack exchange.

**Comment by JaredCorduan** [comment]
Np, glad you are interested in Plutus and how we can make it better!

**Comment by JaredCorduan** [comment]
@L-as you'll  be happy to see this: https://github.com/cardano-foundation/CIPs/pull/218 :)
