### ISSUE TITLE
How to obtain EpochInfo?

### ISSUE THREAD

**Issue by v0d1ch** [IntersectMBO/cardano-ledger#2655]
I am trying to call a function `evaluateTransactionExecutionUnits` from [here](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Tools.hs#L114) 

That function takes in as a parameter `EpochInfo` and I am having some problems creating a value of that type. I found a function `epochInfo` [here] (https://github.com/input-output-hk/cardano-ledger/blob/master/libs/cardano-ledger-core/src/Cardano/Ledger/BaseTypes.hs#L621) . This one takes in a `Genesis` parameter which is also hard to construct (looks like it might be coming in from external file? may be we can query the blockchain to get that info?). There is also `fixedEpochInfo` but I am not sure where exactly to get the parameters

How can we improve on this? I am willing to either work on this (if there is some work needed to be done) or improve the docs.

**Comment by JaredCorduan** [comment]
Hi @v0d1ch , thank you for your willingness to help out! The queries needed to get this information actually already exist, you just have to know how to stitch the information together.

You can follow along here to see how the cardano-cli does it (`eInfo` is what you want):

https://github.com/input-output-hk/cardano-node/blob/272aa77fd26af37d2040b303074b3ca47edb4bae/cardano-cli/src/Cardano/CLI/Shelley/Run/Query.hs#L408-L418

I suspect that a standalone function to compute the epoch info would be helpful in several places.

**Comment by v0d1ch** [comment]
Thanks @JaredCorduan ! I need to update cardano-ledger version in my project since this piece of code doesn't exist in the version I am using.
