### ISSUE TITLE
Plutus script ledger event

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2659]
When a Plutus script fails, the predicate failure includes enough information to re-run the script with all the arguments passed to it. See [here](https://github.com/input-output-hk/cardano-ledger/blob/2048cd4679ef3155d88a445e0f818abad09a0827/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L608).

It would also be very helpful to be able to re-run _succeeding_ Plutus scripts.

Let's create a new ledger event which provides the same `PlutusDebug` information for successful scripts. Probably somewhere around here: https://github.com/input-output-hk/cardano-ledger/blob/2048cd4679ef3155d88a445e0f818abad09a0827/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/PlutusScriptApi.hs#L264

**Comment by michaelpj** [comment]
Maybe we could just have one event for script evaluations that includes whether they succeeded or failed? Or maybe just the evaluation result (I could imagine that even having the error for failures would be interesting).
