### ISSUE TITLE
New babbage min-utxo calculation

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2682]
Figure 4 of the Babbage spec introduces a new calculation for the minimum ada needed inside a given utxo.

**Comment by WhatisRT** [comment]
If you want to, `coinsPerUTxOWord` can be renamed to `coinPerUTxOByte` and the division by 8 be dropped. But then we need to make sure the parameter is adjusted accordingly at the HF

**Comment by JaredCorduan** [comment]
resolved by #2733 (except for the renaming `coinsPerUTxOWord` -> `coinPerUTxOByte`
