### ISSUE TITLE
babbageMissingScripts problems

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2719]
`babbageMissingScripts` has very strange behavior in the spec, it switches on the major protocol version but is only used in Babbage.

Moreover, the corresponding check in the spec actually needs to follow the `needed ⊆ provided ⊆ allowed` pattern. see #2705.

**Comment by WhatisRT** [comment]
Sadly this isn't actually the pattern, since the scripts in the witness set should be nailed down exactly, which this pattern doesn't do. The actual pattern is `provided = needed - referenced`, see UTXOW in https://github.com/input-output-hk/cardano-ledger/pull/2723

**Comment by JaredCorduan** [comment]
resolved by #2733
