### ISSUE TITLE
Handling of broken Alonzo address missing from the spec

### ISSUE THREAD

**Issue by SebastienGllmt** [IntersectMBO/cardano-ledger#2729]
# Background

On August 28th, cardano-node 1.29.0 was released. Shortly after, on Sept 5th, [this transaction](https://cardanoscan.io/transaction/369826b2f60b443d27966d222fa5bedc6b900326b77a09f15473d77f5ef2871c) which contains an [invalid address](https://cardanoscan.io/address/015bad085057ac10ecc7060f7ac41edd6f63068d8963ef7d86ca58669e5ecf2d283418a60be5a848a2380eb721000da1e0bbf39733134beca4) was created.

Information about this address:
1. Its bech32 representation is `addr1q9d66zzs27kppmx8qc8h43q7m4hkxp5d39377lvxefvxd8j7eukjsdqc5c97t2zg5guqadepqqx6rc9m7wtnxy6tajjvk4a0kze4ljyuvvrpexg5up2sqxj33363v35gtew`
2. Its binary representation is `015bad085057ac10ecc7060f7ac41edd6f63068d8963ef7d86ca58669e5ecf2d283418a60be5a848a2380eb721000da1e0bbf39733134beca4cb57afb0b35fc89c63061c9914e055001a518c7516`
4. It's a base address address of type <keyhash, keyhash> according to its header
5. The address fails to be parsed by [cardano-address](https://input-output-hk.github.io/cardano-addresses/demo/)
6. The complete txbody this tx is contained in is as follows: `a40083825820bf4f8f6287993e17f785c949ef287416ba784198bb0ee12b2c7720cbffecd26f0082582052cf971bee4ba1b4e3b32b762e0bc3f7af83700bc8897eddbd77bd425dd28e8300825820bf4f8f6287993e17f785c949ef287416ba784198bb0ee12b2c7720cbffecd26f01018282584e015bad085057ac10ecc7060f7ac41edd6f63068d8963ef7d86ca58669e5ecf2d283418a60be5a848a2380eb721000da1e0bbf39733134beca4cb57afb0b35fc89c63061c9914e055001a518c75161a035377d082583901f4e9e89cc628b9204fd6e2f4ae3e875aa0591fc2eb45b721520d2d22f4e9e89cc628b9204fd6e2f4ae3e875aa0591fc2eb45b721520d2d221a2c651d70021a00031570031a05f5e100` but it may be good to verify this tx body with some different tool to make sure this isn't an chain indexer issue (it could be that Oura and CardanoScan's indexer both happen to have the same bug and mangle the address info in the same way)
7. If you remove the extra bytes from this address, you end up with the address `addr1q9d66zzs27kppmx8qc8h43q7m4hkxp5d39377lvxefvxd8j7eukjsdqc5c97t2zg5guqadepqqx6rc9m7wtnxy6tajjq6r54x9`

The next node version (1.30.1) doesn't mention this bug being resolved, so I'm not sure if it sill exists or if it was just left out of the changelogs

# What to do?

- Update the ledger spec to document how this address should be handled
- Update cardano-address to parse this address

**Comment by lehins** [comment]
@SebastienGllmt Thank you for reporting this issue. We are aware of this problem and a fix is on the way very soon!

**Comment by SebastienGllmt** [comment]
Just FYI there appears to be 4 addresses on mainnet affected by this

| address                                                                                                                                  | extra bytes                                                                                                                         |
|------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| addr1q9d66zzs27kppmx8qc8h43q7m4hkxp5d39377lvxefvxd8j7eukjsdqc5c97t2zg5guqadepqqx6rc9m7wtnxy6tajjvk4a0kze4ljyuvvrpexg5up2sqxj33363v35gtew | [203, 87, 175, 176, 179, 95, 200, 156, 99, 6, 28, 153, 20, 224, 85, 0, 26, 81, 140, 117, 22]                                        |
| addr1q9d66zzs27kppmxxgdzs5gp34etxla3m89g48n4z6q3m5ecw82xn7xy064e7e2zg5guqadk40nmf3057kagdzjqk7hs3840550lqg79jys0qz68rewjsqx3zc9dpzuurrhe | [19, 213, 244, 163, 254, 4, 120, 178, 36, 30, 1, 104, 227, 203, 165, 0, 26, 34, 193, 90, 17]                                        |
| addr1v8ll5vf492k9g9v7ex3w32zernw535g6vsp7x7fhxpq2ptsjdemn2ve4vum8vumsxaurweng0pc8zvnsw3ekswt8ddeqj7x47t                                  | [18, 110, 119, 53, 51, 53, 103, 54, 118, 115, 112, 55, 120, 55, 102, 104, 120, 112, 113, 50, 112, 116, 115, 104, 57, 103, 107, 114] |
| addr1v92fkk3qu3y68cu5ka38qhmyhx3xhxgpxqp6907m5guevlqqjd7xgj                                                                              | [0]                                                                                                                                 |
