### ISSUE TITLE
Move some code from Shelley to Core

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2742]
There is a lot of code inside https://github.com/input-output-hk/cardano-ledger/tree/master/eras/shelley/impl which should be moved into https://github.com/input-output-hk/cardano-ledger/tree/master/libs/cardano-ledger-core

**Comment by aniketd** [comment]
Notes from discussion:
- UTxO
- PoolParams
- EpicBoundary (hold off until updates are decided)
- Orphans

**Comment by JaredCorduan** [comment]
these two from EpochBoundary seem good:

* `Cardano.Ledger.Shelley.EpochBoundary.SnapShots`
* `Cardano.Ledger.Shelley.EpochBoundary.SnapShot`

more ideas:

* `Cardano.Ledger.Shelley.LedgerState.Types.AccountState`
* `Cardano.Ledger.Shelley.PoolParams.PoolMetadata`

**Comment by aniketd** [comment]
Can we close this one too, as the collective recent efforts of @TimSheard @lehins @JaredCorduan and earlier smaller PRs by others have addressed everything in this issue.

#3202 #3239 #3175 #3110 #3109 #3059

**Comment by JaredCorduan** [comment]
I think we can indeed close it. (we might move other stuff later, but we can do that as it comes up without this issue).
