### ISSUE TITLE
Remove OnePhaseFailure from FailureDescription

### ISSUE THREAD

**Issue by Jimbo4350** [IntersectMBO/cardano-ledger#2749]
This constructor isn't actually used to render errors so it should be removed

**Comment by JaredCorduan** [comment]
thanks @Jimbo4350 ! I should have removed that constructor earlier when I rendered it useless.  backstory is here: https://github.com/input-output-hk/cardano-ledger/pull/2670#discussion_r843345979

**Comment by JaredCorduan** [comment]
fixed by 7e37829a0f6bf1e6bf85a5e1b99babd74b701b13
