### ISSUE TITLE
Min ada requirement - Babbage

### ISSUE THREAD

**Issue by alessandrokonrad** [IntersectMBO/cardano-ledger#2765]
I'm trying to undertand the min ada calculation for a utxo in Babbage.
According to the specs it's:  `(serializedSize of output * coinsPerUTxOWord + 7) / 8`

I see the fomula being used here to validate utxos: https://github.com/input-output-hk/cardano-ledger/blob/88c0fe663720c5ef40f6fd00b9d331de81a6a7cb/eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxo.hs#L268

However a few lines above, where the output should get serialized, I see only the value field is actually serialized:
https://github.com/input-output-hk/cardano-ledger/blob/88c0fe663720c5ef40f6fd00b9d331de81a6a7cb/eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxo.hs#L257

I'm not sure if I'm missing something, but this would imply to me, that adding inline datums, datum hashes or script refs, wouldn't cost anything.

Any help appreciated, thanks!

**Comment by JaredCorduan** [comment]
at first glance, that does look like a bug. thank you for raising this @alessandrokonrad !
