### ISSUE TITLE
Vasil protocol parameters / genesis configuration

### ISSUE THREAD

**Issue by KtorZ** [IntersectMBO/cardano-ledger#2779]
Will there be any new / altered protocol parameters or genesis configuration for the upcoming Vasil hard-fork (talking about parameters themselves / their semantic here, not about a change in their values)? 

Should there be any, would it be possible to document them as a CIP _before_ the hard-fork is actually submitted to the network, in a similar fashion to [what was done for Alonzo's parameters](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0028#readme)?

Thanks a lot :pray:

**Comment by JaredCorduan** [comment]
The Babbage era does not introduce any new protocol parameters (so, in particular, there is no Babbage config). There is one small semantic change which will need to be accounted for in the HFC translation from Alonzo, namely [coinsPerUTxOWord](https://github.com/input-output-hk/cardano-ledger/blob/ea563c6f036da118954723e7d0788b66939d6ab2/eras/babbage/impl/src/Cardano/Ledger/Babbage/PParams.hs#L118) is changing to represent lovelace per byte (not word). Does this merit a CIP?

(Edit: I just checked, we haven't actually made this change yet, the semantics are [still tied to 8 bytes](https://github.com/input-output-hk/cardano-ledger/blob/ea563c6f036da118954723e7d0788b66939d6ab2/eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules/Utxo.hs#L266), but I think we still want to change this...)

**Comment by KtorZ** [comment]
Thanks @JaredCorduan :+1: 

> Does this merit a CIP?

Arguably yes, we want a CIP for all era parameters changes; though if that's the only change it can be very short :)
Shall I keep this issue open as a "reminder" and close it once we've got the CIP out, Kevin is usually doing this so that may already be on his TODO list.

**Comment by JaredCorduan** [comment]
yea, let's keep it open, I'm excited to get the chance to embrace the CIP process more myself. thanks for opening this!

**Comment by KtorZ** [comment]
(for the record, related previous CIPs)

https://github.com/cardano-foundation/CIPs/tree/master/CIP-0009#readme

https://github.com/cardano-foundation/CIPs/tree/master/CIP-0028#readme

**Comment by JaredCorduan** [comment]
https://github.com/cardano-foundation/CIPs/pull/265

**Comment by JaredCorduan** [comment]
I'm going to close this issue here since I have a PR up for the CIP.
