### ISSUE TITLE
Babbage - missing PlutusV2 changes in cddl for witnessing v2 scripts?

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#2798]
https://github.com/input-output-hk/cardano-ledger/blob/76ae29dc6f73ee4707f3cf883a8af279501d798f/eras/babbage/test-suite/cddl-files/babbage.cddl#L281

**Comment by JaredCorduan** [comment]
yes indeed, thank you @ashisherc ! :pray:
