### ISSUE TITLE
Babbage - CDDL - does script_ref type has a glitch?

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#2820]
https://github.com/input-output-hk/cardano-ledger/blob/033b0e048c4caca2c7f642c18cbda51e4d003d8a/eras/babbage/test-suite/cddl-files/babbage.cddl#L412

currently, the script_ref is defined as below,
```
script_ref = #6.24(bytes .cbor script)

script = [ 0, native_script // 1, plutus_v1_script // 2, plutus_v2_script ]
```

Should it have been defined as below?

```
tagged_native_script = #6.24(bytes .cbor native_script)
tagged_plutus_v1_script = #6.24(bytes .cbor plutus_v1_script)
tagged_plutus_v2_script = #6.24(bytes .cbor plutus_v2_script)

script_ref = [ 0, tagged_native_script // 1, tagged_plutus_v1_script // 2, tagged_plutus_v2_script ]
```

**Comment by ashisherc** [comment]
@JaredCorduan can you please take a look?

**Comment by JaredCorduan** [comment]
It's not necessarily a glitch, but I can imagine that the proposed change is more convenient for people. I'll need to investigate to see if there was a strong reason for it to be the way it is now. thanks for bring this up!

**Comment by JaredCorduan** [comment]
unfortunately there is not time to make this change before the Vasil HF, sorry.

**Comment by ashisherc** [comment]
No worries, thank you for looking into it!

**Comment by JaredCorduan** [comment]
anytime, sorry we didn't get to dig into this earlier.
