### ISSUE TITLE
Faulty assumption that every reference script is executed

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2851]
Both `collectTwoPhaseScriptInputs` and `evaluateTransactionExecutionUnits` make the assumption that every reference script inside of every transaction input (both regular and reference) will be executed. The former assumes it for checking for cost models, the latter for gathering transaction contexts.

**Comment by jmhrpr** [comment]
I did see this (in the collectTwoPhaseScriptInputs case) but didn't see it as much of any issue unless I misunderstood something. Just that yes, the cost models for the reference script must be available, which seemed reasonable enough if cost models will never be removed (?) and that we can only create reference scripts for Plutus versions which exist and thus have a cost model. Didn't spot the latter case.

But agree it's good to clear it up.

**Comment by JaredCorduan** [comment]
Thanks @jmhrpr . The first issue, `collectTwoPhaseScriptInputs`, is definitely much less pressing. But I think it's at least abstractly problematic. _If_ we did remove the Plutus V1 cost model, we do not want to render unspendable every transaction output that contains a V1 Plutus reference script, it's much better that folks can remove them. (That said, I don't think we would ever actually remove the V1 cost model :shrug: ).

Note that V1 reference scripts are already a weird thing. They cannot be used to actually authorize anything directly, any transaction that needs to run a V1 script in the Plutus evaluator will by rejected due to a transaction context failure (the V1 context does not know about reference scripts, and we chose to fail hard instead of silently ignore unknown things). All you can do with a V1 reference script is view it from inside a V2 Plutus script (via a reference input).
