### ISSUE TITLE
CostModel data definition has non-strict fields and wrong NoThunks instance

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/cardano-ledger#2853]
I ran the `db-analyser` `noThunks` check and found one thunk, here:

https://github.com/input-output-hk/cardano-ledger/blob/51d97a7faeec32f3825a21d775ca70b6a05fd092/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs#L206

I don't think this is cause for alarm, since it's not involved in any iteration or risks retaining much, as far as I anticipate. However, we should fix it, if only so the `noThunks` test passes.

1) Would it be fine to mark the parameters `Map` and the `EvaluationContext` as strict?

2) This instance need not use `InspectHeap`: you should instead `deriving (Generic)` on `CostModel` and just write `instance NoThunks CostModel`.

https://github.com/input-output-hk/cardano-ledger/blob/51d97a7faeec32f3825a21d775ca70b6a05fd092/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Scripts.hs#L241

3) Moreover, if the `Map` and/or `EvaluationContext` thunks are intentional, then we'll need to handwrite the `wNoThunks` in that instance to not check those arguments for thunks.

**Comment by JaredCorduan** [comment]
@Jasagredo kindly pointed out that there still seems to be an unexpected thunk in the `EvaluationContext`. I'll re-open this issue.

**Comment by JaredCorduan** [comment]
See https://github.com/input-output-hk/plutus/issues/4687
