### ISSUE TITLE
Show and Hash for MemoBytes

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#2882]
It was brought to our attention by @sevanspowell that it is possible for two transactions to not be equal, while the string produced by the `show` function are identical. 

> i.e. `show txA == show txB` but `txA /= txB` 

This is actually true due to the serialization, which does not participate in the Show instance. In fact this is totally legit since there is no law in Haskell that regulates that `show txA == show txB <=> txA == txB` property holds for all types. Nevertheless, I do agree that this is inconvenient, at least for the purpose of testing/debugging.

It is done this way for a very important reason: we must preserve the binary serialization in the original form to ensure cryptographic integrity. The bit of context that is important that there is no normal/canonical form for CBOR serialization. Whenever we get a valid transaction over the wire, it could have been constructed using some other CBOR implementation and thus can have slightly different binary representation from what it would be if we where to construct it and serialize it using ledger code. In other words: it is absolutely possible and valid to have to transactions be "sematically" the same but not equal. Whenever we compute the hashes of such transactions they will be different, thus different transaction, despite having exactly the same values in a Haskell Tx type.

The best solution I think is to also display the hash of the thing that is being memoized in hex format. This will help us with:

* Avoiding hash recomputation whenever we need it more than once
* Reduce number of bytes copied (each hash computation requires an extra buffer copy to pinned memory)
* Account for difference in binary representation when displaying the thing that is being memoized
* It would have also helped us fixing the `Ord` instance, however we decided to simply remove it in #2881 

So the proposed solution is to:

__Disclaimer__ - this was in browser programming, so it is bound to be incomplete or even incorrect:

* Move `MemoBytes` into `cardano-ledger-core` 
* Add hash into the type next to the bytes (must be lazy):
```haskell
data MemoBytes t era = Memo
  { memoType :: !t era,
    memoBytes :: ShortByteString,
    memoHash :: SafeHash (Crypto era) (MemoHashIndex t)
  }

type family MemoHashIndex (t :: Type -> Type) :: Type

-- | Smart constructor
mkMemoBytes :: forall era t. (SafeToHash bs, Era era) => t era -> BSL.ByteString -> MemoBytes t era
mkMemoBytes t bsl = 
  MemoBytes t (toShort bs) (makeHashWithExplicitProxys (Proxy @(Crypto era)) (Proxy @(MemoHashIndex t)) bs)
  where
    bs = toStrict bsl
```

* Move `hashAnnotated` function into `HashAnnotated` class, so it can be customized

Then instances would look something like this:
```haskell
data TxBodyRaw era = TxBodyRaw
  { _inputs :: !(Set (TxIn (Crypto era))),
  ...
  }
newtype TxBody era = TxBodyConstr (MemoBytes TxBodyRaw era)
  deriving newtype (SafeToHash)

type instance MemoHashIndex TxBodyRaw = EraIndependentTxBody

instance (c ~ Crypto era) => HashAnnotated (TxBody era) EraIndependentTxBody c where
  hashAnnotated (TxBodyConstr mb) = memoHash mb
```

**Comment by JaredCorduan** [comment]
Fantastic breakdown, thank you @lehins ! Also, many thanks to @sevanspowell for going out of his way to help us understand the problem.

I heartily endorse the solution proposed here.
