### ISSUE TITLE
Will this repository drop dependency on cardano-prelude?

### ISSUE THREAD

**Issue by locallycompact** [IntersectMBO/cardano-ledger#2886]
Hi, there's an open merge request for cardano-base to drop the dependency on cardano-prelude when babbage hits. https://github.com/input-output-hk/cardano-base/pull/280

Will this repository do the same? I ask because I would like to work on making cardano-ledger compatible with ghc-9.2, and so this is relevant (as it gets rid of protolude).

**Comment by JaredCorduan** [comment]
yes indeed, the issue is here: https://github.com/input-output-hk/cardano-ledger/issues/1676
