### ISSUE TITLE
Create a parsable PR template

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/cardano-ledger#2900]
We should make a PR template and a parser to automate some of the manual labor and enforce contribution rules. The idea is that whenever someone makes a pull request, they add the changelog entries into the PR description. If we have a template, then we can write a GitHub action that scrapes these entries from the description and adds them to the changelog once the PR is merged.

## Template
```

# Description
<!--
Describe what your PR does in this section. At least explain why this change
is necessary and briefly explain how your changes solve the problem.
-->

# Changelog
<!--
Write changelog entries here. The entries should be formated like this:
  - Added: <message>
  - Changed: <message>
  - Deprecated: <message>
  - Removed: <message>
  - Fixed: <message>
  - Security: <message>

These entries will get added to the changelog once the PR is merged.

For more guidelines, see: https://keepachangelog.com/en/1.0.0/
-->

 - Added: <!-- Description of the feature -->
 - Changed: <!-- Description of what changed -->
   <!-- etc. -->

```

## Changelog generation

When somebody makes a pull request, they fill out the template, for example like this:
```

# Description
This PR adds foo and removes bar, because reasons. Bla bla bla.

# Changelog

 - Added: foo to baz
 - Removed: bar from baz

```

Now once the PR gets merged, a program takes the entries from the `Changelog` section and generates a new changelog based on this and the previous PRs.

```
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
### Added
 - something interesting
 - foo to baz
### Removed
 - this and that
 - boring stuff
 - bar from baz
```

## Semantic versioning

Another idea would be to make it possible to mark some changelog entries as breaking, for example with a bang:
```
# Changelog
 - Removed!: old broken code
```

Now we can use that information to decide, which version numbers to bump for the next release.

## Existing solutions

There are some pre-made GitHub actions that are trying to do what I described here, but I haven't had any experience with them.

 - https://github.com/mikepenz/release-changelog-builder-action

## Tasks

- [ ] Create a PR template
- [ ] Create a GitHub action that updates the changelog based on entries in pull request descriptions.

**Comment by Soupstraw** [comment]
I've created a repo for parsing PR templates: https://github.com/Soupstraw/template-parser

There's still a lot of work to do to integrate that into CI. I think the best approach would be to create a GitHub bot that listens for PR events and then collects all the changelog entries. It would then commit the new changelog at a time where we usually don't work on the repo.

**Comment by lehins** [comment]
I think we should stick to the manual approach. It has proven to work great so far and I don't think we want this automation anyways, since our changelogs are package specific
