### ISSUE TITLE
Helper function - construct a transaction output with mimimun lovelace

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2905]
Write an era-generic function
```
minLovelaceFixedPoint :: Core.PParams era -> Core.TxOut era ->  -> Coin
``` 

perhaps with a better name, such that:

for all `pp :: Core.PParams era` and `out :: Core.TxOut era`, if `minLovelaceFixedPoint pp out = x`, then:
* `evaluateMinLovelaceOutput pp (setLovelace x out) = x`.

In other words, `minLovelaceFixedPoint` computes the fixed point of `f z = evaluateMinLovelaceOutput pp (setLovelace z out)`. Note that `evaluateMinLovelaceOutput` is defined [here](https://github.com/input-output-hk/cardano-ledger/blob/b076a648dd7b20e85c20fa6f0446bfa3d47b261b/eras/shelley/impl/src/Cardano/Ledger/Shelley/API/Wallet.hs#L530) (and `minLovelaceFixedPoint` should probably also be a class member of `CLI`).

**Comment by JaredCorduan** [comment]
`setMinCoinSizedTxOut` from #3008 computes the fixed point given the protocol parameters and a transaction output, and returns the transaction output with the lovelace modified to the fixed point.

**Comment by Soupstraw** [comment]
Resolved according to previous comment
