### ISSUE TITLE
Account for deprecated `testProperty` function

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#2910]
As of `tasty-hedgehog-1.2.0` the function [`testProperty`] function has been deprecated. We use it a lot throughout the codebase.

We need to:
- [ ] - Remove all `-Wno-deprecations` that were added in #2908
- [ ] - Use new function `testPropertyNamed`
- [ ] - Add a helper function for tests that already have short names for properties, to avoid duplicating names:
```haskell
testNoNameProperty propName@(PropertyName name) = testPropertyNamed name propName
```

**Comment by Soupstraw** [comment]
Resolved by #2924
