### ISSUE TITLE
Optional datum documentation

### ISSUE THREAD

**Issue by Jimbo4350** [IntersectMBO/cardano-ledger#2919]
Optional datums were introduced in the Alonzo era however information regarding them is scarce, in particular what is considered a valid optional datum. This needs to be added to the spec.

**Comment by catch-21** [comment]
We should settle on a single name when referring on this type of datum. I've seen "optional" (ledger spec), "extra" (CIP-31 & CIP-32) and "embedded" (node-cli).  I vote to align on "optional".

**Comment by JaredCorduan** [comment]
We have called these "supplemental" datums everywhere in the haskell implementation.

To be clear, in the spec we require:
```
dom(txdats txw) ⊆ inputHashes ∪ {h | ( , , h) ∈ txouts tx }
```

where `inputHashes` correspond to the datums that we _must_ have, and the ones in the transaction outputs are supplemental. I think it is the name alone that has caused confusion, the spec definitely does explain them:

> The only datums included in a transaction have hashes that are either in a UTxO corre-
sponding to a transaction input, or in a transaction output. The output datums are for
communication only, and are therefore optional, hence the use of subset equality. No
additional datums are permitted.
