### ISSUE TITLE
`validPlutusdata` dead code?

### ISSUE THREAD

**Issue by L-as** [IntersectMBO/cardano-ledger#2940]
https://github.com/input-output-hk/cardano-ledger/blob/83b9973810f4e15ce24d5efc8f1debeb5d73b729/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L781 doesn't seem to be used anywhere.

**Comment by JaredCorduan** [comment]
indeed, looks like dead code to me too
