### ISSUE TITLE
Instances needed for proper master key rotation

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2988]
In input-output-hk/ouroboros-network#2963, an the `TranslateEra LedgerState` instance was used to rotate the master keys. This should suffice for mainnet, and other networks that begin in the Byron era, but questions remain about Shelley-only networks. In particular, do we need instances for `CanStartFromGenesis` and `AdditionalGenesisConfig`, and do we need to translate `ShelleyGenesis` via `TranslateEra ShelleyGenesis`.

**Comment by JaredCorduan** [comment]
The ledger does not need to use `TranslateEra ShelleyGenesis` to rotate the master keys, we have a plan for consensus that will let us get rid of these instances in general (see https://github.com/input-output-hk/ouroboros-consensus/issues/409).

We still want to add a `CanStartFromGenesis ConwayEra` instance, though, where `AdditionalGenesisConfig` is something isomorphic to `(AlonzoGenesisConfig, ConwayGenesisConfig)`. The instance is responsible for converting a Shelley ledger state directly into a Conway ledger state.

**Comment by Soupstraw** [comment]
There already seems to be a `CanStartFromGenesis` instance for `ConwayEra` ([added here](https://github.com/input-output-hk/cardano-ledger/commit/c3a46e04244404261bb7fddc2629ddb0729c7927#diff-e106c7b5b8a971b311fc101be676dcc1a5b13d1111f36a070d7699c6e68b1ab7R51))

**Comment by JaredCorduan** [comment]
Ah, you are right @Soupstraw . The question still remains, though, if we have the correct behavior.

The current `CanStartFromGenesis` for conway is potentially a source for confusion. We are using the conway genesis to override the master keys in the shelley genesis. So if you are starting in conway (which is what the `CanStartFromGenesis` class is used for), the shelley master keys are entirely un-used. Alternatively, `CanStartFromGenesis` for conway could forgo the conway genesis altogether, and just use the shelley genesis to set the values for conway. I'm not sure which is less confusing. Maybe we could assert that precisely one of the two is non-empty (or that they agree)?

**Comment by JaredCorduan** [comment]
A lot has changed since I made this issue, it is not really relevant anymore. We will still be doing master key rotation, but in a much different way.
