### ISSUE TITLE
Bring all cabal files up to date

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#2999]
Things like year in the copyright, maintainer email, author, description in all of the cabal files in the repo are outdated. This ticket tracks a task to go through all of them and bring them up to date.

Please comment on this ticket what the correct information should be and the assignee will take care of the update.

**Comment by JaredCorduan** [comment]
@kevinhammond recommend that we be consistent with the packages in the cardano-node repository with respect to the maintainer email and author:

```
author:                 IOHK
maintainer:             operations@iohk.io
```

**Comment by aniketd** [comment]
If https://github.com/input-output-hk/cardano-ledger/pull/3023 addressed this issue, we can close it? @lehins I wonder if there are any more issues with `cabal` files, like `unused-packages`, etc. that might be worth addressing?

**Comment by Soupstraw** [comment]
#3024 did not add good descriptions to the packages, but that's something that requires a good knowledge of the codebase.

**Comment by lehins** [comment]
@aniketd There might be. If you wanna go through and inspect all cabal files and find (and potentially fix) any oddities then it will definitely be great thing to do regardless if you find any issues there or not

**Comment by aniketd** [comment]
@lehins @JaredCorduan I think that given the recent changes to all cabal files, including the enforcement of formatting on CI, this ticket stands finished?

**Comment by JaredCorduan** [comment]
thank you for all your work on this @aniketd ! :raised_back_of_hand:
