### ISSUE TITLE
Make the CI abort actions on older commits when a new commit gets pushed

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/cardano-ledger#3037]
Right now the CI seems to continue running actions on older commits when I push newer commits to a PR branch. This results in a lot of spam in my notifications and also probably clogs up the CI job action queue. 

It might be a good idea to halt all previous actions once a new commit gets added, so that the actions will only be run on the latest commit in a PR.

**Comment by lehins** [comment]
Fixed in #3244
