### ISSUE TITLE
Check UTxO HD assumption on size of values set needed when applying rules

### ISSUE THREAD

**Issue by dnadales** [IntersectMBO/cardano-ledger#3105]
During the design of UTxO HD we made the following assumption

```
No large set of values needs to be brought from disk when applying rules (slot tick or block application).
```

If the above assumption is wrong, then we need to redesign consensus and or ledger to work around this. 

Furthermore, for future versions of UTxO HD: if a huge subset of the UTxO is required at slot ticks, then we will need to adapt our design.

**Comment by dnadales** [comment]
While discussing https://github.com/input-output-hk/cardano-ledger/issues/3013 @TimSheard, @Jasagredo, and I realized this assumption might not hold, so we need to check it.

**Comment by javierdiaz72** [comment]
Hi, guys! I think you have the wrong Javier. :) Cheers!

**Comment by dnadales** [comment]
> Hi, guys! I think you have the wrong Javier. :) Cheers!

This was bound to happen at some point. You have no idea how many times I had to delete what I wrongly autocomplete. Sorry about that (maybe you want to formalize the assumption in Isabelle anyway :stuck_out_tongue: )

**Comment by JaredCorduan** [comment]
@dnadales for just the adaptation of moving the UTxO on disk, that assumption is correct. The size of the UTxO that the ledger will need is bounded by:

* how many transaction inputs you can fit into a transaction
* how many transaction you can fit into a block

Only the UTXO rule uses the UTxOs, with the exception of the Shelley to Allegra translation.

Now, when we start moving other data structures to disk, such as the stake credentials and the stake distribution, we will need to reconsider!

**Comment by jasagredo** [comment]
@JaredCorduan I think this answer is enough for UTxO-HD v0.1 as we are only moving the UTxO set to disk. I think we can re-scope this issue now for future work when we move something else to the disk. Thanks!!
