### ISSUE TITLE
track individual deposits

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3113]
# Overview

Individual deposits are not currently tracked by the ledger, only the values as given in the protocol parameters. This has several problems and needs to be addressed.

# What happens (today) if the deposit amounts are changed?

We currently collect deposits for:

- stake credential registrations
- stake pool registrations

The amount in Lovelace is  determined by two protocol parameters. In the event of a change to these parameters, the reserves absorb the difference, assuming it is large enough (otherwise the entire protocol parameter update is ignored).

In particular:

* If the deposit amount is raised, the appropriate number of Lovelace is removed from the reserves and added to the deposit pot. Users de-registering these resources will be given back a larger deposit than they originally gave.
* If the deposit amount is lowered, the appropriate number of Lovelace is added to the reserves and removed from the deposit pot. Users de-registering these resources will be given back a smaller deposit than they originally gave.

Pros for this methods

* We do not have to track the value of each deposit paid by the many registered stake credentials (the stake pool deposits are less problematic since there are far fewer of them).

Cons for this methods

- Most folks expect a deposit to be paid back exactly.
- We cannot increase the deposit amount once the reserves hits zero.
- If folks know that the deposit amount is soon to be increased, they can make free Lovelace by registering a lot of credentials.
- Because of all the ickiness above, it's going to be incredibly hard to ever change the values.

# What should we do instead?

We can always rewrite the ledger to track how much everyone deposited, and pay back exactly what they originally gave (we have the history, we just don't track it in the ledger state). This will, however, add to the already-problematically-big stake credential map. Note that the stake credential pointer map does already track when everyone registered, so we could perhaps re-use it together with a history of the changes to the parameter values (this would grow linearly with time, which is unfortunate, but might be small).

# This is imperative

Note the logic of the `NEWPP` rule. It checks three things:

1. There is a non-trivial update
2. There is enough in the reserves to account for increasing the deposit values
3. The maxBlockSize isn't being set to something too crazy (ie the max block body size and the max block header size are bounded by the max block size)

Note also that consensus makes the decision about whether or not to enact a hard fork based on the protocol parameter update state **two stability windows** before the end of the epoch.

This means that if quorum is met regarding changing the major protocol version, but the update violates 2. or 3. above, consensus will change the era but the ledger will not change the major protocol version, leaving the ledger in a split-brain state.

We therefore must commit to accepting a protocol parameter update two stability windows from the end of the epoch. Which means:

- We must check the max block size at the time the update is provided (there is no good reason we are not doing it this way now)
- We must track the deposits and pay back exactly what was paid.

**Comment by ilap** [comment]
Why just not add some value field in the ledger for their registrations (stake address, pool) based on the current parameters in some update before any registration parameters changes?

I meant the `StakeCreds` is a finite map where the key is the cred itself and the value is the slot it was registered.
It could be changed to some for both:
- from `StakeCreds -> Slot` to `StakeCreds -> (Slot , Coin)`   (stored in `DState`) and
- from `StakePools -> Slot` to `StakePools -> (Slot , Coin)` (stored in `PState`)  where the coin can be stake deposit at registration time (from protocol params i.e., `keyDeposit pp` or `poolDeposit pp`)

TBH, I have not to dig deep into the code, but I do not think it would be hard to implement.
The first step should be some update, which will migrate the finite maps from `Slot` to `(Slot, Coin)` (based on the current protocol params) and the relevant functions (`refund`, `refundKey`, `obligation`, `totalDeposits` etc. etc.)

This will ensure, that the ppl will get the same amount of money back they've deposited.
And in any case of the parameter's deposit changes the registration field for both will reflect/store the new deposit values for new registrations.

Though, what's the status of the `decayed deposit`? Will it be implemented?

**Comment by JaredCorduan** [comment]
> Why just not add some value field in the ledger for their registrations (stake address, pool) based on the current parameters in some update before any registration parameters changes?
> 
> I meant the `StakeCreds` is a finite map where the key is the cred itself and the value is the slot it was registered. It could be changed to some for both:
> 
>     * from `StakeCreds -> Slot` to `StakeCreds -> (Slot , Coin)`   (stored in `DState`) and
> 
>     * from `StakePools -> Slot` to `StakePools -> (Slot , Coin)` (stored in `PState`)  where the coin can be stake deposit at registration time (from protocol params i.e., `keyDeposit pp` or `poolDeposit pp`)

yes, if I understand you correctly, that is exactly what I am proposing (thought there is also the alternative of using the ptr map as a lookup).

> TBH, I have not to dig deep into the code, but I do not think it would be hard to implement. 

It is not hard to implement. The worry is that there are a lot of registered stake credentials, and we worry a lot about the size in memory of the ledger state.

> Though, what's the status of the `decayed deposit`? Will it be implemented?

We abandoned that idea before the Shelley release.

**Comment by ilap** [comment]
> It is not hard to implement. The worry is that there are a lot of registered stake credentials, and we worry a lot about the size in memory of the ledger state.

Then some other type could be used for storeing deposits instead of the arbitrary length `Coin`.

As 2 bytes would be more than enough to store up to 65K in values, which is more than enough for describing any current and future pool and cred deposits.

Meaning if we would have 10m stake creds it would be only ~20MB overhead in the ledger state (linear to the nr. of stake credentials).

**Comment by ilap** [comment]
> We abandoned that idea before the Shelley release.

What was the reason? As it's a quite good idea for incentivizing the non-performing pools to be deregistered.
As currently, there are no real incentives for deregistering a pool.
Ofc, if the decay function as a function of time/epoch gives some high pressure to the operators. Meaning when it's not linear but some `1/(x-a)^b` like or similar, like a sudden drop in deposit initially and slow decay afterwards.
And the well-performing pools can accept that loss long-term.

**Comment by JaredCorduan** [comment]
> Then some other type could be used for storeing deposits instead of the arbitrary length `Coin`.

We wouldn't store it as an arbitrary length integer, even `Coins` are not stored this way in memory, don't worry :)

> As 2 bytes would be more than enough to store up to 65K in values, which is more than enough for describing any current and future pool and cred deposits.

In Haskell, a Word (eight bytes) is the smallest unit of space that you can take up. But you also have to consider the other overhead of adding it to the existing data structures (again, knowing that a Word is as small as it gets).

**Comment by JaredCorduan** [comment]
> What was the reason? As it's a quite good idea for incentivizing the non-performing pools to be deregistered. As currently, there are no real incentives for deregistering a pool.

What do you mean? There is even more incentive without decay, as you get the whole thing back. I guess you mean they are incentivized to do it quickly? It's not that high anyway, I don't know how much it would matter.

The reasons were: 1) a lot of extra complication, 2) it assumed a lot of economic assumptions that may or may not even be true, such as the ability to price things at infinity (which usually assumes inflation).

**Comment by ilap** [comment]
> What do you mean? There is even more incentive without decay, as you get the whole thing back.

Sorry, I was confusing. I meant, they can keep their non-performing pool for long as they can back the same deposit independently of the deregistration time.  So, no incentives to deregister it as soon as possible as no pressure.

While, if they're losing some amount by the time they're incentivised to deregister it sooner than later.

> We wouldn't store it as an arbitrary length integer, even `Coins` are not stored this way in memory, don't worry :)

Cool, I have no knowledge of Haskell internals.

> The reasons were: 1) a lot of extra complication, 2) it assumed a lot of economic assumptions that may or may not even be true, such as the ability to price things at infinity (which usually assumes inflation).

Yeah, makes sense, but point 2. They will lose ADA by the time independently of the price of it. Though higher price than higher (profit) loss (compared to the initial FIAT investment) by the time.

**Comment by JaredCorduan** [comment]
resolved by #3127  #3195 and #3217

good news @ilap , we are only adding eight bytes per registered stake credential as hoped :)
