### ISSUE TITLE
Add no-thunk tests for cardano ledger eras translations

### ISSUE THREAD

**Issue by yogeshsajanikar** [IntersectMBO/cardano-ledger#3144]
As a part of running consensus tests with no-thunks flag turned on, few thunks were found hanging onto TVars. Some of these were traced to ledger code handling translations for eras. Specifically, lazy functor mapping for `UTxO` was the problem. If a no-thunk tests are added to ledger code, it would be easier for a library developer 

- to test and check provenance of a thunk, which usually takes a longer time.
- to check if a new thunk is accidentally introduced during the course of a time.

**Comment by JaredCorduan** [comment]
resolved by #2909
