### ISSUE TITLE
prevent ptr address from being created in conway

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3161]
Starting in the conway ledger era, do not allow the creation of transaction outputs that contain pointer addresses. Implementation options include: 1) adding a new predicate failure, perhaps the `UTXO` rule, 2) use the version CBOR to prevent pointer address from being deserialized starting in major protocol version 9.

**Comment by jmhrpr** [comment]
What if a script relies on sending something to a pointer address? Why not just remove the resolving functionality of pointers -> stake credentials, but deserialise as normal? Then the addresses can remain but there is no expensive look up required. It doesn't sound like the removal/blocking of the pointer addresses is required for Leios or for dealing with the case that the expensive look-up, but rather the resolution of the pointer to a stake credential is what causes the issues.

**Comment by JaredCorduan** [comment]
That's a very good point, @jmhrpr . Not resolving the pointers makes them effectively an enterprise address. I doubt anyone is doing something like this inside a plutus script (since there are only ~11 of them on mainnet), but what you suggest is probably the more proper thing to do. thank you for pointing this out!
