### ISSUE TITLE
Host cardano-ledger-api Haddock documentation

### ISSUE THREAD

**Issue by koslambrou** [IntersectMBO/cardano-ledger#3173]
As the `cardano-ledger-api` Haskell package

* will eventually become THE API for working with transactions for DApp developers

* will contain the actual user documentation on how to use it in the form of Haddock documentation

We need the Haddock documentation to be hosted somewhere. In the long run, this is probably something that needs to be handled by CHaP. But in the short/medium term, we need this to be hosted somewhere.

We can probably host it as a Github page. Options for routes names can be: 

* `https://input-output-hk.github.io/cardano-ledger/cardano-ledger-api`
* `https://input-output-hk.github.io/cardano-ledger/api`

**Comment by koslambrou** [comment]
Also, an additional nice feature to have would be to be provide a rendered Haddock in every PR. 
This is similar to what readthedocs does. For example: https://cardano-ledger--3165.org.readthedocs.build/en/3165/

This gives us the capability to easily view the rendered view of Haddock documentation in every PR.

Don't know if that's possible with Github pages though.

**Comment by lehins** [comment]
I think doing haddock for every PR would be an overkill, but hosted haddock for cardano-ledger-api and the rest of the ledger codebase is definitely useful. Master version of haddocks is now hosted on:
* The whole of cardano-ledger: https://input-output-hk.github.io/cardano-ledger/
* `cardano-ledger-api: https://input-output-hk.github.io/cardano-ledger/cardano-ledger-api/index.html
