### ISSUE TITLE
Result of evaluateMinLovelaceOutput and  evaluateMinFee is not valid after transaction update.

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/cardano-ledger#3181]
### Issue
Related :  https://github.com/input-output-hk/cardano-node/issues/2631

Since Babbage, era the encoded size of `Coin` data depends on the value it has. 

so, if we use `evaluateMinFee` function with `0 Lovelace` fee and then update the transaction with the calculated fee, the size of transaction will increase, and thus the fee is no longer sufficient.

### Solution 1
 Straight forward solution is to  change the `minfee`  function defined in  cardano-ledger-alonzo :
  [cardano-ledger/Tx.hs](https://github.com/input-output-hk/cardano-ledger/blob/c7c63dabdb215ebdaed8b63274965966f2bf408f/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Tx.hs#L333)

- Calculate fee for the transaction
- Calculate new size of transaction as `newSize = oldSize - sizeOf oldFee  + sizeOf minFee `
- return Fee based on new size.

### Solution 2
Since we do not need to do the double computation when we are just validating a transaction, 

We should have function pairs.  
- `minfee`   for validation. (same as current min fee)
- `minfeeForUpdate`, calculates fee as suggested in solution 1.

**Comment by JaredCorduan** [comment]
hi @mesudip :wave: 

yes, the minimum fee is a fixed point calculation. We have a helper function named `setMinCoinSizedTxOut` which will compute it for you. See https://github.com/input-output-hk/cardano-ledger/issues/2905.

**Comment by mesudip** [comment]
@JaredCorduan 

>  yes, the minimum fee is a fixed point calculation. We have a helper function named setMinCoinSizedTxOut which will compute it for you. See https://github.com/input-output-hk/cardano-ledger/issues/2905.

What about the fixedPoint calculation for the `txFee`, it has similar issue like the txoutMinLovelace.

The main issue is with these two functions in ` Cardano.Ledger.Shelley.API.Wallet`. These are used by `cardano-api` and eventually `cardano-cli` and these don't use the fixedPoint calculation.
Since these are user/developerAPI facing functions, my opinion is that these functions should use fixedpoint calculation.

```haskell
evaluateMinFee :: EraTx era => PParams era -> Tx era -> Coin
evaluateMinFee = getMinFeeTx
{-# DEPRECATED evaluateMinFee "In favor of 'getMinFeeTx'" #-}

-- | Evaluate the minimum lovelace that a given transaction output must contain.
evaluateMinLovelaceOutput :: EraTxOut era => PParams era -> TxOut era -> Coin
evaluateMinLovelaceOutput = getMinCoinTxOut
{-# DEPRECATED evaluateMinLovelaceOutput "In favor of `getMinCoinTxOut`" #-}
```

Or at least there should be functions in ledger for returning `txOutminLovelace` and `txFee` with fixedPoint

**Comment by lehins** [comment]
Yeah, I totally agree, we need implement such helper function that calculates the minimum fee (the same way we have minimum output) in `cardano-ledger-api`
