### ISSUE TITLE
KeyPair should be moved to tests

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3186]
The `KeyPair` type in `Cardano.Ledger.Keys` contains both the private and the public keys, which are never used in the ledger. It doesn't seem like anyone downstream uses that type. The only place were it is useful is in tests, therefore it should be moved to the new `cardano-ledger-core:teslib`  sublibrary introduced in #3184

**Comment by JaredCorduan** [comment]
:100:

**Comment by lehins** [comment]
Depends on #3184
