### ISSUE TITLE
Out of Date PagerDuty

### ISSUE THREAD

**Issue by ruhatch** [IntersectMBO/cardano-ledger#3206]
I used to work on this project and yesterday I got some PagerDuty alerts to my phone. Can you remove me from the comms list for pagerduty alerts?

**Comment by JaredCorduan** [comment]
hey @ruhatch ! :wave: I'm sorry you got alerted, I will definitely look into it.

**Comment by disassembler** [comment]
My apologies, we were revamping alerts this past week and some low priority environments got assigned to an old user that was never purged. If our paths cross again, I owe you a beer! Your user has been properly deleted now.

Sam
