### ISSUE TITLE
Gracefully fix `Redeemer` (de)serialization

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3237]
Gracefully fix `Redeemers` encoder/decoder length value from `4` to `3`. In other words:

* For Conway deserializer should be able to accept both values `3` and `4`
* For Conway serializer should use the correct value `3`
* Create a ticket that tracks disabling incorrect value `4` in deserializer in the era after `Conway` 

Encoder:

https://github.com/input-output-hk/cardano-ledger/blob/71c31ace17467ee02f065ad9fc5f640e5f1e4091/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs#L139-L142

Decoder:

https://github.com/input-output-hk/cardano-ledger/blob/71c31ace17467ee02f065ad9fc5f640e5f1e4091/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxWits.hs#L489-L495

**Comment by aniketd** [comment]
It was discovered that `FromCBORGroup` for `RdmrPtr` uses a `listLen` of `2`, and therefore `4` happens to be the correct number of elements in the codec.
