### ISSUE TITLE
Why does CDDL for Conway state protocol version 10 as next upgrade and not protocol version 9?

### ISSUE THREAD

**Issue by NetWalker108** [IntersectMBO/cardano-ledger#3251]
https://github.com/input-output-hk/cardano-ledger/blob/bb0b5a2c4218a7704c45e2066a2de31fe2683b8f/eras/conway/test-suite/cddl-files/conway.cddl#L47

Cc: @JaredCorduan

**Comment by lehins** [comment]
First protocol version for Conway will be `9`, because there will be an intra-era hardfork for Babbage with protocol version 8. Therefore the next upgradeable protocol version will be `10`. Does this answer the question?

**Comment by NetWalker108** [comment]
Ah this answers it @lehins, and I just realised I've confused Conway to be this intra-era hard fork. I thought Conway's upgrade to be protocol version 8. 

Can you please point me to the spec/changelog for protocol version 8? Thanks.

Also a side-question, is it appropriate to consider protocol version 8 as Babbage 1.X then?

**Comment by JaredCorduan** [comment]
There are no changes to the ledger (in the sense of code in this repository) for major protocol version 8.

The node repository does list the major change that will be introduced in the [release notes](https://github.com/input-output-hk/cardano-node/releases/tag/1.35.4): "Node 1.35.4 supports the use of SECP256K1 elliptic curves via new Plutus primitives at protocol version 8".

> is it appropriate to consider protocol version 8 as Babbage 1.X then?

Version 8 will still be considered `Babbage`, yes, but we do not qualify it with any extra numbers (besides just "major protocol version 8"). [CIP-59](https://github.com/cardano-foundation/CIPs/tree/6f50596b99b7de9ff8601553762566fde0ef7a30/CIP-0059) might be helpful to you here.

**Comment by NetWalker108** [comment]
Many thanks @JaredCorduan
