### ISSUE TITLE
broken links for specs in README

### ISSUE THREAD

**Issue by francolq** [IntersectMBO/cardano-ledger#3252]
Most links in the "Formal Specification" of the first table are broken.

All links under the "Other Documents" links are also broken.

**Comment by JaredCorduan** [comment]
duplicate of #3196 (and #3250), which we are now about to fix thanks to https://github.com/input-output-hk/cardano-ledger/pull/3245. see also https://github.com/input-output-hk/cicero/issues/67.

**Comment by francolq** [comment]
thanks!
