### ISSUE TITLE
Constraint based generation

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/cardano-ledger#3266]
Just writing down some tasks to keep track of the progress

- [x] Add to (Rep era t) new types for NewEpochState,  `EpochNo`, `Natural` (from Blocksmade)
- [x] Add Lens for each new `Var`
- [x] Add `Var`s for every field up to NewEpochState
- [x] Add a `Target` value `newepochstateT` for NewEpochState

**Comment by JaredCorduan** [comment]
@Soupstraw this is complete, correct?
