### ISSUE TITLE
Constitutional Committee hot key adoption in conway

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3267]
In the conway era, we no longer need to stage the adoption of the hot keys for the constitutional committee (corresponding to the old genesis keys). This was originally done for the overlay schedule, since anything that affects the block header check must be stable for one stability window.

The `TICK` rule is where the adoption is currently happening, using the `fGenDelegs` map. In conway, the [hot key certificate](https://github.com/input-output-hk/cardano-ledger/blob/3c4835dc4fe80a19f5714f576c49926d6a58c563/eras/conway/impl/src/Cardano/Ledger/Conway/Delegation/Certificates.hs#L31) can immediately update the hot-cold key map in the `Deleg-Gen` rule (which should be renamed to something like `Deleg-CC-HotKey`.

**Comment by Soupstraw** [comment]
Already implemented in the GOVCERT rule.
