### ISSUE TITLE
add LaTeX spec to CI

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#33]
There is a makefile inside `fm-ledger-rules/latex` which builds a pdf using Nix. It would be nice to check this build as a part of CI.  It would also be great if there was a way to publish the pdf as an artifact.

**Comment by dnadales** [comment]
@nc6 as far as I understand we are already doing this, however we are not able to prevent a merge from happening on a broken LaTeX file. How far are we from achieving this? Can I help somehow?

**Comment by dnadales** [comment]
@JaredCorduan closing this as we're currently checking Hydra

**Comment by dnadales** [comment]
I mean checking the LaTeX compilation on Hydra :upside_down_face:
