### ISSUE TITLE
Split cardano-ledger-pretty into pretty sub-library for every era

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3314]
Currently cardano-ledger-pretty defines orphan instances for all of the types in the ledger libraries. This has an unfortunate affect on the dependency graph of all of the test libraries. For example this makes `cardano-ledger-shelley-test` transitively depend on all of the era libraries: `cardano-ledger-shelley`, `cardano-ledger-mary`, `cardano-ledger-allegra`, `cardano-ledger-alonzo`, `cardano-ledger-babbage` and even `cardano-ledger-conway`. This increases compile times.

In order to solve this problem we can create sub libraries called `prettylib` and place orphan instances for all of the types defined in each individual era into its own sublibrary. All of the pretty class definitions and instances for types from core can go into `cardano-ledger-core:prettylib`

**Comment by JaredCorduan** [comment]
@lehins I think I can close #2746 in favor of this issue. agree?

**Comment by lehins** [comment]
Yes. I think so.

**Comment by lehins** [comment]
We completely got rid of `cardano-ledger-pretty`. This issue is no longer relevant
