### ISSUE TITLE
use alonzo-style txout serialization when possible

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3362]
The alonzo-style encoding of transaction outputs (the array) is smaller than the babbage one. When babbage features are not used, we should therefore use the alonzo style.

**Comment by lehins** [comment]
In particular, these two cases should use Alonzo encoder:

https://github.com/input-output-hk/cardano-ledger/blob/d883cf700488ed1c3ecefd403c9863a0e3943587/eras/babbage/impl/src/Cardano/Ledger/Babbage/TxOut.hs#L453-L454
