### ISSUE TITLE
Add tests to ensure that ConwayDCert decoding is backwards compatible

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/cardano-ledger#3397]
In #3387 we aimed to make DCert decoding backwards-compatible. We should write tests to ensure that's actually the case.

**Comment by lehins** [comment]
> The EncCBOR and DecCBOR instances for ConwayDCert should be backwards compatible with ShelleyDCert, meaning that it should be possible to decode a Shelley era certificate in Conway era (with the exception of MIR certificates). We should add tests to check that this is indeed the case.

More context from #3405

**Comment by lehins** [comment]
This has been fixed in #3596
