### ISSUE TITLE
Upgrade cardano-ledger to build with ghc-9.6

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-ledger#3400]
[x] Make it build.
[ ] Add it to CI.
[ ] Upload to CHaP.

**Comment by erikd** [comment]
This requires Plutus to build with 9.6.

**Comment by erikd** [comment]
Currently using SRPs until the dependencies properly support ghc-9.6.

**Comment by erikd** [comment]
Updating plutus dependency: https://github.com/input-output-hk/cardano-ledger/issues/3431

**Comment by erikd** [comment]
`plutus-preprocessor` in the `ledger` repo depends on `plutus-tx-plugin` in the `plutus` repo but the later is not currently buildable with `ghc-9.6` (only supports one GHC version, currently `ghc-9.2`).

For now, I will just make `plutus-preprocessor` unbuildable using the same logic as `plutus-tx-plugin`.

**Comment by lehins** [comment]
> For now, I will just make plutus-preprocessor unbuildable using the same logic as plutus-tx-plugin.

This is totally fine. When we need to run the `plutus-preprocessor` we can just use the ghc version that it is buildable for

**Comment by erikd** [comment]
PR is https://github.com/input-output-hk/cardano-ledger/pull/3437.

Cannot/shouldnot be merged until the `source-repository-package` stanzas I added can be removed.

**Comment by erikd** [comment]
Actually builds now.

**Comment by erikd** [comment]
RSPs removes and submitted for review.

**Comment by erikd** [comment]
Still needs to be uploaded to CHaP

**Comment by erikd** [comment]
Has been uploaded to CHaP.
