### ISSUE TITLE
Add tests to ensure Conway DCerts decoding/encoding is backwards-compatible

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/cardano-ledger#3405]
The `EncCBOR` and `DecCBOR` instances for `ConwayDCert` should be backwards compatible with `ShelleyDCert`, meaning that it should be possible to decode a Shelley era certificate in Conway era (with the exception of MIR certificates). We should add tests to check that this is indeed the case.

**Comment by lehins** [comment]
Duplicate of #3397
