### ISSUE TITLE
Move ToJSON ledger instances from `cardano-node`

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3418]
We would like to replace these functions in `cardano-node` with `ToJSON` instances:

https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Tracing/OrphanInstances/Shelley.hs#L311-L334

**Comment by lehins** [comment]
I wish it was a permalink, cause now we just don't know instances for which types this ticket was about.

**Comment by JaredCorduan** [comment]
ah shoot, usually I'm good at hitting `y` and having github swap `master` out for the lastest master sha.

it was probably about moving these from node into ledger: https://github.com/IntersectMBO/cardano-node/blob/3cbbace022c47434d42526096a08cc416851bde6/cardano-node/src/Cardano/Tracing/OrphanInstances/Shelley.hs

**Comment by lehins** [comment]
Aha, thank you @JaredCorduan :slightly_smiling_face: 

Move ledger related ToJSON instances from cardano-node to ledger, like theses ones for instance: https://github.com/IntersectMBO/cardano-node/blob/3cbbace022c47434d42526096a08cc416851bde6/cardano-node/src/Cardano/Tracing/OrphanInstances/Shelley.hs#L1153-L1175

**Comment by JaredCorduan** [comment]
you can also always ask @Jimbo4350 if he has a "move to ledger" wish list :)
