### ISSUE TITLE
Conway Certs

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3442]
The main `DELEG` rule that has been largely unchanged since the Shelley era will see some changes in Conway:

- [x] It will allow for DRep registration, delegation, and retirement
- [ ] It will check the stake key registration deposit amount, if specified in the cert
- [x] It will add new CC hot key delegation and cold key retirements
- [x] It will not include the MIR cert support

Note that the DRep delegation sub-rule will be storing the new DRep delegation relation in the UMap.

**Comment by lehins** [comment]
__Note to myself__: Some of this has already been implemented. Need to do check which parts have been implemented and which ones still need to be done and either create new tickets or update this one

**Comment by aniketd** [comment]
We can now work against https://github.com/input-output-hk/formal-ledger-specifications/tree/conway-v0.8 as a fixed version.
