### ISSUE TITLE
CC vote always No, when the committee is too small

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3444]
The constitutional committee will contain a group of members and a threshold for the proportion of yes votes required to pass governance actions. When a committee member retires (either by expiration or by actively submitting a retirement certificate), we still assume the same denominator as before the retirement for the purposes of determining if the threshold is met. If ever it becomes impossible to meet this threshold, the system automatically enters a state of no confidence.

For example, with four committee members and a threshold of 51%, if two members retire, the system enters a state of no confidence.

This logic needs to be present in the ratification rules.

**Comment by lehins** [comment]
Looks like we are converging on a slightly different decision of not to going into a NoConfidence mode when CC is too small. Instead we will count the whole Committee vote as a No on all governance actions when CC is below the minCCSize. This means that the only governance actions that can be ratified are the NoConfidence and the NewCommittee.
