### ISSUE TITLE
New key roles for Conway

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3445]
Perhaps with better names, the conway era will need new [key roles](https://github.com/input-output-hk/cardano-ledger/blob/d421556ef91362d13963a68a94c6f9e752d67e59/libs/cardano-ledger-core/src/Cardano/Ledger/Keys.hs#L119) for:

* committee cold key
* committee hot key
* DReps

**Comment by lehins** [comment]
There are already: https://github.com/input-output-hk/cardano-ledger/blob/d421556ef91362d13963a68a94c6f9e752d67e59/libs/cardano-ledger-core/src/Cardano/Ledger/Keys.hs#L127-L129

Perhaps `Voting` can be renamed to something like `VotingRep`? `DRep` is fine with me too, it just looks a bit out of place.

**Comment by JaredCorduan** [comment]
ah, sorry, those are actually all fine by me! I was going to fast. thank you!
