### ISSUE TITLE
Compute the DRep stake distribution

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3446]
The DRep stake distribution is obtained by applying the DRep delegation relation to the per-stake-credential stake distribution, similiarly to how the per-stake-poool distribution is created. This distribution needs to be computed and stored in the ledger state for the governance ratification logic to use.

There are several ways to do this, with pros and cons. We will refine this issue when we have definitely made a decision.

**Comment by lehins** [comment]
This will likely have to be done with a Pulser, in similar way how we compute StakePool distribution.

**Comment by lehins** [comment]
Fixed by #3592
