### ISSUE TITLE
Other ideas from CIP-1694

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3453]
Time permitting, we may pursue some of the "other ideas" from CIP-1694: https://github.com/JaredCorduan/CIPs/blob/e96681908fd336702b9d89827063a190c5656eab/CIP-1694/README.md#other-ideas--open-questions

**Comment by lehins** [comment]
Unlikely to happen, but I'll keep the Conway tag just in case until we are already in Conway

**Comment by lehins** [comment]
None of the "other ideas" made it into Conway.

If there will be interest in any of those ideas in the future, we can open new issues for them. Closing this ticket as "wontfix"
