### ISSUE TITLE
Minimum AVS for ratification

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3456]
There should be a threshold such that if the active voting stake (ie the total stake delegated to DReps) falls below this value, no governance action can be ratified. This is just for extreme circumstances, and the value should be something like one percent, or a fraction of a percent, of the total stake.

(This needs to be added to CIP-1694 as well)

**Comment by lehins** [comment]
If it does get into the CIP-1694 then we'll need to implement it. Until then this should not be implemented

**Comment by lehins** [comment]
From the looks of it, this is not something that will be implemented in Conway. Closing as wontfix
