### ISSUE TITLE
Rename Constitutional Committee certificates 

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3458]
Current names for Committee certificates are:
https://github.com/input-output-hk/cardano-ledger/blob/c1603995da7c57d95371844191d235b05bb476b7/eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs#L147-L148

These should be renamed to:
```haskell
data ConwayCommitteeCert c
  = ConwayAuthCommitteeHotKey !(KeyHash 'CommitteeColdKey c) !(KeyHash 'CommitteeHotKey c)
  | ConwayResignCommitteeColdKey !(KeyHash 'CommitteeColdKey c)
```

This rename should also apply to pattern synonyms implemented in #3455

**Comment by teodanciu** [comment]
Closed by https://github.com/input-output-hk/cardano-ledger/pull/3462
