### ISSUE TITLE
Decide if ScriptHash for StakePool votes should be allowed

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3512]
Specification defines that a vote is possible for these three entities:

* Constitutional committee
* DRep 
* Stake Pool

It also uses `Credential` for all of those entities as a matter of convenience for implementation, because the spec becomes simpler. Just as a reminder: Credential can either be a KeyHash or a ScriptHash.

However, using `Credential` means that the `ScriptHash` is allowed for all entities, including the Stake Pools. The spec for all eras clearly dictates that StakePoolId is a KeyHash and cannot be a ScriptHash.

Allowing ScriptHash for StakePool has numerous problems:

* First and foremost it is misleading to the user. Stake pools could never be represented by scripts, while all of a sudden we would allow transactions to be placed on chain that rely on such concept.
* If we are to allow such scripts, we could never disable them without a new Plutus version. And we would have to support it forever at least for PlutusV3 version. Enabling features are 
* Such votes can never be counted, so they are really useless data on chain
* Extra work for the API and CLI team to support and document such useless feature
* Extra work on ledger team side to test and validate that this useless feature works as expected: namely has no impact on the voting protocol.

Disadvantages of disabling ScriptHash for StakePool:

* If accounting for such change in the spec, then either:
  * Agda implementation becomes more complicated and cumbersome
  * Or such votes can be disabled in Agda spec by a Predicate, while Haskell implementation would protect against it with types.
* It would also be possible to simply not accounting for this in the spec, because disabling this case in implementation makes it stricter than a spec. The downside is that the translation function between Haskell and Agda becomes partial. Which, as far as I know, is only a minor inconvenience.

Current implementation disables scripts for stake pools in #3508 , but it can be easily changed. This ticket is tracking the final decision on this issue.

Everyone's input and opinion is appreciated.

**Comment by aniketd** [comment]
I vote for the following arrangement

> ...simply not accounting for this in the spec, because disabling this case in implementation makes it stricter than a spec. The downside is that the translation function between Haskell and Agda becomes partial. Which, as far as I know, is only a minor inconvenience.

**Comment by lehins** [comment]
> The downside is that the translation function between Haskell and Agda becomes partial.

I now realize this is not the case, since for conformance testing we will not need to translate votes from Agda representation to legder's Haskell implementation. Our conformance tests will be generating data on Haskell side and translating it to the Haskell code generated from Agda, not the other way around. So partiality is avoided in this case.

Moreover, I just had a long discussion with cardano-api team, because they mistakenly used a Credential for a StakePool, which led them to believe pools can be identified by plutus script.

So, this confirms my belief that it is a bad idea to allow a ScriptHash for StakePools
