### ISSUE TITLE
Disable `ppuProtocolVersionL` in Conway

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3539]
Conway will have a new mechanism for updating the protocol version, namely the HardFork govaction.

However, we should not remove it from PParams, because there are a lot of places where we rely on the ProtVer being there.

This means that there is a trick needed to disable in PParams HKD for PParamsUpdate, but not PParams

**Comment by Soupstraw** [comment]
Resolved by #3766
