### ISSUE TITLE
Prevent duplicates in `proposalProceduresTxBodyL `

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3540]
Currently `proposalProceduresTxBodyL` is defined as a sequence, which is problematic because it allows duplicate proposals.

Duplicate proposals don't make sense in general, but in the same transaction it will cause an issue with identifying a script with a ScriptPurpose, when it is implemented in #3533

Related ticket #3541, which could share the same solution.

**Comment by aniketd** [comment]
#3779
