### ISSUE TITLE
Convert `votingProceduresTxBodyL` to a `Map`

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3542]
Currently `votingProceduresTxBodyL` is defined as a sequence, which is problematic because it allows duplicate proposals.

Duplicate proposals don't make sense in general, but in the same transaction they will even cause issues when identifying a script with a `ScriptPurpose`.

For this reasons 
```haskell
  , ctbrVotingProcedures :: !(StrictSeq (VotingProcedure era))
```
must be switched to:
```haskell
  , ctbrVotingProcedures :: !(Map (VotingProcedureId (EraCrypto era)) (VotingProcedure era))
...

data VotingProcedureId c = VotingProcedureId
  { vpiGovActionId :: !(GovActionid c)
  , vpiVoter :: !(Voter c)
  }
```

This means that the `VotingProcedure` will loose the above two fields:
```haskell
data VotingProcedure era = VotingProcedure
  { vProcVote :: !Vote
  , vProcAnchor :: !(StrictMaybe (Anchor (EraCrypto era)))
  }
```

**Comment by lehins** [comment]
I just realized  that it is actually much better to switch to a nested Map for representing `VotingProcedures`:

```haskell
newtype VotingProcedures era = VotingProcedures
  { unVotingProcedures ::
      Map (Voter (EraCrypto era)) (Map (GovernanceActionId (EraCrypto era)) (VotingProcedure era))
  }
```

It does make decoding slightly more involved, namely we need to enforce that there are no nested empty maps, but it comes with very nice benefits:

* The most common case where a DRep or CC votes on a lot of proposal in a same transaction becomes a lot more efficient, both:
  * with respect to CBOR serialization, because a single Credential is being encoded, instead of as many as there are votes
  * JSON serialization becomes possible, in case whet it is needed. Otherwise encoding a Voter+GovActionId as a key of a map is quite ugly, something like this: `ScriptHash-0x12345678...-0xdeadbeef...#2`
* Better runtime performance 
  * with respect to memory representation
  * with respect to rules. There is no need to filter out on DRep's credential anymore, it is a O(log n) lookup.

**Comment by WhatisRT** [comment]
I like that change, but I probably wouldn't put it in the spec.

There is some room for tweaks still, since we don't know exactly what the most common pattern would be: it could also be the case that people vote for different roles, in which case splitting the `Voter` and putting a set of roles in `VotingProcedure` would be even more efficient. But what you have here is probably good enough for all cases and there's no need to make this more difficult.
