### ISSUE TITLE
Restrict `PParamUpdates` values

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3548]
Some of the PParamUpdates need their bounds tighten up. This ticket tracks these important tasks:

* [x] - Identify which pparam updates need extra validation
* [x] - Decide on concrete ranges for the above pparam updates
* [x] - Implement validation for the actual `PParamUpdates` possibly with stricter deserializer or predicate checks in the rules.

**Comment by WhatisRT** [comment]
There's already something in the spec for this: [paramsWellFormed](https://input-output-hk.github.io/formal-ledger-specifications/html/ledger/Ledger.PParams.html#1738). There may be some changes to this once I try to prove a bunch of properties, but who knows when that happens. I think you can safely take that list for now.

**Comment by lehins** [comment]
Yes, that's exactly what this issue is about. Ensuring that PParamsUpdates are well formed.I just left out the details on how we need to do this. So, thank you for linking to the spec

**Comment by lehins** [comment]
Well formedness of PParams as defined by the spec has been implemented.

There will also be a guradrail script in place that will take care of preventing Parameter change proposals that propose values outside of ranges specified by constitution

We also fixed the types of some of the parameters to reflect their actual width as used downstream in consensus
