### ISSUE TITLE
Exposing `Rules.{Utxo,Utxow,Utxos}` modules

### ISSUE THREAD

**Issue by Anviking** [IntersectMBO/cardano-ledger#3622]
We (`cardano-wallet` / wip `cardano-balance-tx` lib) were highly curious about reusing the ledger rules and/or smaller helpers like [`shelleyWitsVKeyNeeded`](https://github.com/input-output-hk/cardano-ledger/blob/3b1a42163c007afdef0a7ce49d3cf0236c554e23/eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Utxow.hs#L529-L538) both for testing and implementation.

It seems the modules were made hidden some while ago, e.g.:
https://github.com/input-output-hk/cardano-ledger/blob/master/eras/babbage/impl/cardano-ledger-babbage.cabal#L43-L46

Would it be possible for them to be exposed again?

**Comment by lehins** [comment]
All of the rules modules are re-exported from the top level `Cardano.Ledger.[Era].Rules` module, so all you need to do is `import Cardano.Ledger.Shelley.Rules (shelleyWitsVKeyNeeded)` :wink: 
Eg. https://github.com/input-output-hk/cardano-ledger/blob/3b1a42163c007afdef0a7ce49d3cf0236c554e23/eras/babbage/impl/src/Cardano/Ledger/Babbage/Rules.hs#L1-L7

Feel free to reopen the ticket and let me know if I misunderstood your question somehow.

**Comment by Anviking** [comment]
Doh! 👍  thanks!
