### ISSUE TITLE
Implement a sustainable way to update the CostModels

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3631]
Current approach of updating the cost models is to specify a PParamUpdate that must contain the cost model for every Plutus version since PlutusV1. This is not sustainable, since cost models are pretty big and pretty soon all of them will not fit into a single transaction.

An acceptable approach would to update a cost model for a single Plutus version at a time. In other words, whenever a CostModel is supplied for a language in the `Map Language CostModel`, only the CostModel that is supplied should be replaced, rather than replacement of the whole Map as a whole, which is the current behavior.

**Comment by Soupstraw** [comment]
Resolved by #3771
