### ISSUE TITLE
Implement UTXO rule for Conway with appropriate (stake) deposit refund calculations

### ISSUE THREAD

**Issue by aniketd** [IntersectMBO/cardano-ledger#3638]
The current UTXO rule accounts for deposit refunds with the assumption that the refunds should amount to the current PParams values. This changes with Conway. We need to keep track of deposits (this is already being done in UMap) and also pass the accumulated information about deregistering stake credentials that need to be refunded in the DELEG rule onto the UTXO rule where the calculations will be processed for the UTXO state.

1. We need another field in DState to accumulate deregistered stake creds, and their exact refund amounts, taken from the UMap.
2. UTXO rule could then lookup this information in its `Environment` to process the refunds.
3. This field should be reset before CERT in CERTS for the next instance.

**Comment by aniketd** [comment]
@lehins @WhatisRT @Soupstraw

**Comment by lehins** [comment]
We decided to pass the previous certState into the UTXOW rule, which still has information about the unregistered DReps and StakeCredentials. This is the way it is done in Shelley through Babbage.
