### ISSUE TITLE
[cardano-ledger]: Fix ghc 9.6 support

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-ledger#3653]
Somehow, `HEAD` of master got broken and nobody notcied.

**Comment by lehins** [comment]
How so? We have CI that runs with GHC 9.6. Still runs fine.

How can we reproduce the problem you are describing?

**Comment by erikd** [comment]
I screwed up. 

I followed the following the order of operations:

* Install ghc-9.6
* Try to build ledger and failed.
* Build one of my projects with ghc-9.6
* Try to build ledger and success
