### ISSUE TITLE
Use of (CompactForm Coin) in IncrementalStake

### ISSUE THREAD

**Issue by TimSheard** [IntersectMBO/cardano-ledger#3702]
In PR #3676, we changed from using the Mark Snapshot to using the `credMap` field of the Incremental Stake to initialize the pulsing `DRepDistribution` (in file `eras/conway/impl/src/Cardano/Ledger/Conway/Rules/NewEpoch.hs`)

One disadvantage of this was the `SnapShot` stored the `Coin` as `CompactForm Coin`, which is exactly the type needed in the `Pulser` for efficient summation.  In the `IncrementalStake` it is stored as a `Coin`, so the initialization must do this conversion which is expensive at a time (the epochBoundary) when we don't have much time.  We should change the `IncrementalStake` to be a `(Map cred (CompactForm Coin)`, and the pulser from  `(VMap   cred (CompactForm Coin))` to `(Map cred  (CompactForm Coin))`, this way no conversion is necessary. 

In  `Cardano.Ledger.Shelley.LedgerState.Types`

```haskell
data IncrementalStake c = IStake
  { credMap :: !(Map (Credential 'Staking c) Coin)
  , ptrMap :: !(Map Ptr Coin)
  }
```

Changes to 
```haskell
data IncrementalStake c = IStake
  { credMap :: !(Map (Credential 'Staking c) (CompactForm Coin))
  , ptrMap :: !(Map Ptr Coin)
  }
```

and in `Cardano.Ledger.DRep`

```haskell
data DRepPulser c (m :: Type -> Type) ans where
  DRepPulser ::
    (ans ~ Map (DRep c) (CompactForm Coin), m ~ Identity) =>
    !Int ->
    !(UMap c) ->
    !(Map (Credential 'DRepRole c) (DRepState c)) ->
    (VMap VB VP (Credential 'Staking c) (CompactForm Coin)) ->
    !ans ->
    DRepPulser c m ans
```

changes to

```haskell
data DRepPulser c (m :: Type -> Type) ans where
  DRepPulser ::
    (ans ~ Map (DRep c) (CompactForm Coin), m ~ Identity) =>
    !Int ->
    !(UMap c) ->
    !(Map (Credential 'DRepRole c) (DRepState c)) ->
    (Map (Credential 'Staking c) (CompactForm Coin)) ->
    !ans ->
    DRepPulser c m ans
```

**Comment by lehins** [comment]
Fixed in #3747
