### ISSUE TITLE
Improve ImpTest so that HSpec can show diffs

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/cardano-ledger#3755]
This does work, but it destroys the ability for hspec to show diffs, which is a bit unfortunate, but I think I know the way how to solve this (which we can postpone fixing to a subsequent PR)

_Originally posted by @lehins in https://github.com/input-output-hk/cardano-ledger/pull/3733#discussion_r1335934434_

**Comment by lehins** [comment]
Fixed in #3842
