### ISSUE TITLE
DRepRegistration certificate must require a witness

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3890]
Current implementation wrongfully does not require a witness for DRep registration certificate.

According to the spec it is required:

https://github.com/input-output-hk/formal-ledger-specifications/blob/eafd83a7931cd6af07212253a183115e740f6c1e/src/Ledger/Deleg.lagda#L103

Here:

https://github.com/input-output-hk/cardano-ledger/blob/afedb7d519761ccdd9c013444aa4b3e0bf0e68ef/eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs#L620-L621

and here:

https://github.com/input-output-hk/cardano-ledger/blob/afedb7d519761ccdd9c013444aa4b3e0bf0e68ef/eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs#L642

**Comment by catch-21** [comment]
This affects both `DRepKeyHash` and `DRepScriptHash`

**Comment by lehins** [comment]
> This affects both DRepKeyHash and DRepScriptHash

Correct
