### ISSUE TITLE
Move `EpochInterval` to `cardano-base`

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3944]
The package where `EpochNo` and `EpochSize` are defined is `cardano-slotting`. It only makes sense for `EpochInterval` and `addEpochInterval` to live there as well.

See a related ticket: https://github.com/IntersectMBO/cardano-base/issues/455

Also adding `IsList` instance for `StrictSeq` would be nice too: https://github.com/IntersectMBO/cardano-base/issues/444

This is a multi-stage process:
* [x] - Add changed to the `cardano-base`
* [x] - Release to CHaP
* [x] - Update cabal index
* [x] - Account for the changes in cardano-ledger

**Comment by TimSheard** [comment]
just remember cardano-slotting is not part of cardano-ledger.

**Comment by lehins** [comment]
> just remember cardano-slotting is not part of cardano-ledger.

I am aware of that. I've linked a related ticket on the `cardano-base` repo and said so in the title of this ticket.
Why do you bring it up?

**Comment by TimSheard** [comment]
Only, that as a good first issue, maybe it's not so good, as it requires bumping version numbers.

**Comment by lehins** [comment]
On the contrary. That is a perfect way to get acquainted with how cross-repo packages interact. This would serve as a great introduction to CHaPs, etc.
