### ISSUE TITLE
ToJSON of BabbagePParams is missing protocolVersion

### ISSUE THREAD

**Issue by v0d1ch** [IntersectMBO/cardano-ledger#3948]
The title pretty much says it all. If you encode `BabbagePParams` to json string it is missing the `protocolVersion` field which is actually there `bppProtocolVersion`. I might do a small PR when I find some time unless this is picked up by someone before.

**Comment by lehins** [comment]
This is a duplicate of #3943 

If you'd like to submit a PR that fixes it, that will be great.
