### ISSUE TITLE
Change DNS entry for the GitHub pages

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/cardano-ledger#3967]
Seems like the https://intersectmbo.github.io/cardano-ledger site should instead be at https://cardano-ledger.cardano.intersectmbo.org based on the pattern we're seeing in other Intersect repos.

**Comment by lehins** [comment]
This is very strange. I did change the domain for github pages right after the transition to IntersectMBO (we even changed the url in README.md):

https://github.com/IntersectMBO/cardano-ledger/blob/fdc366df654fc02b1668012342732d41eaa099fe/README.md?plain=1#L10


Somehow DNS was removed on Github. 
I've authorized it back again it should work now: [cardano-ledger.cardano.intersectmbo.org](https://cardano-ledger.cardano.intersectmbo.org/)

Thank you for reporting this.
