### ISSUE TITLE
CommitteeMember can vote on UpdateCommitteeProposal

### ISSUE THREAD

**Issue by mkoura** [IntersectMBO/cardano-ledger#3980]
A transaction that contains CommiteeMember vote on UpdateCommiteProposal can be successfully submitted and accepted on chain without resulting in DisallowedVoters failure.

```json
  "proposals": [
    {
      "action": {
        "contents": [
          null,
          [],
          {
            "keyHash-db34410e3234ef221cdb5a0361197707845168fab6cf7e6eff19d9b7": 28
          },
          0.6
        ],
        "tag": "UpdateCommittee"
      },
      "actionId": {
        "govActionIx": 0,
        "txId": "4963f82f7e3d652b06c69f1ee13f1c2df600a47605777891b72c6f27776f189b"
      },
      "committeeVotes": {
        "keyHash-70735b325f5084b23d5f52603642e8f0de61dc8067390a23481b5571": "VoteNo",
        "keyHash-99ee64dd3c5eb4b4d7b77c3f405337cb79f8f7ca0294db294afadf42": "VoteNo",
        "keyHash-f9da4a0db77c27245dbf98202285d6581e1ac383e13d89f233ccd183": "VoteNo"
      },
      "dRepVotes": {
        "keyHash-3cbb0d943e555ad34594ffeddae4703fe39c3e0acc23a5070a4e1bbc": "VoteYes",
        "keyHash-4d7c8d097e0cfb9c279e8e2d3d42668ccddfe55254e930a5c59be6dd": "VoteYes",
        "keyHash-a6ed79d34d7fc61fa7417d7e69446919afa6610d5b4af2b5787f8eda": "VoteYes",
        "keyHash-f679b984fd1b2e87e583fc3f2f4198dbdb999744033b2eb8d534003f": "VoteYes"
      },
      "deposit": 100000000,
      "expiresAfter": 26,
      "proposedIn": 24,
      "returnAddr": {
        "credential": {
          "keyHash": "4567e58c2966eb77fb951f063b2d3d466d5f6675884562597c7db563"
        },
        "network": "Testnet"
      },
      "stakePoolVotes": {
        "c0875e300838c796d14afd125a281d8a05f710c3dedc2e3e00b88c88": "VoteYes",
        "cc6095a014a7d4e31d4149841e427b754efd0233f830d32128fe892e": "VoteYes",
        "f0ae80ac376a5f0fb43ce843e1188c0e33f1867c7afe76f7f0c100e0": "VoteYes"
      }
    }
  ]
```

**Comment by Soupstraw** [comment]
I'm trying to reproduce this, but all of the transactions where a committee member tries to vote for a committee change get rejected. Do you have any transactions that reproduce this behavior?

**Comment by mkoura** [comment]
Archive with proposed action, votes, gov state and transaction: [ledger_issue_3980.tar.gz](https://github.com/IntersectMBO/cardano-ledger/files/13990566/ledger_issue_3980.tar.gz)

**Comment by Soupstraw** [comment]
I noticed that the `EnactState` in the archive doesn't have a script hash in the constitution, ~~so it seems to be using a pretty old version of `cardano-ledger-shelley` (at least 6 months old).~~ 

Can you tell me what version of ledger this was using @mkoura?

EDIT: Never mind, my bad, our JSON encoder just omits the script if there isn't one

**Comment by lehins** [comment]
@Soupstraw This bug report will be from the current version on SanchoNet, cardano-node-8.7.3,
which uses cardano-ledger-conway-1.11.0.0
