### ISSUE TITLE
Newly elected CC members are removed together with other unrecognized CC members

### ISSUE THREAD

**Issue by mkoura** [IntersectMBO/cardano-ledger#4001]
It should be possible for new potential CC members to authorize their hot keys, and the hot keys should stay authorized once the member gets elected.
It is not the case, the authorized key is removed once the "update committee" proposal that added the member gets ratified.

1. Authorize hot keys for two new potential CC members. The members are shown with status `Unrecognized`, and their hot keys have tag `MemberAuthorized`:

```json
{
    "keyHash-b996f3e6e53884a2aafa98ede0a23cb7200542092846033c26f5b18c": {
      "expiration": null,
      "hotCredsAuthStatus": {
        "contents": {
          "keyHash": "44fb79e80bfe48184165ab213ffeacbe5828b6ff6f2a2097f38c16da"
        },
        "tag": "MemberAuthorized"
      },
      "nextEpochChange": "NoChangeExpected",
      "status": "Unrecognized"
    },
    "keyHash-ea6bf31dff5e45a809b98bff7a157b178f429b230b34f4e988861bc0": {
      "expiration": null,
      "hotCredsAuthStatus": {
        "contents": {
          "keyHash": "7f8d2df7ac1080b6e4c6cbb2f28ad2740e728ef2eefa2f7c76987f59"
        },
        "tag": "MemberAuthorized"
      },
      "nextEpochChange": "NoChangeExpected",
      "status": "Unrecognized"
    }
}
```

2. Propose a "update committee" action that adds one of the new potential CC members.
3. Elect the new CC members.
4. Once the proposal is ratified, check that all `Unrecognized` CC members were removed, both the newly elected and the non-elected ones. Both CC members listed above can no longer be queried.
5. Wait until the proposed action gets enacted.
6. Check that the newly elected CC member was added and can be queried. However, its hot key is missing and tag is `MemberNotAuthorized`. Therefore he needs to authorize his hot key again.

```json
{
    "keyHash-b996f3e6e53884a2aafa98ede0a23cb7200542092846033c26f5b18c": {
      "expiration": 5,
      "hotCredsAuthStatus": {
        "tag": "MemberNotAuthorized"
      },
      "nextEpochChange": "NoChangeExpected",
      "status": "Active"
    },
}
```

Full committee state query outputs and governance state dumps: [ledger_issue_cc_members.tar.gz](https://github.com/IntersectMBO/cardano-ledger/files/14016002/ledger_issue_cc_members.tar.gz)

**Comment by teodanciu** [comment]
The steps in the order described above are yielding results as expected, namely: registered hot keys get removed in the next epoch (unless their corresponding members got elected prior to the hot key registration).  So: you can't authorize and after that elect the member. 

The way the "pre-authorization" of the hot key works is like this: 
 **Epoch n**
      ratification: member c1 gets elected  (after being proposed and voted on)
 **Epoch n + 1**    
    * state of the member  c1 (as returned by our query is): 
       `CommitteeMemberState MemberNotAuthorized  Unrecognized Nothing ToBeEnacted`
    * member registers hot key hk1
    * state of the member  c1 (as returned by our query is): 
       `CommitteeMemberState (MemberAuthorized hk1)   Unrecognized Nothing ToBeEnacted`
 **Epoch n+ 2** 
    * new committee gets enacted. Member c1 stays authorized with the hot key hk1. 
    * state of the member  c1 (as returned by our query is): 
      `CommitteeMemberState (MemberAuthorized hk1) Active (Just 12) NoChangeExpected`   


I will close the issue for now. For reference, the test case for this is here: https://github.com/IntersectMBO/cardano-ledger/blob/master/libs/cardano-ledger-api/test/Test/Cardano/Ledger/Api/State/Imp/QuerySpec.hs#L60
If  I misunderstood the problem or there are other cases that are not covered, please update/reopen the ticket.
