### ISSUE TITLE
Conway BUG - Its possible to retire a stakeaddress while an active proposal is running

### ISSUE THREAD

**Issue by gitmachtl** [IntersectMBO/cardano-ledger#4017]
Tested on current SanchoNet

```console
$ cardano-node --version
cardano-node 8.7.3 - linux-x86_64 - ghc-8.10
git rev a4a8119b59b1fbb9a69c79e1e6900e91292161e7
```

Its possible to retire a stakeaddress while an active governance proposal is open and running!

What happens to the deposit-amount after the proposal reached its expire epoch? 

It would be good to have an information about such deposits via cardano-cli and the `query stake-address-info` request with a new output entry like `proposalDeposits` or similar.

Similar to the checks about remaining rewards on a stakeaddress, it should be impossible to retire a stakeadress while this keyhash is involved in an open proposal which required a deposit amount.

Other than with the rewards-address for a stakepool-registration (which would receive the pool deposit amount), the governance action proposal needs to be signed with the stake secret key that is set to be the receiving address for the deposit-return.

As an alternative, maybe a good idea to offer the retirement but refunding all deposits at the same time. Like with the stakeaddress deposit amount. Which than would also remove/end all governance action proposals for that keyhash?

@lehins

**Comment by intertreeJK** [comment]
Agreed. If it is possible to add such checks, they really do need to be added. 

Don't want orphaned Proposal Deposits sitting On-Chain.

**Comment by lehins** [comment]
In such cases we should be doing the same as what we do for stake pool rewards and deposits when the reward account gets unregistered, we place those deposits and rewards into the treasury.

However, I believe this is not the current behavior. So, thank you for reporting this bug!

**Comment by WhatisRT** [comment]
As @lehins said the intent is that unclaimed money goes to the treasury, as we do with things like staking rewards and a bunch of other stuff. If the current implementation just burns the deposit that's indeed a bug.

While it'd be possible to prevent deregistration while a proposal is active, it'd probably be a mistake. You may have a good reason to deregister your credential, and if you don't care about the deposit that's fine. Note that doing this by accident doesn't lose anything if it is caught: if the credential is re-registered by the time the deposit is paid out it'll still go to that address. This is exactly the same behaviour as with other rewards and deposits that are paid out at the epoch boundary.

**Comment by WhatisRT** [comment]
Actually, maybe it'd be a good feature for the CLI/other interfaces to refuse deregistration with outstanding rewards/deposits except if there is a special flag passed?

**Comment by lehins** [comment]
> maybe it'd be a good feature for the CLI/other interfaces to refuse deregistration with outstanding rewards/deposits

Unless we implement it in ledger as a new ledger state query it would be pretty expensive for CLI to implement such protection, since they would have to download huge chunks of ledger state in order to be able to answer this question: "Is this reward account used anywehre?".

Something like db-sync can provide answers like that, but cardano-cli doesn't use db-sync.

I would be totally fine to adding such query to ledger if there will be a need for it.

**Comment by gitmachtl** [comment]
> Something like db-sync can provide answers like that, but cardano-cli doesn't use db-sync.
And thank you for that! 😄 

Its just a bit of a strange "in between" query system with cardano-cli, you can query things, but you don't get the full picture.

With the 3rd party tools, we can query the governance state for a stakekey too to get a better picture. So not the end of the world.
