### ISSUE TITLE
Conway mislabeling of Constitutional Committee Parameter

### ISSUE THREAD

**Issue by intertreeJK** [IntersectMBO/cardano-ledger#4018]
Tested on current Sancho Testnet 

$ cardano-node --version
cardano-node 8.7.3 - linux-x86_64 - ghc-8.10
git rev a4a8119b59b1fbb9a69c79e1e6900e91292161e7

Following Mike Hornan, Nicolas Cerny, and I's recent running of a series of Test Suites to determine what Ratification outcomes would occur across various combinations of Yes/No Votes from the Constitutional Committee's voting on a Proposal. It was discovered that the, so named, 'Quorum' Parameter of the Constitutional Committee is in fact acting with the behaviour of a Threshold Parameter.

It is therefore **highly** suggested that the official On-Chain naming of the CC Quorum Parameter be changed to reflect its core function. Which is that of a Threshold. 

More information about the testing patterns that were run on Sancho Testnet are available at Mike Hornan's Governance GitHub Repository: https://github.com/Hornan7/Testnet_Scenarios 

NB: The definition of Quorum is as follows -

"The minimum number of members of an assembly or society that must be present at any of its meetings to make the proceedings of that meeting valid."

It is most certainly **not** supposed to be the actual **target** of the required amount of Yes Votes for something to Pass.

It is **only** supposed to be the amount of people required to actually show up to vote on something before that vote can be considered valid. 

As it stands,  the Quorum Parameter is currently set up to be an actual **target** for the **amount of Yes Votes** required to deem an Action to be Constitutional.

i.e. It may not be working as intended. 

If it is...

Then that Parameter needs to be renamed to be **Threshold**. To avoid any user confusion being created such as the confusion Mike and I had during our predictions of the Voting Outcomes in the Testing Repository linked to above. 

It also needs to be made clear in any documentation that the now renamed CC Member 'Threshold' Parameter setting takes precedence over **all** other Governance Action Threshold Parameter Settings, in the DRep sphere, when it comes to the Constitutional Committee's Voting Process as to the Constitutionality of a Proposal. As was shown during our testing. 

I hope this request is acceptable. 

Thank you kindly 🙏🏻

**Comment by Hornan7** [comment]
I second Johnny's comments. As you will see in the results of our tests, for a "Quorum" of 3/9: 
3 `Yes` votes and 6 `No` votes still allows the ratification of governance actions.

Also, 2 `Yes` votes and 1 `No` vote does not allow the ratification of governance action. 

This does not reflect with the definition of the word "Quorum", and as mentioned by Johnny, I myself have been caught up in unnecessary debate on this subject.

"Threshold" would in my opinion be a much better choice and would avoid many confusing situations such as the one we regularly experience.

Thank you,
--Mike Hornan

**Comment by WhatisRT** [comment]
Yes, this is indeed supposed to be called a threshold. It used to be a quorum (in name and function) a long time ago in the CIP, but it's been renamed for a while, see the table in the CIP:
```
2. New constitutional committee and/or threshold and/or terms | Changes to the members of the constitutional committee and/or to its signature threshold and/or terms
```
Can you point out where the name "quorum" is still used?

**Comment by intertreeJK** [comment]
Yes: https://book.world.dev.cardano.org/environments/mainnet/conway-genesis.json

See parameter name in conway-genesis.json for Mainnet for Constitutional Committee.

**Comment by lehins** [comment]
Yeah, this never got renamed in the actual implementation.

@intertreeJK Thank you for reporting this, we'll get it renamed.

**Comment by intertreeJK** [comment]
Splendid!

Much appreciated 🙏🏻

**Comment by Hornan7** [comment]
> Can you point out where the name "quorum" is still used?

The CC "Quorum" is also mentionned [here](https://github.com/cardano-foundation/CIPs/blob/7687f28447359cd2bdbc945b6acf651906e1583b/CIP-1694/README.md?plain=1#L1032)
And also [here](https://github.com/cardano-foundation/CIPs/blob/7687f28447359cd2bdbc945b6acf651906e1583b/CIP-1694/README.md?plain=1#L1373), and [here](https://github.com/cardano-foundation/CIPs/blob/7687f28447359cd2bdbc945b6acf651906e1583b/CIP-1694/README.md?plain=1#L1727)

That should be it. 😃👍

**Comment by WhatisRT** [comment]
I have an open PR to the CIP that fixes this (and lots of other things): https://github.com/cardano-foundation/CIPs/pull/622 I don't want to change it in the changelog though, since that documents historical changes.
