### ISSUE TITLE
Shelley spec: POOLREAP inference contradicts described pool rules

### ISSUE THREAD

**Issue by zuzunker** [IntersectMBO/cardano-ledger#4043]
Might have been already reported, but I couldn't find it.

The EPOCH inference rule parameter `e` (epoch) is only used to call the POOLREAP inference:

![image](https://github.com/IntersectMBO/cardano-ledger/assets/5585355/02e249f9-e752-48bc-b964-96edd9ed8a69)

The POOLREAP inference parameter `e` is only used to calculate the `retired` state which is defined as the mirror image of the `retiring` state filtered by the specified epoch `e`:

![image](https://github.com/IntersectMBO/cardano-ledger/assets/5585355/97aa1bb5-a28f-42fb-80fa-b913eec5c21a)

The `retiring` state is defined as the pool keys mapping into the `retire c` value which is supposed to just return the epoch specified in the pool retirement certificate:

![image](https://github.com/IntersectMBO/cardano-ledger/assets/5585355/676862ca-4417-4ce2-a0ee-73ab84341858)

This means that whatever is the value of `e` specified when EPOCH transition is called - the `retired` state will contain the pools for which the retirement certificates contain the same specified retirement epoch value.

The problem is that it is never clearly defined what `e` should actually be in the EPOCH inference. An epoch boundary is an event between two epochs: **the closing epoch** and **the new starting epoch**. It is not clear if the EPOCH inference should be called with the CLOSING epoch or the STARTING epoch as parameter.

The stake pool rules section is the only place (I think) that explicitly mentions that: pool must be actually retired **"at the end of the epoch they are scheduled to retire in"**.

![image](https://github.com/IntersectMBO/cardano-ledger/assets/5585355/16ed1547-0f75-44da-a4c6-db9ada872071)

This requirement explicitly limits the `e` parameter in the `EPOCH(e)` inference to be the CLOSING epoch, the one that just ended. Because only in this case the `dom(retiring^−1 e)` would select the pools **AT THE END** of their specified retirement epoch.

-----

E.g. current epoch is 99, pool X submits a retirement certificate with the retirement epoch 100.

- Epoch boundary FROM 99 INTO 100 happens.
- EPOCH inference is called with e = 99 (the CLOSING epoch)
- The pool X is **not** selected as retired, because `retiring` state is `{ X: 100 }`
- Pool X keeps working until the end of epoch 100

In this case the requirement stated in the pool rules would be satisfied.

------

If we use the starting epoch instead.

- Epoch boundary FROM 99 INTO 100 happens.
- EPOCH inference is called with e = 100 (the STARTING epoch)
- The pool X **IS** selected as retired, because `retiring` state is `{ X: 100 }`
- Pool X is retired immediately at the end of epoch in which the retirement certificate was submitted.

In this case the requirement stated in the pool rules is **NOT** satisfied. Because the pool is actually retired at the beginning of the specified retirement epoch, and not at the end.

-----

The correct or incorrect behaviour that matches or does not match the text clearly stated in the specification is thus entirely dependant on the undefined parameter `e` and seems to be left to be decided by an implementation.

I am still trying to double-check it, but according to the main node testing it seems that the incorrect way has been implemented. It seems that pools do actually get removed at the **start** of the scheduled epoch.

Seems like the `e` needs to be better defined for the inference, and maybe the section about the retirement happening at the end of the scheduled epoch can be removed to not cause confusion, comparing to how things actually work.

Seems like the two initial requirements: **retirement epoch must be greater than the current epoch** and **pools are removed at the end of the retirement epoch** were supposed to ensure that delegators have at least a whole epoch to see the planned retirement and redelegate. Right now (in the implementation, tested on the `8.7.3` node) it seems to be possible to get a pool retired and removed in a very short time, in case the owner submits the retirement scheduled for the next epoch at the end of the current epoch their pool will get removed right at the end of the current epoch along with all the existing delegations, without any time for the delegators to react.

**Comment by zuzunker** [comment]
In case someone else will try to make an implementation of the node it pretty much depends on that `e` parameter, whether they get a matching rewards state or not, because it affects when exactly the deposit will be returned into account, which changed the delegation value for that account, etc.

**Comment by HeinrichApfelmus** [comment]
For each parameter `e`, there is a possible state transition according to the EPOCH rule — you can't tell whether only a subset of them are used by looking just at the EPOCH rule.

In order to find out which transitions are actually used, you have to look at rules which use the EPOCH rule. In this case, the NEWEPOCH rule answers your question:


<img width="622" alt="NEWEPOCH" src="https://github.com/IntersectMBO/cardano-ledger/assets/564592/25ae68c0-0296-42ce-82bb-9b6273d4c0e3">

**Comment by zuzunker** [comment]
> In order to find out which transitions are actually used, you have to look at rules which use the EPOCH rule. In this case, the NEWEPOCH rule answers your question:

Thank you, @HeinrichApfelmus. I did miss this part. So if I understand correctly it shows that EPOCH transition is invoked with the STARTING epoch number as parameter. This is then directly contradicts the text in the pool rules that "pools scheduled for retirement must be removed at the end of the epoch they are scheduled to retire in". Seems like would be better to get rid of that part.

**Comment by HeinrichApfelmus** [comment]
> So if I understand correctly it shows that EPOCH transition is invoked with the STARTING epoch number as parameter. 

Not necessarily — according to the comments, $e_{\ell}$ is the "last epoch".

However, looking at the TICK rule, it appears that $e = \text{epoch } slot$ where $slot$ is the slot of the most recent block. In other words, the NEWEPOCH rule is indeed called with $e$ equal to the epoch number of the most recent block. This means that pools are removed with the first block of an epoch.

----

Somewhat unrelated, I just noted that the prose for "12.3 New Epoch Transition" is not accurate: The environment to the NEWEPOCH rule is empty, and contains neither slot nor genesis keys.

**Comment by WhatisRT** [comment]
Nice catch on the prose error, probably some leftover from the past.

**Comment by WhatisRT** [comment]
I made a PR for that. Is there anything left to do here?

**Comment by zuzunker** [comment]
> I made a PR for that. Is there anything left to do here?

Thank you!
