### ISSUE TITLE
Milestone 1: Figma design and prototype of the user interface, Architectural design

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/cardano-ledger#4044]
**Deliverables**

- User personas
- User journey maps
- User stories for each stage of journey map
- Full flows
- Wireframes
- Detailed technical/ architecture design document

**Comment by lehins** [comment]
@ValMBO My apologies. Are you sure you have the right repository?

We don't have any UI that requires wireframes, etc. Nor do we have end users. Ledger is a Haskell library, not a separate product that has user journeys and personas. 

Maybe you are confusing us with the GovTool?

**Comment by Ryun1** [comment]
Added here by mistake.
