### ISSUE TITLE
Change the type of `minFeeRefScriptCoinsPerByte`

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4052]
In a recent PR #3983 a new protocol parameter has been added. One oversigt was that the type that was used does not allow for a more fine grain tuning of the fee, because it is backed by an `CoinPerByte`, which is essentially a `Coin`. In other words it only allows one lovelace per byte granularity, which might not be enough in the future. 

In order to allow us to be as precise as necessary, we need to:

* [x] - We need to change the type to `NonNegativeInterval`
* [x] - Change the formula to use rounding
* [x] - Rename the parameter to `minFeeRefScriptCostPerByte`
* [x] - Adjust CDDL

Here is the implementation of the fee calculation:

https://github.com/IntersectMBO/cardano-ledger/blob/e73acc68d1ee98e59849288a9825b8fe1fb83324/eras/conway/impl/src/Cardano/Ledger/Conway/Tx.hs#L85-L87

Which should be changed to this new calculation:

```haskell
 alonzoMinFeeTx pp tx <+> refScriptsFee
 where 
   refScriptFee = unboundRational (pp ^. ppMinFeeRefScriptCoinsPerByteL)
   refScriptsFee = Coin (floor (fromIntegral @Int @Rational refScriptsSize * refScriptFee)) 
```

**Comment by aniketd** [comment]
@lehins Thank you for such a detailed write up here :heart: :raised_hands: :bow: :muscle:
