### ISSUE TITLE
Test failure on CI in the new `constraint-generator` package 

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4057]
https://github.com/IntersectMBO/cardano-ledger/actions/runs/7805271233/job/21289095718?pr=4050#step:15:4624

```
      Int8
        prop_complete: FAIL (0.02s)
          *** Failed! Falsified (after 52 tests):
          
          genFromSpec
              [Int8]
              TypeSpec (ListSpec [] TrueSpec (TypeSpec [..4] []) (FoldSpec Id (TypeSpec [11..19] []))) []
          
          Can't generate list of ints with fold constraint
            elemSpec = TypeSpec [..4] []
            normElemSpec = TypeSpec [-128..4] []
            foldSpec = TypeSpec [11..19] []
          
          Generating an element:
            elemS = TypeSpec [4..4] []
            foldS = TypeSpec [11..11] []
            fuel  = 12
            lst   = [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,-44,-5,-29,4,-8,0,-25,-10,1]
          
          Fatal error: 
          Ran out of tries on suchThatT
          
          Use --quickcheck-replay=145764 to reproduce.
          Use -p '/listSumRangeUpper.Int8.prop_complete/' to rerun this test only.
```

**Comment by MaximilianAlgehed** [comment]
I think this is just a case of getting _super_ unlucky. @TimSheard has the solution I think.

It would be nice if there was a way of saying "I only want this test to fail ~0.1% of the time" in QuickCheck - but I don't know that there is.

**Comment by lehins** [comment]
> I only want this test to fail ~0.1% of the time

That would mean that test is badly written. I am glad QuickCheck doesn't have something like that.

Yes, looks like Tim has a fix for it.

**Comment by MaximilianAlgehed** [comment]
No, it means that the test is testing a _generator_ meaning that you can get super unlucky.

The point here is that this doesn't become a problem when you're testing non-generator code because you would just discard that test. When you're writing advanced generators it doesn't make sense to say "I never want the generator to fail", but you _do_ want to say "I want this generator to fail so rarely that you can safely discard generation failures at use sites".

**Comment by MaximilianAlgehed** [comment]
Tim's fix isn't a fix, it just moves the probability from 0.1% to 0.05%. The underlying problem - there is no good abstraction for testing generators - persists.

**Comment by lehins** [comment]
> I think this is just a case of getting super unlucky

I've seen this failure personally already twice on two different CI runs. So, am I very lucky or unlucky?

This is a bad test, if we can't fix it properly, we should remove it.

My point is that flaky tests like that really get in a way of our productivity. It takes time away from developers, because we need to investigate each failure on CI. It also affects speed at which we can merge PRs.

**Comment by MaximilianAlgehed** [comment]
You can remove the test, but I think Tims fix probably makes the probability so low there is no problem. But if you want to make the probability of tests passing 100% you will need to remove all tests in that module.

**Comment by MaximilianAlgehed** [comment]
My point is that this is inherent to what the constraint generators is doing. There is no good way to get around this kind of thing when you work with writing generators. You have to deal with some degree of flakiness.

The problem with productivity here is that marginally flaky tests are getting in the way of productivity. The monorepo is the productivity problem.

**Comment by lehins** [comment]
This flaky [test failure is back](https://github.com/IntersectMBO/cardano-ledger/actions/runs/7901452333/job/21565041824?pr=4080#step:15:4599)

We need to dump all of the tests that can fail at random from the test suite.

Flakiness is unacceptable.

**Comment by MaximilianAlgehed** [comment]
You do realise that is all the tests for the constrained-generators package, right?

We need to figure out a way to tell the tests that we want these generators to succeed _most of the time_.

**Comment by lehins** [comment]
> You do realise that is all the tests for the constrained-generators package, right?

I do. Which tells me that those are incorrectly designed tests. Unfortunately we will have to remove them one by one until we see no failures. The reason why this is the way we will solve this problem is very simple: if there is no way to reliably tell an actual failure from a flaky failure then the test is useless. And we should not be wasting our time on it.

> We need to figure out a way to tell the tests that we want these generators to succeed most of the time.

That is an incorrect approach to solving this problem. Feel free to disagree with me, but unless you have a way to fix those tests for them to succeed 100% of the time, they'll have to be removed (or disabled).
