### ISSUE TITLE
Babbage Formal Spec PV2 TxInfo Construction Incorrect for Signatories field

### ISSUE THREAD

**Issue by jmhrpr** [IntersectMBO/cardano-ledger#4095]
The Babbage formal spec states that the Signatories field of the TxInfo construction uses the key hashes from the transaction witnesses, but I think this should actually say `reqSignerHashes` from the transaction body.

![image](https://github.com/IntersectMBO/cardano-ledger/assets/25673452/48a87a56-d4fe-4137-a1d9-39e6cff3febb)

**Comment by WhatisRT** [comment]
Good find! There is the same issue in the Alonzo spec, so it was probably just copied from there.
