### ISSUE TITLE
Stake distribution updates seem to take 4 epochs to reach ratification only for SPO votes

### ISSUE THREAD

**Issue by aniketd** [IntersectMBO/cardano-ledger#4108]
In #4097 , there is a test that demonstrates that, for SPO votes, stake distribution updates (by adding UTxOs) as well as updates to the rewards, take 4 epochs to reach ratification, as opposed to 2 epochs for DRep votes.

- [x] Investigate why there is a difference in the number of epochs needed to ratify
- [ ] ~Either document that this is expected behavior for the future or fix it.~

**Comment by lehins** [comment]
> Either document that this is expected behavior for the future or fix it.

This is not expected behavior. 

Fix is implemented in #4115 
Turns out we were using too old of stake distribution
