### ISSUE TITLE
Start using `huddle` for defining cddl

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4125]
Initial step will be defining alternative CDDL specification for all eras using [`huddle`](https://github.com/input-output-hk/cuddle/blob/a8d6043e012d14057a213169d8dbe4f2b55d44d0/cuddle.cabal#L31)

Once specification is written using `huddle` we can release `cuddle` to Hackage.

The original CDDL will be used as a source of truth for a while until we are confident we can 100% rely on `huddle` to generate readable and accurate CDDL specification.

**Comment by Soupstraw** [comment]
We need to make `cuddle` compile with the GHC versions that we're using in `cardano-ledger` before we can tackle this task

see input-output-hk/cuddle#22
