### ISSUE TITLE
Start using `cuddle` for roundtrip testing

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4126]
Currently we use a `cddl` tool written in Ruby that generates random data according to the cddl spec for us.

We want to start using [`cuddle`](https://github.com/input-output-hk/cuddle/tree/master) to improve our testing

It should be setup in a similar fashion, except the cddl configuration will not be coming from a cddl file, but from the `huddle` specification defined in #4125 

The goal is not to replace the ruby tool, but to improve out testing coverage.

**Comment by nc6** [comment]
This was addressed in #4437, at least going by the "start" keyword. Other eras will come under #4462
