### ISSUE TITLE
Add a NewEpoch event for proposals and their refunds

### ISSUE THREAD

**Issue by kderme** [IntersectMBO/cardano-ledger#4165]
In the EPOCH transition for Conway, the enacted and expired proposals refund the active stake addresses. It would be nice to have a ledger event with the ids of these proposals as well as the returned and unclaimed refunds. This could be a nice place for the event https://github.com/IntersectMBO/cardano-ledger/blob/543e734207ebde5cb97edcdafd12974206a72e72/eras/conway/impl/src/Cardano/Ledger/Conway/Rules/Epoch.hs#L316

**Comment by lehins** [comment]
I think it would actually be best to produce an `Event` that contains the `expiredActions` and `enactedActions` as well as `unclaimed` and a set of governance action ids that didn't claim the refund. This would contain all of the information necessary and more:
* actions that were expired and enacted
* actions and the amounts that were refunds
* actions that didn't get their refunds back as well as the total unclaimed refunds

This event could then be used for things other than tracking refunds.
