### ISSUE TITLE
NoThunks test failure on Nightly

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4184]
Here is the CI failure: https://github.com/IntersectMBO/cardano-ledger/actions/runs/8194048073/job/22409197921#step:15:5620
```
FAIL (3.04s)
      *** Failed! (after 3 tests):
      Exception:
        Thunks present: ThunkInfo {thunkContext = ["Likelihood","Map","rewLikelihoods","RewardSnapShot","PulsingRewUpdate","StrictMaybe","nesRu","NewEpochState","mcsNes","MockChainState"]}
        CallStack (from HasCallStack):
          error, called at src/Test/Cardano/Ledger/NoThunks.hs:51:23 in cardano-ledger-test-9.9.9.9-inplace:Test.Cardano.Ledger.NoThunks
      Use --quickcheck-replay=755182 to reproduce.
      Use -p '/There are no unexpected thunks in MockChainState.Babbage era. Trace length = 100/' to rerun this test only.
    Alonzo era. Trace length = 100:                                   FAIL (0.74s)
      *** Failed! (after 1 test):
      Exception:
        Thunks present: ThunkInfo {thunkContext = ["Likelihood","Map","rewLikelihoods","RewardSnapShot","PulsingRewUpdate","StrictMaybe","nesRu","NewEpochState","mcsNes","MockChainState"]}
        CallStack (from HasCallStack):
          error, called at src/Test/Cardano/Ledger/NoThunks.hs:51:23 in cardano-ledger-test-9.9.9.9-inplace:Test.Cardano.Ledger.NoThunks
      Use --quickcheck-replay=139138 to reproduce.
      Use -p '/There are no unexpected thunks in MockChainState.Alonzo era. Trace length = 100/' to rerun this test only.
    Allegra era. Trace length = 100:                                  FAIL (2.26s)
      *** Failed! (after 3 tests):
      Exception:
        Thunks present: ThunkInfo {thunkContext = ["Likelihood","Map","rewLikelihoods","RewardSnapShot","PulsingRewUpdate","StrictMaybe","nesRu","NewEpochState","mcsNes","MockChainState"]}
        CallStack (from HasCallStack):
          error, called at src/Test/Cardano/Ledger/NoThunks.hs:51:23 in cardano-ledger-test-9.9.9.9-inplace:Test.Cardano.Ledger.NoThunks
      Use --quickcheck-replay=536721 to reproduce.
      Use -p '/There are no unexpected thunks in MockChainState.Allegra era. Trace length = 100/' to rerun this test only.
    Mary era. Trace length = 100:                                     FAIL (4.46s)
      *** Failed! (after 6 tests):
      Exception:
        Thunks present: ThunkInfo {thunkContext = ["Likelihood","Map","rewLikelihoods","RewardSnapShot","PulsingRewUpdate","StrictMaybe","nesRu","NewEpochState","mcsNes","MockChainState"]}
        CallStack (from HasCallStack):
          error, called at src/Test/Cardano/Ledger/NoThunks.hs:51:23 in cardano-ledger-test-9.9.9.9-inplace:Test.Cardano.Ledger.NoThunks
      Use --quickcheck-replay=493906 to reproduce.
      Use -p '/There are no unexpected thunks in MockChainState.Mary era. Trace length = 100/' to rerun this test only.
    Shelley era. Trace length = 100:                                  FAIL (1.64s)
      *** Failed! (after 1 test):
      Exception:
        Thunks present: ThunkInfo {thunkContext = ["Likelihood","Map","rewLikelihoods","RewardSnapShot","PulsingRewUpdate","StrictMaybe","nesRu","NewEpochState","mcsNes","MockChainState"]}
        CallStack (from HasCallStack):
          error, called at src/Test/Cardano/Ledger/NoThunks.hs:51:23 in cardano-ledger-test-9.9.9.9-inplace:Test.Cardano.Ledger.NoThunks
      Use --quickcheck-replay=177461 to reproduce.
      Use -p '/There are no unexpected thunks in MockChainState.Shelley era. Trace length = 100/' to rerun this test only.
5 out of 277 tests failed (1583.79s)
Test suite cardano-ledger-test: FAIL
```

**Comment by neilmayhew** [comment]
I can't reproduce this, unfortunately. I've tried lots of things, and it simply doesn't happen for me.

Things I've tried:

* `git checkout 3bc1fa076c2da18b4d091ed3b77bea1b06c1de40`
* `NIGHTLY=yes cabal test cardano-ledger-test --test-options '-p "/MockChainState.Babbage/" --quickcheck-replay=755182' `
* `NIGHTLY=yes cabal test cardano-ledger-test --test-options '-p "/MockChainState.Babbage/"'` repeated 50 times
* `NIGHTLY=yes cabal test cardano-ledger-test --test-options '--quickcheck-replay=755182'`

I've done these first using `nix develop` and then using a `podman` image that closely mimics what we do in CI, ie uses `ghcup` to install the Haskell toolchain and builds all the dependencies using it.

**Comment by neilmayhew** [comment]
It does seem odd to me that all 5 of the nothunks tests failed in this run, and then several subsequent runs don't have any of those failures.

**Comment by neilmayhew** [comment]
Here are the files I used for the Podman-based testing: [podman.zip](https://github.com/IntersectMBO/cardano-ledger/files/14656798/podman.zip). They might be useful for some other purpose in the future.

**Comment by neilmayhew** [comment]
Just for good measure, I also built a `cardano-ledger-test` with `nix`, using `nix build .#cardano-ledger-test:test:cardano-ledger-test` and ran it as above.

**Comment by neilmayhew** [comment]
I followed up the context information given by `noThunks` and found that it points to this field of `RewardSnapShot`:

```haskell
  , rewLikelihoods :: !(Map (KeyHash 'StakePool c) Likelihood)
```

Here, `Map` is from `Data.Map.Strict`, of course. `noThunks` is saying that the `Likelihood` value in the map is a thunk. That should be impossible, since it's a strict map. I checked all the places in which `rewLikelihoods` is set, and all of them feed strict values into the map. However, there's one place that uses the constructor directly without naming the fields, and that's the `Arbitrary` instance for `RewardSnapShot`:

```haskell
instance Crypto c => Arbitrary (RewardSnapShot c) where
  arbitrary =
    RewardSnapShot
      <$> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
```

So the `arbitrary` instance for `Map (KeyHash 'StakePool c) Likelihood` must be returning a map containing non-strict values, and I was able to verify this in `ghci`. I then wrote a small test program to explore what `arbitrary` is doing for the various datatypes involved here:

```haskell
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}

import Cardano.Ledger.Crypto (StandardCrypto)
import Cardano.Ledger.Keys (KeyHash, KeyRole (..))
import Cardano.Ledger.Shelley.PoolRank (Likelihood)
import Cardano.Ledger.Shelley.RewardUpdate (RewardSnapShot)
import Control.Exception (evaluate)
import Control.Monad ((<=<))
import Data.Map.Strict (Map)
import NoThunks.Class (NoThunks, noThunks)
import Test.Cardano.Ledger.Shelley.Arbitrary ()
import Test.QuickCheck (Arbitrary, arbitrary, generate)

main :: IO ()
main = do
  printNoThunksArbitrary @(RewardSnapShot StandardCrypto)
  printNoThunksArbitrary @(Map (KeyHash 'StakePool StandardCrypto) Likelihood)
  printNoThunksArbitrary @(Map Int Likelihood)
  printNoThunksArbitrary @(Map Int (Maybe Char))
  printNoThunksArbitrary @Likelihood

printNoThunksArbitrary :: forall a. (Arbitrary a, NoThunks a) => IO ()
printNoThunksArbitrary =
  print <=< noThunks [] <=< evaluate <=< generate $ arbitrary @a
```

The `evaluate` is to force the value to at least WHNF, otherwise `noThunks` says that the value itself is a thunk.

The output is:

```
Just (ThunkInfo {thunkContext = ["Likelihood","Map","likelihoodsNM","NonMyopic","rewNonMyopic","RewardSnapShot"]})
Just (ThunkInfo {thunkContext = ["Likelihood","Map"]})
Just (ThunkInfo {thunkContext = ["Likelihood","Map"]})
Just (ThunkInfo {thunkContext = ["Maybe","Map"]})
Nothing
```

So even the `Map` instance that involves none of our types (`Map Int (Maybe Char)`) has thunks in it, which shows the problem isn't in any of our instances, at least not directly.

Also, there are no thunks in the arbitrary `Likelihood`, so the problem isn't inside that type.

**Comment by neilmayhew** [comment]
The `Arbitrary` instance for `Data.Map.Strict.Map` comes from QuickCheck:

```haskell
λ> import Data.Map.Strict (Map)
λ> import Test.QuickCheck (Arbitrary)
λ> :info Map
...
instance (Ord k, Arbitrary k, Arbitrary v) => Arbitrary (Map k v)
  -- Defined in ‘Test.QuickCheck.Arbitrary’
```

However, `Test.QuickCheck.Arbitrary` uses

```haskell
import qualified Data.Map as Map
...
instance (Ord k, Arbitrary k, Arbitrary v) => Arbitrary (Map.Map k v) where
  arbitrary = arbitrary1
  shrink = shrink1

instance (Ord k, Arbitrary k) => Arbitrary1 (Map.Map k) where
  liftArbitrary = fmap Map.fromList . liftArbitrary . liftArbitrary
  liftShrink shr = map Map.fromList . liftShrink (liftShrink shr) . Map.toList
```

so, because of the shared underlying type between lazy and strict maps, the `Arbitrary` instance is shared too, and because it's using the lazy `fromList` there's no forcing of the values.

**Comment by neilmayhew** [comment]
The question is what we should do here. Ideally we'd get it fixed upstream, but I don't see a way to do that because strict and lazy maps are identical at the type level, so they have to share an `Arbitrary` instance. We could make a `newtype` like we did for `StrictSeq`, but it would be a lot of work to change the type in the large number of places we use `Map`.

A compromise solution would be to add a forcing function to all the places we generate an arbitrary strict `Map`.

**Comment by neilmayhew** [comment]
The following avoids thunks in `RewardSnapShot` when used with my test program:

```haskell
forcedArbitrary :: (NFData a, Arbitrary a) => Gen a
forcedArbitrary = force <$> arbitrary

instance Crypto c => Arbitrary (RewardSnapShot c) where
  arbitrary =
    RewardSnapShot
      <$> arbitrary
      <*> arbitrary
      <*> forcedArbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> forcedArbitrary
      <*> forcedArbitrary
```

I had to use `forcedArbitrary` for the `rewNonMyopic` and `rewLeaders` fields as well, otherwise the problem just shifts to those.

**Comment by neilmayhew** [comment]
This is less of a shotgun approach:

```haskell
arbitraryMap :: (Ord k, Arbitrary k, Arbitrary v) => Gen (Map.Map k v)
arbitraryMap = Map.fromList <$> arbitrary

instance Crypto c => Arbitrary (NonMyopic c) where
  arbitrary =
    NonMyopic
      <$> arbitraryMap
      <*> arbitrary
  shrink = genericShrink

instance Crypto c => Arbitrary (RewardSnapShot c) where
  arbitrary =
    RewardSnapShot
      <$> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitrary
      <*> arbitraryMap
      <*> arbitraryMap
  shrink = genericShrink
```

Ideally, we'd find a way to hide the `Arbitrary` instance for `Map` so we'd be forced to use `arbitraryMap` everywhere a `Map` is needed, but I don't think there's a way to do that. We could instead just expand our suite of NoThunks tests.

**Comment by neilmayhew** [comment]
For some reason, I completely missed the fact that the failures happen only with ghc 9.8.1!

I can now reproduce the problem reliably, and, sad to say, neither of my "fixes" (in ledger or in QuickCheck) fix the problem :sob:

**Comment by neilmayhew** [comment]
I've found the problem, and it turns out to be the bug I thought I'd found (in `containers`) on my first day of looking at this, which I then second-guessed and decided wasn't a bug.

There's an easy workaround that I'll add to the PR.
