### ISSUE TITLE
Unclear Certificate mapping to on-chain data representation

### ISSUE THREAD

**Issue by michele-nuzzi** [IntersectMBO/cardano-ledger#4227]
some certificates are not directly represented on-chain

an example is [`stake_vote_deleg_cert`](https://github.com/IntersectMBO/cardano-ledger/blob/ab8d57cf43be912a336e872b68d1a2526c93dc6a/eras/conway/impl/cddl-files/conway.cddl#L284C6-L284C27)

used to simultaneously delegate staking credentials to a stake pool and a drep.

The [`PlutusLedgerApi` module doesn't allow for any such certificate](https://github.com/IntersectMBO/plutus/blob/f168bc125021356f39ee2b1b537cb69bbc39997b/plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs#L1309)

should `stake_vote_deleg_cert` be mapped to 2 different `TxCertDelegStaking` certificates? if yes, in which order are reported in the ScriptContext?

**Comment by lehins** [comment]
This is the certificate on the Plutus side: https://github.com/IntersectMBO/plutus/blob/f168bc125021356f39ee2b1b537cb69bbc39997b/plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs#L135-L136

See the definition of the [`Delegatee`](https://github.com/IntersectMBO/plutus/blob/f168bc125021356f39ee2b1b537cb69bbc39997b/plutus-ledger-api/src/PlutusLedgerApi/V3/Contexts.hs#L118) and it will become clear. Let me know if it is still unclear. 

Closing as there is nothing to do on our side.
