### ISSUE TITLE
Ensure translations of Conway types for conformance testing is exhaustive 

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4254]
There are still some aspects of ledger implementation that are not fully translated to the spec representation (eg. hash protection: https://github.com/IntersectMBO/cardano-ledger/pull/4212#discussion_r1557580588 and script support: https://github.com/IntersectMBO/cardano-ledger/pull/4212#discussion_r1557501161)

This ticket tracks that all types have been properly translated in conformance testing

MAlonzo types that need to be improved:
- [x] `PParamsUpdate`
- [ ] `Script`
- [x] `Network`
- [x] `DataHash`

There's probably more types that can be improved, see `LedgerTypes` in the formal spec.

**Comment by Soupstraw** [comment]
There's an issue about improving scripts in the formal spec
https://github.com/IntersectMBO/formal-ledger-specifications/issues/405
