### ISSUE TITLE
Conformance testing of the UTXO rule

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4256]
Currently testing of GOV rule is disabled in the conformance testing, which needs to be fixed. Quote from https://github.com/IntersectMBO/cardano-ledger/pull/4212#discussion_r1557723923

> The constraints used in the UTXO rule are still incomplete. 

# Checklist

- [x] `RATIFY`
- [x] `GOVCERT`
- [x] `POOLS`
- [x] `DELEG`
- [ ] `UTXO` (waiting for the generators)

**Comment by Soupstraw** [comment]
Closed by #4660
