### ISSUE TITLE
Specify numeric ranges explicitly in CDDL

### ISSUE THREAD

**Issue by klntsky** [IntersectMBO/cardano-ledger#4296]
It seems that `int` and `uint` types do not have a default range in CDDL, thus making the spec effectively implementation-defined.

E.g. https://github.com/IntersectMBO/cardano-ledger/blob/3ce23865480b3e2bf69d286775dc388d7b465d4b/eras/conway/impl/cddl-files/conway.cddl#L514

**Comment by lehins** [comment]
@klntsky The example you posted is actually an arbitrary precision integer. There are no bounds in the CDDL spec `int` as well as the implementation: https://github.com/IntersectMBO/cardano-ledger/blob/2f0ad36b34ee0bb97ce961c016981e48597380f7/libs/cardano-ledger-core/src/Cardano/Ledger/Metadata.hs#L56

The only limiting factor in this case is the limit on the transaction size.

That being said, I did a quick scan and it does seem like there are places in the CDDL spec where we do not specify the bounds, while in the actual implementation we do enforce strict bounds. 

Thank you for reporting this issue, we'll go through the spec and adjust it accordingly.
