### ISSUE TITLE
`translateUpperBoundForPlutusScripts` clarification

### ISSUE THREAD

**Issue by zuzunker** [IntersectMBO/cardano-ledger#4331]
Hi! Can someone plz help clarify. In the Plutus function transValidityInterval there’s a hardfork check for `HardForks.translateUpperBoundForPlutusScripts.`

Am I getting it right that the only affected case is when NO `validity_interval_start` is specified in the transaction and SOME `ttl` is specified, and the only change is that an interval structure like `Interval (NegInf, ttl_posix)`  is returned instead of `TO ttl_posix` ?

But the values are still in **posix timestamps** and the case when **only** `validity_interval_start` is specified with **no** TTL is not changing and it still returns `FROM validity_start_posix` and not an interval? Which also means the `PosInf` value is never returned at all?

https://github.com/IntersectMBO/cardano-ledger/blob/dbb9f4e846f17660f7690301a4f23da1dfb842df/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/TxInfo.hs#L177-L208

**Comment by lehins** [comment]
> Am I getting it right that the only affected case is when NO validity_interval_start is specified in the transaction and SOME ttl is specified, and the only change is that an interval structure like Interval (NegInf, ttl_posix) is returned instead of TO ttl_posix ?

Yes, except the difference is `Interval (NegInf, ttl_posix)` vs `Interval (NegInf, ttl_posix]`

This whole `translateUpperBoundForPlutusScripts` only fixes the upper bound to being strict.

> Which also means the PosInf value is never returned at all?

`PosInf` is only relevant when the upper bound is missing and it is returned by the means of `always` and `from`:

* https://github.com/IntersectMBO/plutus/blob/9326493dddb036b7e2e8f443112b8e524f3fd361/plutus-ledger-api/src/PlutusLedgerApi/V1/Interval.hs#L310
* https://github.com/IntersectMBO/plutus/blob/9326493dddb036b7e2e8f443112b8e524f3fd361/plutus-ledger-api/src/PlutusLedgerApi/V1/Interval.hs#L299

Does this answer your questions? Please, feel free to reopen the issue if this is still not clear.
