### ISSUE TITLE
Avoid types with infinite precision in the protocol parameters

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4360]
There are a few parameters that are defined using `Natural`. This will be problematic starting with Conway, because anyone can submit proposals on-chain values that are total garbage and we'll have to support them indefinitely.

For this reason we need to set them to sensible `WordX` values in the ConwayPParams type. However, in order to reduce breakage we should keep the types for relevant lenses unchanged. This will make setters partial, but that is already the case with `Natural`, so this should not be a problem.

These changes should also be reflected in the cddl specification.

**Comment by teodanciu** [comment]
Completed in https://github.com/IntersectMBO/cardano-ledger/pull/4357
