### ISSUE TITLE
Switch to using Plutus testingCostModels instead of zero models in Tests

### ISSUE THREAD

**Issue by teodanciu** [IntersectMBO/cardano-ledger#4404]
Because of an issue in testingCostModels from Plutus, we had to set our costmodels to zero values in order to get the tests to pass for the [CIP-0069 PR](https://github.com/IntersectMBO/cardano-ledger/pull/4374/commits).  

Once the problem is solved in Plutus, we have to revert to the cost models they provide, for more realistic tests.

**Comment by lehins** [comment]
Is there a relevant issue on the Plutus repo that we can cross reference?

**Comment by teodanciu** [comment]
Relevant Plutus issue is this: https://github.com/IntersectMBO/plutus/issues/6089
