### ISSUE TITLE
SanchoNet tx incompatible with Conway CDDL

### ISSUE THREAD

**Issue by scarmuega** [IntersectMBO/cardano-ledger#4421]
There seems to be a Tx in SanchoNet that doesn't respect Conway CDDL:
- tx hash: `ea3d309d4ef836cf0aea7e2b5f70537ca82e647754958ff191d5162b55036838`
- block slot: `31412056`
- block hash: `1240f59bd88d16f4f6e425ae60935926985478965e37b73b5b85276625bcbe82`

As far as I can tell, the specified Tx includes the following protocol parameter updates:
- collateral percentage = `18446744073709551615`
- max collateral inputs = `18446744073709551615`

but the CDDL for Conway specifies that those two parameters should be `uint .size 2`, which can't hold such large values:

https://github.com/IntersectMBO/cardano-ledger/blob/cb30d895b866ccd5d8c529212208aca0c913b9c2/eras/conway/impl/cddl-files/conway.cddl#L401

Is my analysis correct? If so, does this require an adjustments at the CDDL level?

**Comment by aniketd** [comment]
This is an intended [recent change](https://github.com/IntersectMBO/cardano-ledger/pull/4357/files#diff-2db82f5dbfb4a80856bebe363f5c1fd257cfa32e9214a3307492f4f73163161aR401), for context.

**Comment by scarmuega** [comment]
thanks @aniketd. Can we then assume thats txs like the specified in the issue won't make it on-chain in future versions of the node?

**Comment by lehins** [comment]
> Can we then assume thats txs like the specified in the issue won't make it on-chain in future versions of the node?

@scarmuega That is correct. We intentionally restricted types only to reasonable values. Starting with node-8.12 transactions like that will not make it on chain
