### ISSUE TITLE
Missing Documentation per OSC Governance

### ISSUE THREAD

**Issue by Ranchhand87** [IntersectMBO/cardano-ledger#4439]
The following documents/features are suggested by OSC Governance: Issue Template

For Reference: https://intersect.gitbook.io/open-source-committee/policies/governance
Also see Documentation and Legal

**Comment by lehins** [comment]
I am not sure what is the ask here?

Are you suggesting we create a Github issue template?

**Comment by Ranchhand87** [comment]
Yes, please write an Issue template for common issues filed against this repo. Please advise if you would like a Template.

**Comment by lehins** [comment]
As far as I understand, this is just a suggestion from OSC, not a requirement.

We are doing pretty good without a template. 

As far as I am concerned it is totally fine to have a free form issue. If and when we get more issues created by other people except maintainers of the repo, then I will re-evaluate this decision, but for now, I prefer not to have a template. 

Thank you for your suggestion though.
