### ISSUE TITLE
Update nothunks dependency.

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-ledger#4504]
In https://github.com/IntersectMBO/cardano-ledger/pull/4451 I added the contstraint:
```
        nothunks ^>=0.1.5,
```
Newer versions of `nothunk` have a API which adds a `Maybe` to one of the return types.

**Comment by lehins** [comment]
Could you please provide a bit more info? Looking through the haddock I can't see any changes in type signatures of functions in `nothunks` between 1.5 and 2.0
