### ISSUE TITLE
are votes part of the governance snapshot?

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#4507]
if a snapshot is taken for the governance world, are the votes parts of it? if so can we query them?

if not, do votes made during the ratification process are considered if they are submitted just before pulser is executing ratification?

in ref - https://github.com/IntersectMBO/cardano-ledger/issues/4491

**Comment by lehins** [comment]
Sorry @ashisherc, but Github issue tracker is not really meant for QA.

I'd recommend trying Intersect's Discord channel or StackOverflow instead.

I will respond to these questions this time, but I'd appreciate resorting Github issue tracker for things like feature requests or bug reports.

> are the votes parts of it?

Yes

> if so can we query them?

[`GovState`](https://github.com/IntersectMBO/cardano-ledger/blob/88d788500ceb2b4bc5215afb6ebe6fd73972baf1/libs/cardano-ledger-api/src/Cardano/Ledger/Api/State/Query.hs#L133-L134) will give you [`ConwayGovState`](https://github.com/IntersectMBO/cardano-ledger/blob/88d788500ceb2b4bc5215afb6ebe6fd73972baf1/eras/conway/impl/src/Cardano/Ledger/Conway/Governance.hs#L235-L250) which contains **everything** that is governance related.

> if not, do votes made during the ratification process are considered if they are submitted just before pulser is executing ratification?


If I understand the question correctly, then no. That is the point of taking a snapshot: it becomes immutable and no external action can affect it.

**Comment by ashisherc** [comment]
Just tested voting for an action, and the gov state does update in real time with the new votes casted. So are you sure you are referring to the correct gov state query for the snapshot that does not update?

--
query - cardano-cli conway query gov-state

action id - 8c4155d0567ce236c2182431e687f88b7be300074c4d32050bc530516ba8281b#0

casted yes by - drep - keyHash-8f4fefcf28017a57b41517a67d56ef4c0dc04181a11d35178dd53f4c

gets updated in the current epoch itself - sancho - 9.0.0
