### ISSUE TITLE
Document that duplicate reference scripts between reference inputs & spend inputs are not conciderd for fee computation

### ISSUE THREAD

**Issue by sourabhxyz** [IntersectMBO/cardano-ledger#4539]
*External*

**Summary**
[`txNonDistinctRefScriptsSize`](https://github.com/IntersectMBO/cardano-ledger/blob/7e65f0365eef647b9415e3fe9b3c35561761a3d5/eras/conway/impl/src/Cardano/Ledger/Conway/UTxO.hs#L149-L156), according to it's haddock, should account for duplicate scripts. The same input can be present as both reference input & spend input inside the transaction body (as an example, see [this](https://preprod.cardanoscan.io/transaction/4b5ee7d4c7a87d3b54c91fc245d224b7fbf4a4e95e18c2b5e8bd365eb355d8f4?tab=summary) transaction, submitted on pre-production testnet, where first spend input is same as first reference input) however `Set.union` suggest that duplicates there are masked!

**Comment by lehins** [comment]
Sure, that is in case when duplicate inputs are supplied in regular inputs and reference inputs. This is in fact the desired behavior, but that doesn't mean we should not document it in the haddock of the function.

**Comment by lehins** [comment]
Relevant PR #4550
