### ISSUE TITLE
Why remove documentation of script_data_hash in conway CDDL?

### ISSUE THREAD

**Issue by mpizenberg** [IntersectMBO/cardano-ledger#4556]
Conway CDDL used to include the documentation of how the script_data_hash is computed. But that information was removed in commit https://github.com/IntersectMBO/cardano-ledger/commit/80b10eb3cd9068839d9052d48d154c0299946837

It is information really needed by every offchain cardano framework out there. Has this information been moved elsewhere?

https://github.com/IntersectMBO/cardano-ledger/blob/676ffc5c3e0dddb2b1ddeb76627541b195fefb5a/eras/conway/impl/cddl-files/conway.cddl#L176

**Comment by lehins** [comment]
Closing as duplicate of #4522 

> Why remove documentation of script_data_hash in conway CDDL?

We recently made a drastic switch from defining CDDL spec manually to generating it from a Haskell definition. In the process of doing that we lost most of the comments, which are now being brought back in #4552 and #4553 In the matter of fact this PR https://github.com/IntersectMBO/cardano-ledger/pull/4554 also fixes the comment for `script_data_hash` for Conway

Thank you for raising your concern! Makes us appreciate how many people use the CDDL specification that we write :slightly_smiling_face:

**Comment by mpizenberg** [comment]
Thank you for the explanation and the pointers
