### ISSUE TITLE
Semantic & signification of RatifyState

### ISSUE THREAD

**Issue by KtorZ** [IntersectMBO/cardano-ledger#4641]
Hello! Would anyone be kind to document the semantic and signification of the `RatifyState` type and its sub-components:

https://github.com/IntersectMBO/cardano-ledger/blob/8d16d698dd499fd171845da16611c7c7026c1754/eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Internal.hs#L268-L273

I know the type is part of an `Internal` module, but it is now exposed to end-users through the local-state-query protocol via the `GetRatifyState` query. In order to make this query available to a larger audience, I'd be thankful to get clarification on the various components of its result. 

Thanks.

**Comment by lehins** [comment]
The fact that it is defined in an Internal module, does not make it "internal". It is exposed to the world through public modules and there is even a query for it :smiley: That does not mean that we should not document it! So, thank you for opening this issue.

The gist of it is that it represents what will happen at the next epoch boundary with respect to the governance. For example if a governance action is listed in `rsEnacted` it means that it will be enacted on the next epoch boundary and its affect is already applied in the `rsEnactState`. So, in reality the affect of enactment on the epoch boundary is just applying the values from the `EnactState` to the `GovState` in the ledger state.
